LizardByte/Sunshine

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/label-actions.yml
- .github/pull_request_template.md
- .github/workflows/issues-stale.yml
- .github/workflows/issues.yml
- .github/workflows/pull-requests.yml
Add .github folder:
- ISSUE_TEMPLATE
- workflows
- etc.
Include screenshots if the changes are UI-related.
- Fixes #(issue)
> Add TEMPLATES and WORKFLOWS

- CHANGELOG.md
- changelog parser action fails if "v" is in prefix
- action has already been updated ("v" prefix is added)
- https://github.com/SunshineStream/actions/blob/29f0d30310e1b7bf7fa251b2b0c1bddcf47fe5a2/verify_changelog/action.yml#L26
- https://github.com/SunshineStream/actions/blob/29f0d30310e1b7bf7fa251b2b0c1bddcf47fe5a2/verify_changelog/action.yml#L47
- https://github.com/SunshineStream/actions/blob/29f0d30310e1b7bf7fa251b2b0c1bddcf47fe5a2/verify_changelog/action.yml#L58
> Fix changelog_parser action

- sunshine/video.cpp
Change cherry-picked from @psyke83 repository. It has a real impact on stream quality on my various tests.
* Increase vbv-bufsize to 1/10 of requested bitrate. The previous value
was too low, which was resulting in poor encoding quality and failure to
stabilize at the requested bitrate. Setting to 1/10 of bitrate is a
good compromise, as it avoids quality loss but also prevents bandwidth
spikes far above the bitrate/vbv-maxrate.
* With vbv-bufsize set to a more appropriate value, testing shows that
the average bitrate vs client-requested bandwidth overshoots by ~20%.
Adjust for this scenario in the software encoding case only.
N/A
N/A
> video: use a better vbv-bufsize & correct software bitrate calculation

- assets/web/config.html
- assets/web/header.html
- assets/web/pin.html
- assets/web/welcome.html
Minor fixes to the Web UI, updated messages to make sure they are correct
> UI Web Fixes

- assets/sunshine.conf
- assets/web/config.html
- `sunshine.conf`
- Rename `amd_preset` to `amd_quality`
- Document `key_rightalt_to_key_win`
- `config.html`
- Fix some typos
- Reformat some tags
- Fixes #45 
> Fix sample config

- .github/dependabot.yml
- .github/workflows/clang.yml
- sunshine/confighttp.cpp
- sunshine/httpcommon.cpp
- sunshine/main.cpp
- sunshine/nvhttp.cpp
- sunshine/platform/linux/audio.cpp
- sunshine/platform/linux/x11grab.h
- sunshine/platform/windows/misc.h
- sunshine/process.cpp
- sunshine/utility.h
- sunshine/video.cpp
- Add clang linter
- Add dependabot (github action dependencies only)
> Add clang linter

- .clang-format
- .github/workflows/clang.yml
- .gitmodules
- CMakeLists.txt
- Portfile
- README.md
- assets/apps_mac.json
- assets/info.plist
- assets/sunshine.conf
- assets/web/config.html
- sunshine/config.cpp
- sunshine/config.h
- sunshine/input.cpp
- sunshine/platform/common.h
- sunshine/platform/macos/av_audio.h
- sunshine/platform/macos/av_audio.m
- sunshine/platform/macos/av_img_t.h
- sunshine/platform/macos/av_video.h
- sunshine/platform/macos/av_video.m
- sunshine/platform/macos/display.mm
- sunshine/platform/macos/input.cpp
- sunshine/platform/macos/microphone.mm
- sunshine/platform/macos/misc.cpp
- sunshine/platform/macos/misc.h
- sunshine/platform/macos/nv12_zero_device.cpp
- sunshine/platform/macos/nv12_zero_device.h
- sunshine/platform/macos/publish.cpp
- sunshine/rtsp.cpp
- sunshine/video.cpp
This patch set introduces initial support for MacOS as third major host platform. It relies on the VideoToolbox framework for audio and video processing, which enables hardware accelerated processing of the stream on most platforms. Audio capturing requires third party tools as MacOS does not offer the recording of the audio output like the other platforms do. The commit enables most features offered by Sunshine for MacOS with the big exception of gamepad support. The patch sets was tested by a few volunteers, which allowed to remove some of the early bugs. However, several bugs especially regarding corner cases have probably not surfaced yet. 
Besides instructions how to build from source, the commit also adds a Portfile that allows a more easy installation. After available on the …
> Initial support for MacOS

- .github/workflows/CI.yml
- CMakeLists.txt
- gen-deb.in
- sunshine.desktop.in
> Get version from CMakeLists

- sunshine/video.cpp
This fixes a bad sigsegv on AMD GPUs (maybe others too, though I've only seen it reported on AMD) running on Linux. Basically, because of the order of the members in session_t, hwdevice would be destroyed before the avcodec context. This causes problems because the context relies on the hwdevice still being active - as in, when the hwdevice is destroyed the dri library is unloaded, and va calls methods in there.
Here's a backtrace of the sigsegv:
```txt
#0  0x00007fffe6f39630 in  () -> (this is supposed to be si_resource_destroy in radeonsi_drv_video.so but because it's unloaded it no longer exists)
#1  0x00007fff7835dea1 in pipe_resource_destroy (res=<optimised out>)
#2  pipe_resource_reference (src=0x0, dst=0x5555578c0e88)
#3  vlVaDestroyBuffer (ctx=0x555556997b30, buf_id=5)
#4 …
```
> Fix hwdevice being destroyed before context causing sigsegv on AMD

- sunshine/stream.cpp
This adds exception handling in the stream broadcast handler threads. This is necessary, because, for instance, if the host's network disconnects, sock.send_to would throw an exception - which would lead to a crash.
- Fixes #112 
> Properly catch exceptions in stream broadcast handlers

- sunshine/stream.cpp
- sunshine/video.cpp
- sunshine/video.h
This PR changes the codebase to wrap AVPacket instead of extending it.
According to ffmpeg's documentation: 
>sizeof(AVPacket) being a part of the public ABI is deprecated. once av_init_packet() is removed, new packets will only be able to be allocated with [av_packet_alloc()](https://ffmpeg.org/doxygen/trunk/group__lavc__packet.html#gaaf85aa950695631e0217a16062289b66), and new fields may be added to the end of the struct with a minor bump.
I believe this to mean extending AVPacket is fragile and prone to break if things are changed in ffmpeg
In this case, the extended struct did not clear the memory for AVPacket.opaque_ref, so it was not guaranteed to be correctly set to nullptr.
That meant that when encode was called it would try to free a random pointer (since opaque_ref is a AVBuffer) …
> AVPacket Fix

- sunshine/audio.cpp
- sunshine/platform/linux/audio.cpp
A number of small improvements were made to the Linux platform audio code to improve user experience and improve Pipewire compatibility.
- Fixed a bug in the base Audio code that caused it to select the virtual sink even if you had a different on selected in the config.
- Added functionality to get monitor names and default sink names.
- The recording code now properly uses the monitor of the provided/selected sink.
- Records the default sink as the sink to restore after streaming instead of the last sink encountered in the list.
- Reliably switches the recorded sink to be the default
- Updated example config to be clear to provide the SINK name to monitor.
I have tested the following scenarios to work correctly under Pipewire. Additional testing under pulse would be ideal. The code …
> Improved Pulse/Pipewire Compatibility for Linux.

- scripts/Dockerfile-fedora_33
- scripts/Dockerfile-fedora_35
The Fedora 35 docker image doesn't have libcap development files, hence the CMake checks won't enable KMS support. (SUNSHINE_ENABLE_DRM depends on the libcap dev files)
> f35: add libcap-devel to enable KMS code

- CMakeLists.txt
- docs/source/about/advanced_usage.rst
- src_assets/common/assets/web/config.html
- sunshine/config.cpp
- sunshine/config.h
- sunshine/platform/windows/display.h
- sunshine/platform/windows/display_base.cpp
Adds  DwmFlush() call before acquiring a new frame to resolve framerate stuttering observed when moving the mouse.  For more context, see (obsolete) PR and issue from upstream that describes the problem in detail:
https://github.com/loki-47-6F-64/sunshine/issues/227
https://github.com/loki-47-6F-64/sunshine/pull/286
Please note that I had to include a very minor but unrelated fix for VideoToolbox variables missing from the video_t struct, as this needed to be fixed in order to accommodate the new `dwmflush` entry correctly.
- Fixes https://github.com/loki-47-6F-64/sunshine/issues/227
~~Potential breakage only in specific circumstances when enabled: DwmFlush() constrains the framerate to the host computer's monitor refresh rate, so it may cause issues if the client is streaming at an FPS …
> platform/windows: add DwmFlush() call to improve Windows capture

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
Adding `--talk-name=org.freedesktop.Flatpak` as this is needed to launch applications on the host. Example: `flatpak-spawn --host sleep 1m`.
> Add permission for Flatpak.

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- sunshine/config.cpp
This PR changes behavior of the config and apps files.
- default files will be copied to the user's home config directory on linux
- default files will be copied to the working directory on Windows
> sunshine.conf and apps.json on user's home config dir

- .github/workflows/winget.yml
Continuation of #203 since it cannot be reopened.
[This action](https://bittu.eu.org/docs/wr-intro) automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
Before merging this:
1. ~Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).~ @LizardByte-bot's PAT is used in the workflow.
2. Fork https://github.com/microsoft/winget-pkgs under @LizardByte
3. Make sure the PAT owner has signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) for winget-pkgs.
If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro), and the source …
> Add winget releaser action

- CHANGELOG.md
- scripts/_locale.py
- fix src directory for localization
- update changelog for v0.14.1
- Fixes #313
> Prepare v0.14.1

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- packaging/macos/Portfile
- Update boost to 1.80.0 (flatpak)
> Update boost to 1.80.0 (flatpak/macport)

- .github/workflows/CI.yml
> add nightly release

- .readthedocs.yaml
- README.rst
- docs/requirements.txt
- docs/source/about/advanced_usage.rst
- docs/source/about/installation.rst
- docs/source/about/third_party_packages.rst
- docs/source/about/usage.rst
- docs/source/building/build.rst
- docs/source/building/linux.rst
- docs/source/building/macos.rst
- docs/source/building/windows.rst
- docs/source/conf.py
- docs/source/contributing/contributing.rst
- docs/source/contributing/localization.rst
- docs/source/contributing/testing.rst
- docs/source/troubleshooting/general.rst
- docs/source/troubleshooting/linux.rst
- docs/source/troubleshooting/macos.rst
- docs/source/troubleshooting/windows.rst
- scripts/requirements.txt
> change docs theme to `furo`

- docs/source/troubleshooting/general.rst
The command to create new credentials via the terminal has a typo, one dash instead of two.
> Fix credentials command typo in docs

- .docker_platforms
- DOCKER_README.md
- add linux/arm64/v8 docker platform
> add linux/arm64/v8 docker platform

- CMakeLists.txt
- src/input.cpp
- src/platform/common.h
- src/platform/linux/input.cpp
- src/platform/macos/input.cpp
- src/platform/windows/input.cpp
The Moonlight PC client allows pasting UTF-8 from the client to the server using the Ctrl+Alt+Shift+V hotkey. Under the hood, this grabs the clipboard text and uses `PNV_UNICODE_PACKET` messages to send UTF-8 characters to the host.
This PR adds support for `PNV_UNICODE_PACKET` on Windows. We convert the UTF-8 bytes to UTF-16 and inject them via `SendInput()`. The focused application will receive them as `WM_CHAR` messages.
I needed to pull the latest `moonlight-common-c` which required some changes to input.cpp and allowed us to get rid of the qos2.h hack too. This change is in a separate commit for easier review.
- Fixes #519
> Add support for UTF-8 input messages on Windows

- CHANGELOG.md
- CMakeLists.txt
The multiarch path (e.g. /usr/lib/x86_64-linux-gnu) is not the correct path for these files.
> CMake: Linux: use standard FreeDesktop udev/systemd paths

- .github/ISSUE_TEMPLATE/bug-report.yml
> update issue template

- src/video.cpp
* Revert previous change to software bitrate calculation & bufsize. I was not aware that Moonlight-QT internally scales the requested bandwidth by 75% if HEVC is selected.
* Add back a more conservative bufsize increase. This still appears to resolve the quality degradation issue seen when using 8/16 slices, and may hopefully resolve the RPI3 decoder issues in #478.
Closes #478
> Video: revert software bitrate change & use more conservative bufsize

- src/video.cpp
If `delay` is not set manually, it defaults to INT_MAX, which is then reduced to number of surfaces - 1, which can potentially cause encode delay.
See: 
https://github.com/FFmpeg/FFmpeg/blob/eb1e359a14e04367239a784506e1ae414512a104/libavcodec/nvenc_hevc.c#L110-L111
https://github.com/FFmpeg/FFmpeg/blob/eb1e359a14e04367239a784506e1ae414512a104/libavcodec/nvenc.c#L961
https://forums.developer.nvidia.com/t/nvenc-hevc-ultra-low-latency-with-ffmpeg-libraries-what-should-be-my-expectations/143954/5
Note that I don't own NVIDIA hardware, so this change needs testing by someone else.
> video: reduce nvenc delay/async_depth to 0

- .gitmodules
- src/confighttp.cpp
- src/nvhttp.cpp
This PR changes the `Simple-Web-Server` submodule to the upstream actively maintained version. It turns out that all functionality that was specific to our fork was either implemented upstream or could be achieved without modifying the `Simple-Web-Server` code itself (by creating a class derived from `SimpleWeb::Server<HTTPS>`).
> Migrate to upstream Simple-Web-Server submodule

- src/video.cpp
Reducing maximum processing parallelism to minimum should improve latency for realtime encoding.
> video: vaapi: reduce async_depth to 1

- src/crypto.cpp
- src/crypto.h
This PR fixes deprecation warnings in crypto.cpp due to use of legacy low-level SHA256/RSA APIs. I have replaced these with the high-level EVP equivalents as suggested by the OpenSSL 3.0 migration guide.
> Avoid using functions deprecated in OpenSSL 3.0

- CMakeLists.txt
Ref: https://github.com/boostorg/log/issues/177
> CMakeLists: win32: fix build against boost 1.81.0-1+

- src/process.cpp
- src_assets/windows/assets/apps.json
`boost::process::environment` uses a case-sensitive match when looking up environment variables, but Windows variables (especially `PATH`) tend to behave case-insensitively. Because the name of the Windows variable is `Path`, not `PATH`, we would attempt to concatenate `;C:\Program Files (x86)\Steam` to the `PATH` but end up overwriting the entire thing because `env["PATH"]` returned an empty string.
Our `PATH` value itself was also incorrectly hardcoded such that a system where the `Program Files (x86)` folder (or the whole Windows installation) did not reside on the C: drive would not be able to launch Steam.
[Allow …
> Fix PATH variable handling on Windows

- tools/sunshinesvc.cpp
This fixes a bug in SunshineSvc where it would not properly inform the Service Control Manager when startup failed. Without a call to `SetServiceStatus()`, SCM will just keep waiting for us until a system-wide service start timeout expires, even though we returned from `ServiceMain()`. The actual error that led us to fail startup will be lost and never logged.
With this change, we properly report errors back to SCM during startup, so `net start` and the Event Log will correctly display the failure and the error code.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/w …
> Fix SunshineSvc hanging if an error occurs during startup

- tools/sunshinesvc.cpp
This fixes an issue reported by DemonCat on Discord where SunshineSvc could not be restarted if it crashed or was forcefully terminated by the user. This happened because the now orphaned child Sunshine.exe held on to the handle to the log file that SunshineSvc created for it (which was being used as its `stdout` and `stderr`).
SunshineSvc doesn't have really any complicated logic post-startup, so the only real reason it's likely to die in the real world is if a user kills it to try to stop Sunshine. The current behavior of leaving Sunshine.exe running definitely isn't doing what the user wants, and doubly so if they can't even start SunshineSvc again afterwards.
must be …
> Spawn Sunshine.exe in a job object, so it is terminated if SunshineSvc.exe dies

- src/platform/windows/display_base.cpp
We had an incorrect assumption that the DXGI format of the mode in `DXGI_OUTDUPL_DESC` was the format of the frames that we will receive from `AcquireNextFrame()`.
This is incorrect as [MSDN](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api) states:
> The format of the desktop image is always DXGI_FORMAT_B8G8R8A8_UNORM no matter what the current display mode is.
This is why we thought we were getting formats like `DXGI_FORMAT_R16G16B16A16_FLOAT` (in HDR) and `DXGI_FORMAT_R8G8B8A8_UNORM` (in Vulkan apps). This change "fixes" streaming with HDR enabled (though output is clipped to SDR, causing it to look blown out). However, HDR can be successfully toggled off while streaming, which then streams a correct SDR image.
cc: @psyke83 
Blown out HDR streaming (but …
> Fix streaming with non-B8G8R8A8 desktop mode

- src/platform/windows/display.h
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
Pixel pitch was being calculated incorrectly for `DXGI_FORMAT_R16G16B16A16_FLOAT` (which is a 64-bit format), so our buffers weren't large enough to contain the full image. Additionally, `display_vram_t::dummy_img()` had a subtle bug where it was using `int[]` as the data buffer type (which is 4 bytes per element) instead of using `uint8_t[]` and the actual `pixel_pitch` value.
The combination of these would cause the display driver to read out of bounds inside `CreateTexture2D()` when attempting to populate the dummy texture during initialization if HDR was enabled in Windows.
With this change, Sunshine can now initialize without crashing on systems with HDR enabled. For semi-usable streaming, we also need #522 merged.
LizardByte requires that branches be up-to-date before merging. This …
> Fix pixel pitch handling for DXGI_FORMAT_R16G16B16A16_FLOAT

- CMakeLists.txt
Package mingw-w64-x86_64-headers-git 10.0.0.r186.gfc55e181b-1 defines _WIN32_WINNT as 0x601, but boost is built against the r157 headers that defined this preprocessor as 0x603, leading to static link issues.
This fixes the issue, but if a future version of boost is released, it will be built against the r186 headers and therefore may require further action to restore compatibility.
> CMake: win32: further fix for boost linker incompatibility

- packaging/macos/Portfile
`boost.version` automatically adds the correct boost port dependency, removing `port:boost180` to avoid. See https://github.com/macports/macports-ports/blob/0cb1b3a7edb791ed0464eea6bc5b77294ee248bf/_resources/port1.0/group/boost-1.0.tcl#L61
Installed successfully with this change on an M1 MacBook Pro.
> Remove duplicate boost port

- src/platform/windows/display_vram.cpp
VSSetConstantBuffers was not passing the constant buffers for the vertex shader correctly. Resolve by initializing vertex buffers at the same time as the pixel shader buffers are updated to change the colourspace.
Also fix width_i float to use out_width_f to account for aspect ratio scaling.
Before:
After:
Resolves #608 
> windows/vram: fix fringing in NV12 colour conversion

- .github/workflows/CI.yml
- CMakeLists.txt
- Dockerfile
- docs/source/building/linux.rst
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.cpp
- src/platform/windows/misc.cpp
- src/process.cpp
This implements a new `platf::run_unprivileged()` function that can be used (on Windows, currently) to launch a process as the active console user (including their environment variables).
In order to make this work, I had to fix issues with the way we derive the working directory if one is not provided. That required adding a dependency on `libboost-program-options` for `boost::program_options::split_unix()` to perform proper command-line parsing to retrieve the actual binary name.
This could definitely use some testing since there are a _ton_ of use cases to cover.
Resolves #521  …
> Launch games under the correct user account on Windows

- src/audio.cpp
- src/audio.h
- src/rtsp.cpp
This PR implements the proper audio bitrate logic needed to support high-quality stereo and surround when requested by Moonlight. The audio bitrate values match those used by GFE in those various audio configurations.
It fixes issues with variable-sized audio packets due to the `OPUS_BITRATE_MAX` workaround that would cause audio FEC to be disabled in Moonlight when streaming surround sound. Audio FEC is important to avoid audible artifacts due to dropped audio packets.
It fixes issues with 7.1 surround sound exceeding the maximum available packet size on Moonlight's end (found when testing #640). When this happens with a Windows client, Moonlight will receive a `WSAEMSGSIZE` error and terminate the connection. On a Linux client, Moonlight will just read the first 1400 bytes and fail to …
> Rework audio bitrate and quality handling

- src/crypto.cpp
- src/crypto.h
Firefox doesn't like duplicate certificates with the same serial number. Additional certificates encountered will result in SEC_ERROR_REUSED_ISSUER_AND_SERIAL. We can easily avoid this by generating a unique serial number in our certificates.
Fixes #114
> Generate certificates with unique serial numbers

- CMakeLists.txt
* Remove obsolete CPACK_NSIS_DEFINES (already in default template)
* Update description for full uninstall step to clarify all user settings
will be deleted.
* Set silent default for full uninstall step to IDNO.
* Enable CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL.
* Remove CPACK_NSIS_MUI_FINISHPAGE_RUN (as service is now preferred execution
method for Windows).
The new behaviour: installer will prompt the user to first uninstall the
previous version, and the follow-up question to remove all files will NOT be
displayed (or performed). Additionally, the option to run Sunshine.exe has
been removed to avoid service conflicts.
must be updated before it can be merged. You must …
> CMake: NSIS: improve user upgrade experience

- src/main.cpp
- tools/sunshinesvc.cpp
This PR addresses several issues handling service stop, shutdown, and logoff on Windows:
- Moves Sunshine further back in the priority of processes to be terminated to keep connectivity as long as possible during logoff. This allows interaction with the screen that appears when apps are blocking shutdown.
- Adds handling for `WM_ENDSESSION` to allow Sunshine to gracefully close itself when the user session is ending. Unfortunately, we have to use the hidden window solution rather than the simpler `SetConsoleCtrlHandler()` API because the display capture APIs we use cause `gdi32.dll` to be loaded.
- Sends a Ctrl-C to gracefully terminate Sunshine when SunshineSvc is stopped or the system is shutting down. This requires a helper process because we can't attach to Sunshine's console from the …
> Graceful termination on shutdown, logoff, and service stop

- docs/source/about/usage.rst
- src/platform/common.h
- src/platform/linux/audio.cpp
- src/platform/linux/input.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/windows/input.cpp
- src/platform/windows/publish.cpp
- src/process.cpp
- src/stream.cpp
We shouldn't be aborting for non-fatal things like failing to deregister an mDNS service, failing to send input to the ViGEmBus driver, or an `undo` command returning a non-zero exit code.
This also reworks the mDNS registration code for Windows to address an issue that was causing us to consistently (at least on my machine) hit the the `std::abort()` in publish.cpp.
I also included a fix for a crash in KMS grab that I initially thought was a `std::abort()` before actually debugging it.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-chan …
> Remove/fix calls to std::abort()

- src/main.cpp
- src/process.cpp
This addresses the feedback on #647 and #648 of removing the Enter prompt on exit and changing the log level of the "Executing" messages to be consistent.
> Remove Enter prompt on exit and make log levels for execution messages consistent

- .github/workflows/CI.yml
When a PR is synchronized it will trigger another workflow run, running in parallel to the previous run. This causes issues as we easily hit our GitHub limit of simultaneous jobs. Additionally, many jobs will fail if a force push occurs as they depend on the commit still existing at specific steps.
> set concurrency limit for CI workflow

- src/platform/windows/input.cpp
This is an attempt to address the keyboard layout issues when not using a US English layout on the host.
We need testing from one of the affected users to see if this fixes the issue.
> Convert keyboard input to scancodes using the US English layout

- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
The first commit in this PR implements support for detection of DXGI format at the time `AcquireNextFrame()` is called rather than during `display::init()`. This required reworking a lot of logic around the initialization of `img_t` objects to separate format-dependent and format-independent attributes and handle creating dummy images where we don't know the capture format yet. I also did a little bit of P010 format prep work while I was in there.
The second commit is a cherry-pick of @psyke83 's IDXGIOutput5 implementation which now works properly with the dynamic capture format support implemented in the first commit.
The third commit implements support for the `display_ram_t` and `display_vram_t` backends to influence the selected capture formats. `display_vram_t` is pretty flexible …
> Dynamic capture format selection (IDXGIOutput5)

- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_vram.cpp
I think I finally figured out what's going on with the unexpected capture format changes. It looks like DWM will cheat by using a surface that is in the desktop format until a frame is returned that that has `LastPresentTime != 0` (which requires the DWM to convert the surface into the format we asked for).
Due to this behavior, #654 introduced a bug that would cause the surface format to constantly flip-flop between the requested capture format (when the desktop is updated) and the desktop format (when returning a cursor-only update). This format-switching happened constantly when requesting `DXGI_FORMAT_R10G10B10A2_UNORM` which led to very poor performance due to constantly reinitializing the capture session. This issue wasn't visible when we tested #654 because `display_vram` reported …
> Fix unexpected format switching in display_vram

- .github/workflows/CI.yml
AUR was being published on pushed to nightly, causing a quite an ugly log/history (https://aur.archlinux.org/cgit/aur.git/log/?h=sunshine). This was unintentional, with this PR the publish should only occur on merged to `master` branch.
- Fixes #678 
> fix aur publish trigger event

- src/upnp.cpp
This PR fixes the UPnP status messages and allows the detection of UPnP iuds that are in status 2 (not connected)
An IGD in status 1 is the IGD of the network and connected (has an external IP which isn't in a private block)
An IGD in status 2 is also the IGD of the network but may not be connected due to various reasons (no external IP or external IP in a private IPv4/IPv6 block)
Sunshine should not discard an IGD of status 2 as the reason to the unconnected status is not determinable by an outside source and has to be fixed by the network administrator/owner. This can be a misconfigured second router or just the ISP being down due to various reasons. 
We still do not attempt to open ports on a status 3 as this is just a UPnP device which is not an IGD.
LizardByte requires that branches …
> Fix UPnP IGD detection

- src/platform/linux/wlgrab.cpp
When using Sway on a Nvidia device, the following error occurs: https://discord.com/channels/804382334370578482/1053022079039058001
To summarize, moonlight displays a black screen after connecting and an opengl error is printed to the sunshine logs. The logs are here: https://gist.github.com/jhgarner/5627b7e48aae7f8b1d9744e3f9011f11
I can consistently reproduce and fix the issue by compiling with and without the code in this branch, but I can't explain why this code fixes it. As far as I can tell, this is just debug logging. My guess is that it's forcing the driver to actually flush parts of the command buffer? Swapping the code out with a glFinish call doesn't fix it though. Maybe Nvidia is just broken? 
LizardByte requires that branches be up-to-date before merging. This means that …
> Fix wayland capture on nvidia

- src/platform/common.h
There was an extra LFE channel in the mapping array for the 7.1 surround sound setting that was causing channels to get swapped when streaming in 7.1 mode.
> Fix 7.1 surround channel mapping

- src_assets/common/assets/web/config.html
This change fixes Vue binding for config.origin_web_ui_allowed (introduced in beb6bdfadb0c6d5aaa0c434320cd903b6e0c85cd). Without the change config value is always ignored and "Only LAN devices may access the web ui" is displayed instead.
n/a
n/a
> Fix origin_web_ui_allowed binding

- docs/source/about/advanced_usage.rst
- src_assets/common/assets/web/config.html
This PR includes some minor cosmetic fixes/improvements to the UI and docs.
- Added "AMD" to the "AMF Encoder" tab title to make it more clear to users
- Fixed some encoder tabs that were not hidden on unsupported platforms
- Fixed misspelling of QP
- Clarify that the "min_threads" option only impacts the software encoder
- Encoder configuration tabs are sorted in order of encoder priority
> Minor UI fixes

- src/stream.cpp
This is certainly not ideal, but right now you end up having to manually restart Sunshine on the host if you hit an encoder deadlock, such as the NVENC driver bug. This at least allows SunshineSvc to recover automatically by restarting Sunshine after the client disconnects.
> Terminate Sunshine if a session doesn't terminate for more than 10 seconds

- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/wlgrab.cpp
- src/platform/linux/x11grab.cpp
- src/platform/macos/display.mm
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
- src/video.cpp
While testing with #707, I discovered an issue that was causing stream termination hangs that would prevent a client from reconnecting (or with #707, cause Sunshine to terminate itself). The issue is that the only time `display_t::capture()` will return to the capture thread or invoke the callback is when a frame is successfully captured or an error or reinit occurs. If it's just a normal timeout, the capture function will loop forever trying to capture a frame.
To fix this, I added a parameter to the `snapshot_cb` callback that indicates whether a frame was captured or if this is a callback invocation caused by a timeout. Now that `snapshot_cb` is being invoked for timeouts, it can check if capture should stop and return `nullptr` to indicate that.
LizardByte requires that branches be …
> Fix hang on stream termination if no frames can be captured

- src/video.cpp
Rework encoder selection logic to avoid terminating Sunshine if the preferred encoder is not available or doesn't meet the HDR requirement selected. This ensures it's not possible to accidentally set an encoder that's not supported on your system and prevent Sunshine from starting again without manual config file modification.
The old logic was:
1. If a specific encoder is requested, use that encoder. If that encoder doesn't pass validation or doesn't support HDR when requested, fail to start.
2. If an encoder with HDR support is requested and passes validation, use that encoder. If no encoder with HDR support is available, fail to start.
3. If no specific encoder was requested and HDR encoding was not required, use the first working encoder.
4. Else, fail to start.
The new logic is:
1. …
> Improve robustness of encoder selection

- src/confighttp.cpp
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.cpp
- src/platform/windows/misc.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/troubleshooting.html
This PR adds an "Apply" button to the web UI on systems where Sunshine is running as a service. When clicked, it saves the settings and sends a SIGINT to itself to gracefully terminate. SunshineSvc will then restart it, which will load the new settings.
The "Apply" button only appears on Windows systems where Sunshine is running as a service, but the scaffolding is there to support this on Linux and Mac too (probably by just execing ourselves again).
@TheElixZammuto should probably review the config.html changes for correctness. I'm definitely no web development expert.
Save button success text (when Apply button is available):
Apply button success text:
must be updated …
> Add an Apply button to the Web UI when running as a Win32 Service

- CMakeLists.txt
- docs/source/about/advanced_usage.rst
- src/platform/windows/misc.cpp
- src_assets/linux/assets/apps.json
- src_assets/macos/assets/apps.json
- src_assets/windows/assets/apps.json
- src_assets/windows/misc/migration/migrate-config.bat
This moves config and other data files out of the root of our Program Files directory into a specific `config` directory. Only that new config directory has RW access for the Users group now.
I've tested this locally, but it would be nice for someone else to grab the installer from the CI job to make sure it all works seamlessly for them too.
> Migrate Windows config files into specific config directory

- src/platform/windows/display.h
- src/platform/windows/display_vram.cpp
- src/utility.h
Blending of masked color and monochrome cursors was broken when using GPU accelerated encoding on Windows. Color masked cursors would be rendered completely transparently (no cursor at all) and monochrome masked cursors would not be blended with the display contents at all (using fixed colors instead).
This fixes the I-beam cursor when using High DPI (which is a masked color cursor) and the inverted cursor style (which uses monochrome cursors with inversion masks).
Fixes #513
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pu …
> Fix Windows masked cursor blending with GPU encoders

- src/platform/windows/misc.cpp
This PR introduces a workaround for the issue where Windows systems with no physical mouse connected would not display the mouse cursor (OS behavior since Windows 8). As a workaround, we can enable Mouse Keys for the duration of the streaming session which will force the mouse cursor to be displayed. Fortunately for us, Mouse Keys doesn't see input from `SendInput()` so we don't have to do anything special to make the number pad work either.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fo …
> Enable Mouse Keys while streaming for systems with no mouse plugged in

- src/platform/linux/cuda.cu
- src/platform/linux/graphics.cpp
- src/platform/windows/display_vram.cpp
- src/video.cpp
- src/video.h
- src_assets/linux/assets/shaders/opengl/ConvertUV.frag
- src_assets/windows/assets/shaders/directx/ConvertUVPS.hlsl
- src_assets/windows/assets/shaders/directx/ConvertYPS.hlsl
This fixes color conversion errors with both limited and full range content and introduces BT.2020 support.
Host and client titlebars perfectly blend together now when using the same accent color:
Fixes #300
> Color conversion fixes and BT.2020 support

- src/video.cpp
One final fix for the color conversion code. The divisor for the color ranges should be 255 because 1.0f corresponds to 255 not 256.
Winver dialog gray is a perfect match now:
The pink titlebar is within rounding error:
Conhost background is perfect:
Fixes #300 
> Fix divisor for YUV range

- .gitmodules
This should fix issues with initializing submodules. I have been unable to initialize submodules at all until I made this change.
Todo:
Resolves this error
```txt
$ git submodule sync; git submodule update --recursive
Synchronizing submodule url for 'third-party/Simple-Web-Server'
Synchronizing submodule url for 'third-party/TPCircularBuffer'
Synchronizing submodule url for 'third-party/ViGEmClient'
Synchronizing submodule url for 'third-party/ffmpeg-linux-aarch64'
Synchronizing submodule url for 'third-party/ffmpeg-linux-x86_64'
Synchronizing submodule url for 'third-party/ffmpeg-macos-aarch64'
Synchronizing submodule url for 'third-party/ffmpeg-macos-x86_64'
Synchronizing submodule url for 'third-party/ffmpeg-windows-x86_64'
Synchronizing submodule url for 'third-party/miniupnp' …
```
> fix submodule names

- CMakeLists.txt
* Disable boost-cmake detection, as current cmake files in mingw reference non-existent libraries (icudata, icui18n)
* Remove WinAPI workaround (Boost is now built against latest mingw headers)
> CMake: win32: fix API version, disable boost-cmake detection

- .github/workflows/CI.yml
Revert (#669) locking the libpsl version on Windows builds.
> revert windows build libpsl version lock

- .github/workflows/CI.yml
- CMakeLists.txt
- docs/source/building/windows.rst
Adds libmfx as a windows dependency to support qsv-enabled ffmpeg builds
> FFmpeg updates with QSV-enabled builds

- src/upnp.cpp
This PR moves the check for the UPnP enable flag up to the top of the `start` function.
This way if someone disables UPnP it is truly disabled and does not try to find any UPnP device to begin with.
(No issue was made for this)
> Move the check for UPnP enabled up to avoid error messages

- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/vaapi.cpp
- src/platform/macos/nv12_zero_device.cpp
- src/platform/macos/nv12_zero_device.h
- src/platform/windows/display_vram.cpp
- src/video.cpp
This is some plumbing work required for QuickSync. During the QuickSync work, I discovered a reference leak caused by `av_hwframe_get_buffer()` clobbering the reference that we already stored there in `frame->hw_frames_ctx`. To avoid this, we need to pass the `hw_frames_ctx` pointer into `set_frame()` rather than set it in the frame itself.
Since QuickSync will need a fixed size frame pool, I changed `display_vram_t` to use `av_hwframe_get_buffer()` rather than allocating a texture itself.
No behavior changes expected (other than fixing the reference leak with CUDA and VAAPI on Linux). …
> Fix a reference leak of hw_frames_ctx and prepare for QSV

- CMakeLists.txt
mingw's openssl library is built using the "zlib-dynamic" flag, which invokes LoadLibrary() of zlib1.dll during runtime to allow openssl to function if no zlib.dll is installed.
This is a problem because it prevents static linkage of zlib, thus opening a security vulnerability by which a malicious zlib1.dll can be loaded from any valid system dll search path.
Increase security by including the mingw version of zlib1.dll in the application path, which will override any other versions.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes …
> CMake: Windows: harden install by including zlib1.dll

- .gitmodules
- CMakeLists.txt
- src/stream.cpp
This PR switches from the Reed-Solomon implementation in moonlight-common-c to a faster one in https://github.com/sleepybishop/nanors
Right now I'm just building with the default `autoshim.h` flags which means SSSE3 for x86_64 and NEON for aarch64 (since nanors doesn't support runtime CPU feature detection), but that's still good enough for huge performance improvement over the old code.
Profile with old RS implementation:
Profile with new RS implementation (sample counts will vary, so just look at the relative values vs WSASendTo):
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with …
> Switch to faster nanors Reed-Solomon implementation

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/platform/common.h
- src/platform/windows/display_vram.cpp
- src/video.cpp
- src_assets/common/assets/web/config.html
This PR introduces Intel QuickSync support for Windows. We initially create a D3D11VA hwdevice then use that to derive a QSV context which wraps the underlying D3D11 texture pool. We map the QSV surfaces back to D3D11 textures to draw into them (handled in #736).
The QSV encoder was a little more finicky than AMF and NVENC, so more quirk flags were required to get it to behave (respecting the max frame size, but without lowering the RC buffer too much which caused the HEVC encoder to fail completely on large frames).
This does not address hybrid graphics (Optimus) scenarios. I will put up a second PR for that.
Resolves #698 
Resolves #438
must be updated before it can be …
> Intel QuickSync support for Windows

- src/platform/windows/display_vram.cpp
The implementation of `display_vram_t::convert()` was using a pre-allocated black ARGB dummy image to fill the entire image every frame. This effectively means we're doing 2x the amount of work in `convert()` than we should be, because we end up doing RGB->YUV on the dummy image, then doing RGB->YUV on the actual image data to draw right on top of the black image we just drew.
The result is a bunch of extra draw calls, state changes, mutex acquisition, etc. for every frame. We can replace all this work with a couple of `ClearRenderTargetView()` calls when we initially create the image. …
> Avoid redundant padding fills in display_vram_t::convert()

- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.cpp
- src/platform/windows/misc.cpp
- src/rtsp.cpp
- src/stream.cpp
- src/stream.h
This PR implements a series of network performance optimizations for Windows and Linux.
a0658d094008b461ffaf28ac2002a07197602137 adds support for send batching on Windows and Linux via a new `platf::send_batch()` function. This uses UDP segmentation offload to handle the splitting of our video frames into identically sized packets. For NICs that support it, this can even be offloaded to the NIC itself rather than requiring the OS to perform the packet splitting on the CPU. Even for NICs without hardware segmentation offload support, it significantly cuts down on the number of syscalls per frame by an order of magnitude (or two).
054140aa26b3715b67500b228c01407b42790ffd implements support for QoS tagging our video and audio streams on Windows using the qWAVE API. This will set a DSCP tag …
> Network performance optimizations

- src/platform/linux/wlgrab.cpp
This PR just fixes the compiler warning "multi-character character constant". It is mostly just to test that I know how to make PRs in case I have more useful PRs in future.
n/a
n/a
> Fix multi-character character constant compiler warning

- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
This PR replaces the busy loop we were previously using to time frames on Windows with an implementation based on waitable timers, which can provide sub-millisecond wait precision (unlike regular `Sleep()`).
The previous busy loop would increase CPU usage on the capture thread proportional to the difference between the actual capture frame rate and the Moonlight client's selected frame rate. It could end up consuming a significant amount of CPU time which could impact system responsiveness and game performance, especially in CPU-bound scenarios (since the capture thread runs at a high priority). Ironically, attempts by users to reduce load on the system by streaming at a lower frame rate would have actually made the performance problem worse.
LizardByte requires that branches be …
> Replace frame capture busy loop with waitable timer

- CMakeLists.txt
- src/platform/windows/display_base.cpp
- tools/CMakeLists.txt
- tools/ddprobe.cpp
This PR implements a new tool `ddprobe.exe` which Sunshine invokes to perform detection of which GPU preference value is required to get working Desktop Duplication. The GPU preference gets locked in at the moment the first DXGI factory is constructed and cannot be changed for the lifetime of the process, so we must use a sacrificial process to perform the probing rather than doing it inside Sunshine itself.
This approach seems to work both with official NVIDIA Optimus laptops (including with conflicting overrides in the NVIDIA Control Panel) and with "regular" multi-GPU systems like desktop PCs with both an iGPU and a dGPU enabled.
Fixes #737 
must be updated before it can …
> Add support for hybrid graphics systems (NVIDIA Optimus)

- src/platform/windows/display.h
- src/platform/windows/display_vram.cpp
#668 broke the multi-client streaming scenario because it assumes a single `img_t` is shared between a single capture device and a single encoding device. When using multiple clients, there is a new `hwdevice_t` for each independent stream, so there can be an arbitrary number of encoding devices sharing a single capture texture. This PR fixes this issue by keeping a map of encoder image context structures in the `hwdevice_t`, so each separate encoding device can open the same capture texture and mutex properly.
Fixes #795
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-reque …
> Fix streaming to multiple clients from hardware encoder on Windows

- CMakeLists.txt
CMake doesn't define a default `CMAKE_BUILD_TYPE`, so you end up with a build with no optimizations or debug info. We had worked around this issue by hardcoding optimization flags for Debug and non-Debug build types, but this was a hack and only worked for C++ and CUDA source (not C code, like `rs.c`). Fix this by defaulting `CMAKE_BUILD_TYPE` to `Release` if no build type is specified.
> CMake: Default to Release build and stop hardcoding optimization flags

- src/platform/windows/display_base.cpp
- tools/ddprobe.cpp
This PR fixes a few bugs in our handling of hybrid graphics systems that I found while testing on a variety of machines and scenarios.
- Changed ddprobe.exe to return the raw error code rather than just 1 or 0. This change improves debuggability because we can write the actual DXGI errors into our logs rather than just a pass/fail.
- Fixed GPU detection behavior after RDPing into the machine. `DuplicateOutput()` returns `E_ACCESSDENIED` in this scenario, but that is fine to tell us whether DD API is supported or not.
- Added a DD API test inside Sunshine itself to determine if an output is supported for capture. In cases with multiple GPUs connected to monitors, we could try to select a monitor that is on another GPU and fail to capture it.
- Don't reset the GPU preference if ddprobe.exe …
> Improve reliability of hybrid graphics detection

- src/input.cpp
- src/nvhttp.cpp
- src/platform/common.h
- src/platform/linux/input.cpp
- src/platform/macos/input.cpp
- src/platform/windows/input.cpp
- src/stream.cpp
This PR implements a protocol extension for horizontal scroll events and an `appversion` change to allow Moonlight to distinguish Sunshine hosts in moonlight-common-c. Using a negative number for the 4th part of `appversion` should be safe for existing Moonlight clients while also ensuring that any past or future version of GFE will not collide.
I've also added protocol extension for sending keyboard events with non-normalized key codes and HDR metadata, but neither of those are implemented in Sunshine yet.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-wit …
> Implement horizontal scrolling and Sunshine detection for Moonlight

- .github/workflows/ci-docker.yml
- docker/debian-bullseye.dockerfile
- docker/fedora-36.dockerfile
- docker/fedora-37.dockerfile
- docker/ubuntu-18.04.dockerfile-todo
- docker/ubuntu-20.04.dockerfile
- docker/ubuntu-22.04.dockerfile
Docker build will now depend on the event type. There is a problem with slow builds when building the Fedora images for arm64 architecture. Only amd64 images are built now on PR events.
Additionally, the dockerfile syntax has been added to each dockerfile.
> docker build dependent on event type

- src/main.h
- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/misc.cpp
- src/platform/linux/wlgrab.cpp
- src/platform/linux/x11grab.cpp
- src/platform/macos/display.mm
- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
- src/stream.cpp
- src/video.cpp
- src/video.h
This PR contains some miscellaneous prep work for HDR support. The main changes are:
- Plumbing the `video::config_t` into the display implementations to allow them to tell HDR and SDR streams apart
- Call `IDXGIFactory1::IsCurrent()` each frame to tell if there has been a GPU or display change. Microsoft recommends this method of detection. It is required to accurately detect HDR transitions.
- Implement `display_t` functions to return HDR state and HDR metadata
- Configure the encoder for SMPTE ST 2084 PQ and Rec 2020 when in HDR mode
- Send the HDR mode message to Moonlight when HDR state changes
Note: This is only prep work. HDR will not work properly with these changes alone.
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this …
> HDR prep work

- DOCKER_README.md
Updates docker readme with new tag information.
> update docker tag information

- src_assets/linux/assets/apps.json
- src_assets/macos/assets/apps.json
- src_assets/windows/assets/apps.json
Rename 'Steam BigPicture' to 'Steam Big Picture' in apps.json, as Steam refers to it as either 'Big Picture' or 'Big Picture Mode'.
> Rename 'Steam BigPicture' to 'Steam Big Picture' in apps.json

- src/confighttp.cpp
Reported by DemonCat on Discord. The basic auth header is printed when loglevel is Debug, which could be an issue when a user submits their logs.
> Scrub basic auth header from logs

- docs/source/about/usage.rst
- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_vram.cpp
- src/stream.cpp
- src/video.cpp
- src_assets/windows/assets/shaders/directx/ConvertUVPS_PQ.hlsl
- src_assets/windows/assets/shaders/directx/ConvertYPS_PQ.hlsl
- src_assets/windows/assets/shaders/directx/ScenePS_NW.hlsl
The title pretty much says it all. This adds support for streaming HDR content from a Windows host.
I've tested this successfully with NVIDIA (RTX 2080), AMD (RX 6700 XT), and Intel (12600K IGP) GPUs. AMD and NVIDIA  encoders had no trouble encoding HEVC Main 10 in HDR at 4K 60 FPS, but Intel QuickSync seemed to struggle with HEVC Main 10 with notably degraded image quality compared to HEVC Main profile (this impacted both SDR and HDR modes).
I'd attach one but I can't find a screenshot utility that handles HDR content properly
Resolves #376
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collabora …
> Implement HDR support for Windows

- docs/source/about/usage.rst
- sunshine.service.in
Make the systemd service restart itself in case of a crash. A restart is attempted 5 seconds after a crash is detected. Additionally, if the service is restarted more than 5 times in a 500 second interval it is considered as failed and no more restart attempts are going to be made.
Sunshine crashed when I attempted to connect to a desktop session.
Not sure what the actual crash was. Nothing suspicious in the output logs.
Maybe systemd keeps the core dumps somewhere. I will open a new ticket if I find out more about the issue.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-r …
> Restart the systemd service in case of a crash

- src/video.cpp
When a reinit caused by a capture size change occurs via the Windows hardware encoder, the stream will freeze with `display_wp->use_count()` stuck at 2. Fix by ensuring pending images are freed before reinit event is checked.
To reproduce:
* Using an application that allows full-screen transition via alt-enter, continually enter and exit fullscreen whilst the application is configured to use a different resolution from the desktop. In my case, I used Sonic Mania @ 1360x768 with a desktop resolution of 1440p, and the freeze usually occurs within 10 successive resolution changes.
* Disabling DwmFlush appears to help reproduce the issue more quickly.
The freeze will occur when this line appears in the log:
```
[2023:01:24:02:01:26]: Info: Capture size changed [1360x768 -> 2560x1440]
``` …
> Fix image leak of hardware parallel encoder on display reinit

- CMakeLists.txt
This PR contains some miscellaneous installer improvements for Windows:
- Fixes silent mode to be truly silent (no dialogs or browser windows)
- Switches to `nsExec::ExecToLog` for terminal commands and `ExecShell` to avoid spawning focus-stealing command prompt windows
- Adjusted wording in ViGEmBus dialog to make it even more clear that this is required for gamepad support
- Changes the name of the installed Sunshine shortcut to try to reduce confusion when running as a background service
Fixes #790
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-fork …
> Windows installer fixes

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
Rename libmfx-dev to intel-mediasdk to maintain name consistency with source. Make libdrm a submodule of intel-mediasdk. Also cache numactl by building it before CUDA where our caching stops.
> Flatpak build improvements

- src/video.cpp
This fixes some issues with capture initialization/reinitialization that could cause us to discard good frames. When we reinitialize encoding, the encoder thread will free any pending frames and encode an initial dummy frame. This could result in the first captured frame from the newly reinitialized display being dropped or immediately superseded by a dummy frame.
@psyke83 Please give this a try to ensure it doesn't regress #823. It should also fix the black screen issue when starting a stream or triggering a UAC prompt when no new frames are being generated. …
> Display initialization and frame ownership fixes

- CHANGELOG.md
- CMakeLists.txt
- docs/source/gamestream/gamestream.rst
- Update changelog for v0.18.0
- Update version number to v0.18.0
> docs: update changelog for v0.18.0

- CHANGELOG.md
The changelog parser does not like single quotes inside of double quotes, so replacing double quotes with backticks.
I have tested this locally in ACT and believe it resolves the issue.
> changelog: fix parsing issue with single quotes

- CMakeLists.txt
Fix arm64 breakage caused by #864
> CMake: CPack: set Intel MediaSDK as arch-specfic depend

- src/platform/linux/kmsgrab.cpp
- src/platform/linux/wlgrab.cpp
Following #649, I added the same code for `kmsgrub` which from my testing works pretty well
- Fixes #838 
> Fix wayland capture on nvidia for kms

- src/platform/linux/vaapi.cpp
Implement `vaSyncBuffer()` stub for libva <2.9.0, which allows Ubuntu 20.04 builds of Sunshine to be linked against ffmpeg built against libva 2.9.0 or later.
The `vaSyncBuffer()` function is needed for the `async_depth` VAAPI encoder parameter to work correctly, which can reduce latency if GPU drivers support the interface.
> Linux/VAAPI: implement vaSyncBuffer stub for libva <2.9.0

- src/confighttp.cpp
- src/confighttp.h
Add a map of mime types and apply the proper header based on the file extension.
- Fixes #885 
> web: api: add mimes type map

- CMakeLists.txt
CMake: CPack: use correct Boost dependency versions
Fixes #916
> CMake: CPack: use correct Boost dependency versions

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/video.cpp
- src_assets/common/assets/web/config.html
Adds the following tunables:
* usage profiles (default: ultralowlatency)
* preanalysis (default: false)
* vbaq (default: true)
> AMF: add missing encoder tunables

- CHANGELOG.md
- CMakeLists.txt
> changelog: v0.18.2

- .github/workflows/CI.yml
macOS build seems to be failing due to missing `pkg-config`, so adding that using homebrew.
> build(deps): add pkg-config for macOS build

- src/platform/windows/input.cpp
When installed as a service, scancode mapping for non-US keyboards will not work correctly on first boot if the user's Windows installation does not have the English (US) language & keyboard installed as a fallback, and/or the installation is configured to automatically log in.
On first boot, Sunshine does not translate the international keys correctly, and modifier keys such as ctrl/alt/shift will appear stuck after first press (which can be visually confirmed via the On-Screen Keyboard application). Restarting Sunshine after the desktop session has loaded fixes mapping on subsequent connections, indicating that the US locale is loaded but isn't activated correctly in Sunshine when the desktop session is not yet loaded.
This can be fixed by invoking `ActivateKeyboardLayout()` (scoped to …
> windows: input: activate US keyboard layout for scancode mapping

- docs/source/about/advanced_usage.rst
- docs/source/about/app_examples.rst
- docs/source/about/usage.rst
- docs/source/toc.rst
- src_assets/common/assets/web/config.html
Improvements to app examples and virtual sink.
> docs: improve examples

- src/config.cpp
- src/config.h
- src/input.cpp
- src_assets/common/assets/web/config.html
This PR adds three new settings that allow suppressing client input from the mouse, keyboard, and gamepads, one for each type of input. They can be toggled individually, allowing any combination of allowable input the user desires. This also allows for disabling client input entirely, putting Sunshine in a "view only" mode.
All settings are disabled by default, meaning there's no change in default behavior.
This feature was suggested here: https://github.com/LizardByte/Sunshine/discussions/822
N/A
Notes: code additions are very simple and I consider them sufficiently self explanatory to not require any comments.
I have not added any new methods or components.
must be updated …
> Add setting for suppressing input from mouse, keyboard, or gamepads

- .github/workflows/CI.yml
- CMakeLists.txt
- docker/debian-bullseye.dockerfile
- docker/ubuntu-20.04.dockerfile
- docker/ubuntu-22.04.dockerfile
- docs/source/building/linux.rst
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- src/platform/linux/input.cpp
This PR adds Unicode support for remote pasting in Linux using [Unicode input mode](https://en.wikipedia.org/wiki/Unicode_input).  
I've read around and this might not be supported on all combinations of DE, for example see: [kde#103788](https://bugs.kde.org/show_bug.cgi?id=103788) it works fine on my machine but maybe some Linux wizard can find a better solution.
I've introduced another Boost dependency: [Boost.locale](https://www.boost.org/doc/libs/1_81_0/libs/locale/doc/html/index.html) I've added it as a dependency where I could find it, but feel free to modify the PR if I've missed some.
Fixes #760 …
> feat: implemented unicode input mode

- src/platform/linux/wayland.cpp
- src/platform/linux/wayland.h
This fixes issues in the wayland code when compiling using clang caused by some C callbacks. See #549 for exact errors - specifically, the cast errors.
Fixes #549
> Fix linux clang build errors

- docker/archlinux.dockerfile
Disable download timeout for archlinux dockerfile build to solve the below error which occurs randomly.
```txt
Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```
> archlinux: disable downlaod timeout

- docs/Doxyfile
- src/nvhttp.cpp
- src/nvhttp.h
Client verified messages fill the log really quickly whenever a client is viewing the app list, so moving these to debug logging.
> logging: change client verified messages to debug

- CMakeLists.txt
- src/platform/macos/av_audio.m
- src/platform/macos/misc.mm
These changes broaden the macOS versions that Sunshine can be compiled for. There are only a few places in the codebase where a macOS API function that requires macOS 10.15 or later is used, and this PR makes it so that these functions are weakly linked and avoids using them when running in macOS 10.14 and earlier.
The other issue with compiling on macOS 10.14 is that its version of libc++ doesn't support some of the later C++ features used throughout the codebase. However, this can be overcome by compiling with a newer installation of LLVM / clang and statically linking against its copy of libc++.
With the changes in this PR, I was able to get Sunshine to compile for macOS 10.12-10.14 by installing clang 15 using MacPorts (along with Sunshine's other dependencies) and then configuring it …
> Support compiling for earlier releases of macOS

- src/platform/linux/kmsgrab.cpp
What the title says, before it segfaulted when `/dev/dri` doesn't exist
> Fix startup when /dev/dri doesn't exist

- src_assets/common/assets/web/config.html
Only save non default config values.
Also fixes a potential issue where new FPS values were quoted, as discovered when reviewing #1002.
> config: only save non default values

- sunshine.service.in
This fixes an issue where sunshine could randomly start before the window manager on wayland, causing the wm to error with Device or resource busy on the kms/dri device. This would prevent the desktop from running at all, and all you would see is a black screen. This seems to happen on both gnome and plasma when using wayland (I've only tested it on plasma).
The fix is simply to have the sunshine systemd service start after xdg-desktop-autostart.target, which happens when other autostart apps run, and that's always after the window manager is ready.
Fixes #334 …
> Use xdg-desktop-autostart.target for systemd service.

- .github/workflows/ci-qodana.yml
- .github/workflows/dispatcher.yml
Use workflow dispatch for qodana workflows. This should solve an issue where PRs from forks could not fully run qodana ci.
> qodana: use workflow dispatch

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/platform/linux/misc.cpp
- src_assets/common/assets/web/config.html
In Linux sunshine will test nvfbc, kms, wayland and x11 capture methods and will choose the first one that works in that order. This change allows you to force a specific one as long as it is available. If no capture method is found or if you select one that cannot be initialized, then an error message will be raised. 
Documentation update to follow.
> Provide ability to force a capture method via configuration.

- src/process.cpp
- src/round_robin.h
The CMakeLists specifies the C++17 standard and some elements used by sunshine are deprecated. This change cleans up those warnings while preserving the same functionality.
> Fix compiler warnings due to deprecated elements in C++17

- src_assets/common/assets/web/index.html
This pull request fixes a bug in the code that prevents the version update from working properly for nightly builds. The changes made in this pull request ensure that the expected behavior is met, which is to suggest a new nightly release when available, and only suggest a stable release if it has a higher version number than the nightly release.
Changes Made:
Updated the hasNewStable method to check nightly builds by comparing the latest nightly version tag with the stable version, and only returning true if the latest stable version is higher than their current nightly version. If the user does not have a nightly version of Sunshine, the existing functionality of the method remains the same.
Fixed a bug in the hasNewNightly method by using pop() instead of indexing by -1. JavaScript …
> Nightly Notification Bug Fixes

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/confighttp.cpp
- src/process.cpp
- src/process.h
- src_assets/common/assets/web/apps.html
- src_assets/common/assets/web/config.html
Add the ability to add a global set of Prep Commands that will run for _all_ applications. Global prep configuration is accessible in the UI through new tab on Applications page. Users can also enabled/disabled execution of global commands on a per applications basis. Default is Enabled.
Global Command Preparations on Configuration -> General page
Per-App Toggle of global prep command execution
NA
> Add support for global prep commands

- src_assets/common/assets/web/index.html
Fixes alerts when running a dirty (locally modified) version of Sunshine.
> versioning: fix dirty commit notifications

- src/config.cpp
Fixes an issue introduced by #977 when the `global_prep_cmd` config option was not set in the config file.
> commands: fix prep commands when empty

- CMakeLists.txt
Stumbled upon this when setting up sunshine in vscode, where I was getting strange linker errors.
In `CMakeLists.txt` both `CURL_STATIC_LDFLAGS` and `CURL_STATIC_CFLAGS` are lists, when converted to string their items get semicolon-separated. `CMAKE_CXX_FLAGS` is a string, where flags are space-separated.
What basically happened, `CURL_STATIC_LDFLAGS` was always converted to single gibberish `-L` argument which just didn't trigger any errors. And `CURL_STATIC_CFLAGS` was properly converted *only* when the list had a single item (`pkg-config --static --cflags libcurl` returned only `-DCURL_STATICLIB`. When `pkg-config` gets called outside of msys environment, it prepends include directory with `-I` argument , and `CURL_STATIC_CFLAGS` breaks exactly like `CURL_STATIC_LDFLAGS`. To the …
> Properly handle libcurl flags in CMakeLists.txt on Windows

- src/platform/linux/misc.cpp
This was accidentally broken in c6548f4.
n/a
> Fix X11 fallback during init

- docs/source/about/advanced_usage.rst
- src/platform/linux/x11grab.cpp
- src_assets/common/assets/web/config.html
This change lets me use HDMI-0 (with HDMI dummy plugged in) as a Sunshine exclusive output when using the following do/undo commands:
* xrandr --output HDMI-0 --mode 1920x1080 --right-of DP-0
* xrandr --output HDMI-0 --off
n/a
n/a
> Don't skip disconnected X11 outputs

- src/main.cpp
Instead of exiting when one of the major components fails to initialise, this change will log errors and continue. The advantage of this is that even though sunshine will not work, the web UI will still be available to view the logs and fix configuration.
> Continue in the face of failure

- src/system_tray.cpp
In Linux, the action to Open Sunshine in the system tray did not work. The action calls "open URL", but really it should be "xdg-open URL".
> Fix system tray Open Sunshine

- CHANGELOG.md
- CMakeLists.txt
- src_assets/windows/misc/vigembus/install-vigembus.bat
- src_assets/windows/misc/vigembus/uninstall-vigembus.bat
Auto install/uninstall ViGEmBus for Windows installer.
Additionally, fixes elevator component in Windows installer.
> installer: auto install vigembus

- src/main.cpp
Fixes broken audio introduced in 0.19.0
Fixes #1102
> Hotfix - keep platform guard in scope

- .github/workflows/CI.yml
Fixes issue with release versions, where commit hash would be present in the version number. This made the UI believe it was a nightly version.
- Partially Fixes #1103 
> versioning: fix release versions

- src/thread_safe.h
Compilation fails on `Clang 14.0.0 x86_64-apple-darwin21.6.0` from `Xcode 14.2` with the following message:
```
[build] /Users/user/Documents/Sunshine/src/thread_safe.h:450:52: error: implicit instantiation of undefined template 'std::array<unsigned char, 128>'
[build]     std::array<std::uint8_t, sizeof(element_type)> _object_buf;
```
Including the missing header fixes the problem.
> Fix compilation on macOS

- src/platform/windows/input.cpp
It is currently not possible to register a "BACK" action (Select / Share button press) when Sunshine is configured to emulate a DS4 controller on Windows.
This seems to be due to the BACK action being triggered by the touchpad button press instead.
When testing I was not able to register a BACK action using the touchpad, since as soon as the touchpad is pressed it is treated as a mouse input instead.
This PR is a simple fix for the "BACK" functionality on DS4 controller emulation when using a DS4 or DualSense controller, which maps it to the Share button, and unmaps the non-functional touchpad press.
(It is up to interpretation whether this is a breaking change, as it unmaps the touchpad press despite the touchpad press seemingly being incorrectly registered.)
N/A
- Fixes #799
- Most …
> Use Share button on DS4 controllers (ViGEm DS4_BUTTON_SHARE) as BACK action

- src/platform/windows/display_vram.cpp
Follow-up to https://github.com/LizardByte/Sunshine/pull/1098, split up because that pull request is big enough already.
After we start dynamically adjusting capture buffer size, this operation is not free anymore.
> Don't zero-initialize non-dummy textures

- src/platform/windows/display_vram.cpp
This `Flush()` call was introduced by Loki back in 7aff15f7430310a58a9272c03f5e2fd28ec7281a when adding the extra draw calls for the aspect-ratio padding. Since we no longer use that approach for aspect-ratio padding, we can nuke the flush too. Unnecessary flushes can have a perf cost (though the cost of this one seems very minimal in my testing).
> Remove useless Flush() call

- CMakeLists.txt
Enables the DPI scaling on the Windows Installer, so that text does not appear blurry or have jagged edges for users who install Sunshine on high resolution screens.
> Enable DPI Scaling on Windows Installer

- src/input.cpp
- src/platform/common.h
- src/platform/linux/input.cpp
- src/platform/macos/input.cpp
- src/platform/windows/input.cpp
This PR fixes 2 keyboard bugs that impact the mobile Moonlight clients.
- Android and iOS key input, especially from the software keyboard, cannot always be normalized to the US English layout that we use for scancode conversion. In that case, the latest iOS and Android clients will pass `SS_KBE_FLAG_NON_NORMALIZED` to tell the host that these are from an unknown layout. When we receive a non-normalized key event, we will not perform scan code conversion and instead just send the VK value unchanged. This fixes input from non-US keyboard layouts on iOS and Android.
- The Android software keyboard has peculiar behavior for modifiers. It will send a key up+down combo for the Shift key when Shift is toggled on/off, but then uses the modifier flags on each subsequent event to indicate whether …
> Fixes for keyboard issues with mobile Moonlight clients

- src/config.cpp
- src/confighttp.cpp
Running on macOS without `~/.config` folder got me this
```
user@macos build % ./sunshine
libc++abi: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::create_directory: No such file or directory [system:2]: "/Users/user/.config/sunshine"
zsh: abort      ./sunshine
```
Should be very straightforward fix, switch to recursive variant of boost function
https://www.boost.org/doc/libs/1_66_0/libs/filesystem/doc/reference.html#create_directories
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-cha …
> Create config directories recursively

- CMakeLists.txt
Prior to https://github.com/LizardByte/Sunshine/pull/997 it appears that full X11 libraries were only needed as part of `FFMPEG_PLATFORM_LIBRARIES` -- however, after this change, they are also needed outside the context of FFmpeg. This PR adds them to `PLATFORM_LIBRARIES` when found to satisfy this requirement.
Believe this is not an issue currently because the requirement is handled by `FFMPEG_PLATFORM_LIBRARIES` -- however it manifests as part of the [nixpkgs packaging of Sunshine](https://github.com/NixOS/nixpkgs/pull/224152) as we use FFmpeg from nixpkgs rather than the prebuilt version. …
> add X11 to PLATFORM_LIBARIES when found

- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
- src_assets/windows/assets/shaders/directx/ConvertUVPS_Linear.hlsl
- src_assets/windows/assets/shaders/directx/ConvertYPS_Linear.hlsl
Since the introduction of HDR, we were not properly handling the case where the client had requested HDR but the server had an Advanced Color SDR display. In that particular case, we would get frames in linear gamma but treat them as if they were sRGB. I believe this was actually noticed in #1032, but I didn't make the connection to this bug at the time.
When #1137 started allowing FP16 formats for SDR clients too, it became much more noticable since it impacted all streams from hosts with Advanced Color SDR displays.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/ …
> Fix color conversion for Advanced Color SDR displays

- src/platform/windows/display.h
- src/platform/windows/display_vram.cpp
Optimize fullscreen game capture path with copy evasion and save one frame of vram. Currently in draft, it works well, but lacks documentation and instant `std::variant` should be replaced with delayed surface destruction.
> Don't copy to intermediate surface when there is no mouse cursor

- src/nvhttp.cpp
- src/platform/linux/vaapi.cpp
- src/rtsp.cpp
- src/video.cpp
- src/video.h
The first commit changes the logic of setting the number of reference frames such that it will always succeed with any FFmpeg encoder. This eliminates the need for probing `REF_FRAMES_AUTOSELECT` in all cases, allowing us to short-circuit that in the next commit. AMD's encoder in particular uses `-1` as the default value for `ctx->refs`, so we were likely forcing 16 reference frames there before on clients that didn't explicitly request 1 reference frame (wasting memory).
The second commit adjusts `validate_encoder()` to eliminate the need for several encoder probes. Probing for `SLICE` is removed in favor of using the existing `SINGLE_SLICE_ONLY` encoder flag, because it appears to not be required for any encoders other than VAAPI. The common case probe count is down from 8 codec opens …
> Improve speed of encoder probing

- src/main.cpp
- src/main.h
- src/platform/windows/misc.cpp
- src/system_tray.cpp
- tools/sunshinesvc.cpp
This fixes a couple systray bugs when running Sunshine as a service.
- The first commit fixes Explorer's termination detection to ensure the tray icon will disappear when Sunshine terminates unexpectedly. Explorer will try to open a thread handle and delete the tray icon when it is signalled. That fails when running as System because there's no `LogonSessionId` principal in the DACL that would ordinarily grant `SYNCHRONIZE` access to other processes in the same session. To avoid this, we add an ACE to our systray thread that allows `SYNCHRONIZE` access for everyone.
- The second commit makes the Quit option in the systray menu stop the service to avoid automatically respawning Sunshine after quitting.
Fixes #1170
LizardByte requires that branches be up-to-date before merging. This means …
> Fix system tray bugs when running as a service

- docker/fedora-37.dockerfile
bump git from 2.39.2 to 2.40.0 for fedora 37
> build(deps): bump git from 2.39.2 to 2.40.0 for fedora 37

- src/confighttp.cpp
Add "Content-Type" response headers to web ui pages which prevented some browsers from rendering Sunshine pages correctly in some cases, such as if a user was running Sunshine behind a proxy.
Fixes #1186
> fix(web ui): add response headers

- CMakeLists.txt
Use install prefix for the tray icon location.
> build(linux): honor install prefix for tray icon

- docker/fedora-37.dockerfile
Stop-gap fix to address the build break on Fedora 37 caused by their update to Mesa 23.0.3. We probably shouldn't be pinning the patch version (or maybe even the version at all), but this will get us moving again until we figure out the right approach for that logic.
> Fix Fedora 37 build

- src/network.cpp
Tailscale uses the Carrier-Grade NAT range assigned by RFC 6598 for its VPN interface. Since these addresses are intended for internal use in Carrier-Grade NAT systems, they will not be exposed externally (i.e. without a NAT/firewalll) so it should be safe to treat these as LAN addresses.
Fixes #1159
> Add RFC 6598 CGN CIDR block to LAN addresses list

- src/thread_safe.h
`alarm_t` is used by the mDNS registration code on Windows to pass back a pointer to the registered instance to the main thread. The code there assumes that the callback will `ring()` with `nullptr` if registration fails. However, `alarm_raw_t::wait()`'s condition predicate requires the value to satisfy `(bool) val == true` to return. Because `(bool) nullptr == false`, `wait()` never returns after our `ring()` and we deadlock the registering thread.
This is relatively harmless until the destructor for the mDNS `std::future` is called upon returning from `main()`. That will end up deadlocking the main thread and preventing Sunshine from terminating. Because this happens so late in the lifetime of the process, the fallback termination code is already cleaned up too. We will just sit in this …
> Fix deadlock during exit/restart if mDNS registration fails

- src/platform/windows/PolicyConfig.h
This PR removes the policy config for Windows Vista audio. Additionally, I have added `#include <mmdeviceapi.h>` which removes many false positive errors in CLion.
> fix(audio)!: remove policy config for Windows Vista

- CMakeLists.txt
- src/platform/common.h
- src/platform/linux/cuda.cu
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
- src/platform/windows/misc.cpp
- src/platform/windows/misc.h
- src/stat_trackers.cpp
- src/stat_trackers.h
- src/stream.cpp
- src/video.cpp
- src/video.h
Utilize 2 unused bytes of packet short header for transferring frame latency to moonlight.
Can't really granulate this latency (into processing and encoding for example) because of asynchronous nature of gpu commands, at least to my knowledge and while keeping the code clean. And I don't expect anyone particularly caring for it.
moonlight-common-c pull request: https://github.com/moonlight-stream/moonlight-common-c/pull/77
moonlight-qt pull request: https://github.com/moonlight-stream/moonlight-qt/pull/995
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with …
> Extend packet header with frame processing latency

- CMakeLists.txt
- src/config.cpp
- src/main.cpp
- src/main.h
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
- src/process.cpp
- src/system_tray.cpp
- src_assets/windows/misc/migration/migrate-config.bat
This PR contains a set of fixes and improvements for the elevated command redesign that @Nonary completed in #1123.
- The first commit ensures that we create the credentials directory before trying to set ACLs on it. Otherwise first installs would not have ACLs set correctly on this directory.
- The second commit reverts a change from #1123 that was resetting ACLs recursively on our directory. We don't want to do that because it would temporarily wipe out our stricter credential directory ACL, creating a window where an ordinary user could read it.
- The third commit reintroduces the start menu shortcut, but it launches Sunshine.exe with a special parameter that causes it to run in launcher mode. If the service is already running, it will just launch the web UI and exit.  If the service …
> Polish up the elevated command rework

- src_assets/windows/misc/migration/migrate-config.bat
Fixes issues accessing the `credentials` directory on non-English systems after the Elevated Commands Redesign. This also impacted the old code too, when we were granting access to the config directory for the `Users` group. 
I verified locally that manually removing the all ACEs from the `credentials` directory ACL and running the installer again will fix the issue for users already in the broken state.
> Pass the SID instead of the group name to icacls

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/workflows/CI.yml
- docs/source/about/installation.rst
dmg for macOS (created by macports) was approaching 900mb... This PR moves to create a drag-n-drop package by cpack.
Note: The dmg is still not recommended for use. I think we need to statically link on macOS like we do for Windows.
> packaging: fix macos dmg

- src/confighttp.cpp
This PR allows the UI username to be case-insensitive.
> fix(ui): allow case-insensitive username

- docker/archlinux.dockerfile
- docker/debian-bullseye.dockerfile
- docker/fedora-36.dockerfile
- docker/fedora-37.dockerfile
- docker/ubuntu-20.04.dockerfile
- docker/ubuntu-22.04.dockerfile
- docs/source/about/usage.rst
- packaging/linux/AppImage/AppRun
- packaging/linux/flatpak/scripts/additional-install.sh
- packaging/linux/flatpak/scripts/remove-additional-install.sh
- src_assets/linux/misc/85-sunshine.rules
- src_assets/linux/misc/postinst
This PR allows access to Sunshine's virtual keyboard, mouse, touchscreen and gamepad without adding the user to `input` group. This should simplify Sunshine setup for Linux users.
The trick is to add `TAG+="uaccess"` to Sunshine udev rule. It basically sets up proper ACL permissions on `/dev/uinput` for currently logged-in user. This is the modern way of granting device access to unprivileged users, rather than adding them to static groups. I removed the code that adds the user to `input` group from Linux packaging scripts and docs.
Note that `uaccess` tag only grants access to properly logged/authenticated users. For instance, users that were created in Docker containers should still be added to `input` group.
- Closes #1086
LizardByte requires that branches be up-to-date before merging. …
> Automatically grant access to Sunshine input devices on Linux

- .github/workflows/CI.yml
It's very difficult to debug user-reported crashes on Windows, even with a crash dump, because we don't build our binaries with debug info. This PR changes the Windows build to build with debug info and archive the unstripped binaries in a separate zip file for crash analysis. CPack strips the binaries before packaging, so the actual release binaries are unaffected by this change.
With this change, we can download the associated `sunshine-debuginfo-win32.zip` for a given build and generate PDBs with [cv2pdb](https://github.com/rainers/cv2pdb) to debug crashes from any nightly or release build.
I gave the debug info zip file a name with a different format than other artifacts to hopefully reduce the chance someone downloads it by mistake.
LizardByte requires that branches be up-to-date …
> Archive Win32 binaries with debug info for crash analysis

- docs/source/about/advanced_usage.rst
- src/audio.cpp
- src/platform/windows/audio.cpp
- src/thread_safe.h
- src_assets/common/assets/web/config.html
- tools/audio.cpp
This PR contains several improvements to make Windows audio capture easier to configure and avoid breaking streaming entirely if the audio sink is invalid. It also improves the audio-info.exe tool to fix misleading output in several cases.
- The first commit adjusts the Audio Sink and Virtual Sink values to accept device names, device descriptions, and adapter names. This results in a more stable configuration (since names don't change across reconnection, but IDs do) and is also easier for users to set up without having to use audio-info.exe. The documentation and UI are also changed to reflect that sink names should be used on Windows.  The old format device IDs are still supported for backwards compatibility with existing configs.
- The second commit cleans up some misleading output …
> Audio Capture Improvements

- src_assets/common/assets/web/index.html
This PR changes the nightly download URL from the artifacts URL to the release URL. While it's possible the release asset would not have been published yet, most users should be downloading from "releases" instead of from build artifacts.
Build artifacts will also expire after a set period of time.
> fix(ui): use release url for nightly releases

- src/nvhttp.cpp
- src/platform/windows/audio.cpp
This PR contains a couple fixes for audio device tracking issues on Windows (and a small fix for nvhttp.cpp to address a new warning in GCC 13.1).
- The first commit is the warning fix.
- The second commit adds an `IMMNotificationClient` that receives callbacks from the OS when the default audio device changes. Since we always want to capture from the default device, we reinitialize audio if the default device changes to ensure we pick up the new default device. This allows us to handle complex audio topology changes, like unplugging and replugging a monitor or TV with an integrated audio device while streaming.
- The third commit uses the notification added in the prior commit to enable us to set the default audio device back to the virtual sink if another application or device arrival …
> Default audio device tracking fixes

- src/system_tray.cpp
The systray icon doesn't always appear on my systems after a reboot. I wasn't able to consistently reproduce it to debug until I tried a signout/signin cycle which appears to always reproduce the bug for me.
I think this is happening because we're racing with the shell starting up. Adding a wait for the shell window to exist reliably fixes it for me.
> Fix systray icon sometimes not appearing after login

- src/video.cpp
This prevents the h264 encoder on Intel GPUs failing to provide a good image.
> Add NO_RC_BUF_LIMIT to vaapi

- src/main.cpp
- src/process.cpp
- src/process.h
- tools/sunshinesvc.cpp
SunshineSvc was not properly handling fast user switching, so the Sunshine process would continue running in the original session after the new session became the active console session. Since Sunshine was disconnected from the console, it could no longer capture the desktop or send input.
With this fix, SunshineSvc now requests session change notifications from SCM and will signal the main service thread to restart Sunshine if the active console session changes. Any connected clients will be disconnected when the first Sunshine process terminates, but this is the best we can do without major refactoring that's probably not worth the effort right now.
This also allows a client to reconnect to a host after Microsoft Remote Desktop has been used.
LizardByte requires that branches be …
> Fix console session changes via fast user switching

- CMakeLists.txt
With the latest MinGW Boost package change (https://github.com/msys2/MINGW-packages/commit/eabbec9dfad12b4bc5b85f9481942a4200d066d0), it tries to link to the (missing) shared library for Boost::thread with `Boost_NO_BOOST_CMAKE=ON` set. The linking error this was designed to fix seems to be gone now anyway.
> Remove Boost_NO_BOOST_CMAKE=ON to fix Windows build

- src/nvhttp.cpp
- src/platform/linux/vaapi.cpp
- src/video.h
This PR fixes all the leaks found by AddressSanitizer on my Linux machine. We were leaking continuously while streaming (not freeing `AVPacket` for each encoded frame) and also while not streaming if a Moonlight client was open and polling our server info over HTTPS (not freeing `X509` after cert verification). We also leaked a ton of VAAPI driver allocations each time the VAAPI encoder was reinitialized because `vaTerminate()` was never being called.
Resolves #1294
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request …
> Fix several major memory leaks

- src/nvhttp.cpp
- src/upnp.cpp
Sunshine's existing UPnP support has a number of major issues that make it basically unusable:
- UPnP port mappings only last a day after starting Sunshine
- Unable to handle or report conflicts with UPnP mappings registered by other PCs
- Unable to handle changes to WAN address
- Unable to handle router restarts that wipe UPnP mappings
- Unable to handle older routers that don't support IGDv2
This PR ports much of the UPnP logic from the Moonlight Internet Hosting Tool. We will now refresh UPnP mappings regularly to ensure they never expire while Sunshine is running, in addition to fixing the other issues mentioned above.
This PR also removes reporting of `ExternalIP` in the `/serverinfo` data. Trusting UPnP for external address info is not really a good idea. Some routers are known to …
> UPnP Support Rewrite

- tools/dxgi.cpp
Fix for a little bug in `dxgi-info.exe` reported on Discord. If we don't declare ourselves Per-Monitor DPI aware, `IDXGIOutput::GetDesc()` will report DPI-normalized values in `DesktopCoordinates` which causes us to display the wrong resolution for High DPI displays.
> Fix resolutions reported by dxgi-info.exe on high DPI systems

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/platform/windows/input.cpp
- src_assets/common/assets/web/config.html
https://github.com/LizardByte/Sunshine/commit/4e04604696a93020226182cba17562def1890467 caused a regression for Android clients when a normalized key mapping is unavailable (Android 12 and earlier) and the app on the host PC requires scancodes to register key presses properly.
This PR changes the default back to the v0.19.1 behavior of always sending scancodes but provides the option for users to send VK codes for correct behavior with non-US keyboard layouts.
Fixes #1233
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-re …
> Add option to always send scancodes and enable it by default

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/input.cpp
- src_assets/common/assets/web/config.html
The Guide button emulation code instantaneously pressed and released the emulated button, which worked very inconsistently due to the input polling behavior of most apps. Delaying for a short time while the button is down (like Moonlight's button emulation code does) allows the emulated button press to work consistently.
I was surprised to see that Guide emulation is enabled by default. This causes issues with apps/games that use a long press of the Back button for in-game functionality. Since most common controllers have Guide/Home buttons these days and users expect their controller buttons to behave normally out of the box, I've changed Guide button emulation be off by default. I don't expect this to be a major impact, especially because the feature itself was mostly broken prior to …
> Fix Home/Guide button emulation and disable it by default

- src/video.cpp
This regression was introduced by d973e5bbc7d63d44f3795f7ef45b9f8e263226f8 due to the removal of the `encoder.hevc[encoder_t::PASSED] = test_hevc` line.
> Fix software encoding defaulting to HEVC instead of H.264

- src/platform/windows/publish.cpp
Fixes error in Windows build after updating all msys2 packages:
```
D:\Software\msys64\mingw64\bin\c++.exe -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_LOCALE_NO_LIB -DBOOST_LOG_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_THREAD_NO_LIB -DCURL_STATICLIB -DMINIUPNP_STATICLIB -DNDEBUG -DSUNSHINE_ASSETS_DIR=\"assets\" -DSUNSHINE_PLATFORM=\"windows\" -DSUNSHINE_TRAY=1 @CMakeFiles/sunshine.dir/includes_CXX.rsp -O3 -DNDEBUG -std=gnu++17 -Wall -Wno-sign-compare -MD -MT CMakeFiles/sunshine.dir/src/platform/windows/publish.cpp.obj -MF CMakeFiles\sunshine.dir\src\platform\windows\publish.cpp.obj.d -o CMakeFiles\sunshine.dir\src\platform\windows\publish.cpp.obj -c D:\Software\msys64\home\Conn\Sunshine\src\platform\windows\publish.cpp
In file …
```
> windows: fix header conflict for msys2-w32api-headers 11.0.1+

- src_assets/common/assets/web/index.html
Fixes the Web UI Update notification System. 
Stable releases are now checked correctly and does not show an update available. 
I've also changed some methods into Vue computed fields, which is a better approach
Fixes #1103 
> Fix WebUI Stable Update notification

- docs/source/about/usage.rst
Add an SSH example to the Linux usage docs.
> docs: add linux ssh example

- docs/source/troubleshooting/linux.rst
This PR adds some Linux troubleshooting info regarding handicapped mesa that is now being shipped with some Linux distros.
> docs(linux): add information about mesa

- src_assets/common/assets/web/index.html
This PR fixes a bug where nightly releases could show the information from a PR if the PR head branch was named `nightly`.
The api request was changed to only look at push events, and also allows showing of any status, since many push events to the `nightly` branch will fail if the version was not updated.
> fix(ui): fix nightly release notifications

- .github/workflows/CI.yml
- CMakeLists.txt
- docker/debian-bullseye.dockerfile
- docker/ubuntu-20.04.dockerfile
- docker/ubuntu-22.04.dockerfile
- docs/source/building/linux.rst
- src/input.cpp
Sunshine crashes on Ubuntu 22.04 due a missing lib boost dependency. This PR adds the missing dependency for the deb packages.
> fix(deps): replace libboost chrono and thread with standard chrono and thread

- src/input.cpp
- src/stream.cpp
Certain input events, like pen/mouse, can be generated so frequently that we cannot inject them as fast as we receive them. This leads to significant latency accumulating as we get further and further behind, until we finally catch up when the client stops sending more input.
This PR implements input batching for these input types (controller state/touch/motion, pen/touch, mouse motion) to avoid this issue. Moonlight performs similar batching on the client side.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-bra …
> Input batching

- src/input.cpp
- src/platform/common.h
- src/platform/windows/input.cpp
This PR pulls out the extended button support and gamepad count fix from #1396 since they are trivial changes and don't depend on any of the major new protocol work happening in that branch.
Clients supporting these new button flags aren't released yet, but support is present in the Qt and Android clients as of now. iOS will probably be done in the coming few days.
Fixes https://github.com/LizardByte/Sunshine/issues/1362
> DS4 touchpad button support

- docs/source/about/advanced_usage.rst
- src/input.cpp
- src/platform/common.h
- src/platform/linux/input.cpp
- src/platform/macos/input.cpp
- src/platform/windows/input.cpp
- src_assets/common/assets/web/config.html
This is another PR split out of #1396 that implements the new controller arrival packet protocol extension. This allows the host to match the type of controller provided by the client, which means that prompts in games will have the correct PlayStation or Xbox button symbols. It's also important for vendor-specific extended features like controller touchpad and gyro/accel input.
I marked this as a breaking change because it's changing default behavior to match the client controller type instead of always using an Xbox 360 controller. I think this is desirable and it can be changed back to the old behavior by users if they want.
must be updated before it can be merged. You …
> Implement controller arrival metadata support

- src/network.cpp
ENet channels provide a solution to the head-of-line blocking issue common to reliable protocols after a packet loss. I'm adding multi-channel support to moonlight-common-c to be able to send mouse/keyboard/gamepad on separate channels, but we need to accept more than one channel for it to work.
This is a trivial change to pass 0 instead of 1 as the `channelLimit` parameter.
> Allow use of multiple ENet channels

- src/network.cpp
When connecting two machines without the use of a router, the machines are assigned link-local IPs. Sunshine is not considering these to be LAN IPs, making the web dash inaccessible.  
See also: discussion on Discord [here](https://discord.com/channels/804382334370578482/1074377411069747250/1126550517879947315)
N.A.
N.A.
> fix: consider link-local addresses as LAN

- .github/workflows/CI.yml
This adds a step to Flatpak builds to delete some unnecessary files from the runner and free up an additional 7 GB of disk space. The additional free space allows us to successfully extract the CUDA toolkit without running out of space.
> Clear additional disk space for Flatpak builds

- src/platform/windows/input.cpp
This is a preparatory PR for implementing the extended controller protocol features (motion, touch, battery, and RGB LED control) on Windows. We must send the full DS4 extended report rather than just filling out the simple report and relying on ViGEmBus to fill in the rest with default values.
This has the side-effect of fixing #1407 due to the incorrect assumption that it's safe to cast our `gamepad_state_t` directly to a `XUSB_REPORT`. That broke in #1401 when I extended the `buttonFlags` from a 16-bit to a 32-bit value and caused all the subsequent values to become offset when emulating an Xbox 360 controller.
I was going to wait to PR this until I had finished plumbing some of the extended features, but decided to do it sooner after I realized it fixes the root cause of #1407.
Fixes …
> Refactor gamepad emulation code to use the DS4 extended report format

- src/input.cpp
- src/platform/windows/input.cpp
Add support for the [applications (aka context menu) key](https://en.wikipedia.org/wiki/Menu_key). The key opens the context menu and it's useful for using GUI applications with a keyboard. I'm will add corresponding support in moonlight-qt in https://github.com/moonlight-stream/moonlight-qt/pull/1035 .
I had to change input::reset() to not send key-up events for keys that are not pressed because a key-up on the applications key will open the context menu, which would cause the context menu to always open after the client disconnects if the key was pressed by the client. …
> Add support for Applications (context menu) key on Windows hosts

- src/platform/windows/input.cpp
It's unnecessary and races with OS-wide event processing.
Fixes #1433
> Remove GetAsyncKeyState()

- src/input.cpp
- src/main.h
- src/platform/common.h
- src/platform/linux/input.cpp
- src/platform/macos/input.cpp
- src/platform/windows/input.cpp
- src/rtsp.cpp
- src/stream.cpp
This PR introduces support for many new controller features included in recent protocol extensions, including:
- Touchpad input (2-point multi-touch)
- Battery status events
- Accelerometer and gyroscope support
- Controller RGB LED control
The core plumbing work is done in this PR along with a Windows implementation of these features using ViGEmBus. @ABeltramo mentioned he wanted to take a stab at the Linux implementation.
This PR also fixes a bug that prevented rumble from working correctly for all gamepads when multiple clients are streaming at once.
Resolves #1200
Resolves #979  …
> Input extensions for controller touchpad, battery, RGB LEDs, and motion events

- .github/workflows/cpp-lint.yml
This PR adds the ability to ignore clang formatting specific directories, and will ignore the third-party directory initially.
> style(clang-format): ignore third-party directory

- .github/workflows/ci-docker.yml
- docker/ubuntu-20.04.dockerfile
This PR frees additional space on GitHub runners for docker builds, as some docker images were failing to build when building multiple architectures (on push events).
> build(docker): free additional space on runners

- .github/workflows/CI.yml
This PR frees additional space for Linux matrix in the CI, and changes the step in the Flatpak build to use the same action.
> ci(linux): free additional space on runner

- src/platform/windows/audio.cpp
- src/platform/windows/misc.cpp
- tools/audio.cpp
Several fixes for compatibility with new MinGW headers. As with previous similar changes, we will now require these newer headers to build.
> Build fixes for new MinGW headers

- docker/ubuntu-20.04.dockerfile
Within Ubuntu 20.04 Docker image, bump `gcc-10` from `10.3.*` to `10.5.*`
> ci(docker): bump gcc-10 in ubuntu 20.04 image

- src/input.cpp
These `std::clamp()` calls were no-ops until bd68aebe when I noticed the fact that the return value was ignored and fixed it. Unfortunately, the max values passed to `std::clamp()` were actually wrong so "fixing" the ignored return value actually broke the code.
Fixes #1512
> Fix clamping mouse position to aspect ratio adjusted viewport

- docker/fedora-37.dockerfile
- docker/fedora-38.dockerfile
Bump cmake from 3.26 to 3.27 for Fedora builds.
> ci(docker): bump cmake from 3.26 to 3.27 for Fedora

- src/platform/windows/display_base.cpp
Some older AMD AMF DLLs seem to crash when attempting to perform HEVC Main10 encoder tests, even if the underlying hardware doesn't support HEVC Main10 encoding at all. Since we probe all encoders on startup, this cause a crash loop.
To avoid this crash, we will specifically check for an AMD AMF version >= 1.4.23 before allowing HDR encoding. This AMF version corresponds to driver version 21.12.1 (almost 2 years old) and is a supported driver for all AMD cards with HEVC Main10 support.
Note: There are drivers from the legacy support branch that have versions newer than 21.12.1 but these all include older AMF versions (1.4.20 for the latest legacy driver version 22.6.1), so this check works as expected to exclude those drivers.
Pre-merge checklist:
Fixes #1503
Resolves #1012
LizardByte …
> Disable HDR encoding for AMF versions below 1.4.23

- src/main.cpp
This fixes the ability to print non-ASCII characters without crashing. Obviously crashing when trying to log non-ASCII characters is a pretty severe i18n problem for systems that aren't using English as the default/only language.
Fixes #1477
Fixes #475
Fixes #1446
> Use UTF-8 conversion for log output and C standard library functions

- .codeql-prebuild-cpp.sh
- .github/workflows/codeql.yml
Changes CodeQL to detect C++ (and C#) by remapping them to `cpp` (and `csharp`). Additionally:
- changes javascript variable `key` from `const` to `let` to allow overwriting
- adds workflow concurrency
- add ability to prebuild projects
https://github.com/LizardByte/.github/pull/240
> ci(codeql): detect cpp and charp

- src/cbs.cpp
This PR fixes issues with the CBS code that would cause crashes or corrupted output when we trigger the codepath where we replace the VPS/SPS with our own synthesized version. 
The `cbs::make_sps_hevc()` function used so much stack space that we'd crash due to stack exhaustion every time it got called. The first commit fixes this by moving `H265RawSPS` and `H265RawVPS` structs from the stack into heap allocations.
Unlike `cbs::make_sps_hevc()`, `cbs::make_sps_h264()` was manually constructing an SPS from scratch rather than taking the existing SPS provided by the encoder and tweaking it to contain the additional information we want to add. This was error-prone and led to invalid SPS output for at least some encoders (decoding a stream encoded by QSV that had this reconstructed SPS …
> Fix stack exhaustion and SPS corruption in CBS code

- src/nvenc/nvenc_base.cpp
- src/platform/windows/display.h
- src/platform/windows/display_ram.cpp
Software encoding stopped working on Windows, this fixes it.
> Fix regression introduced during standalone nvenc merge

- src/platform/windows/misc.cpp
Fixes a bug that caused Sunshine to fail to execute commands after a certain amount of times, caused by mutations to the environment that is shared with all processes in boost. When the PATH variable was being concatenated, it would continually append itself causing it to exceed the allowed limit and eventually prevent commands from running.
Erases environment variables before setting them again, to avoid a potential leak.
- Fixes #1456  …
> Command Resource Exhaustion bug fix

- src/nvhttp.cpp
Fixes an issue that caused the SUNSHINE_CLIENT_HDR setting to be always false.
- Fixes #1536 
> bugfix: fixed an issue that caused SUNSHINE_CLIENT_HDR to always be false

- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
The first commit contains a small fix for the process code to avoid a race condition where a process could spawn a child before we added it into our job for tracking purposes. This child would escape our control and wouldn't be terminated when the user quit the app. 
The second is cleanup related to #1456 to pass the environment as a const ref to avoid anyone being tempted to modify the passed in `env` parameter again.
> Miscellaneous process fixes

- .github/workflows/CI.yml
Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.
> Change Winget Releaser job to `ubuntu-latest`

- docker/archlinux.dockerfile
Fix ArchLinux Docker image cache issue, where it would build Sunshine two times (on each build step). Adding `--needed` to pacman command should prevent re-installing already installed packages.
> ci(docker): fix ArchLinux image cache

- docs/source/about/advanced_usage.rst
- src/cbs.cpp
- src/config.cpp
- src/config.h
- src/nvenc/nvenc_base.cpp
- src/nvenc/nvenc_config.h
- src/nvhttp.cpp
- src/platform/windows/display_base.cpp
- src/platform/windows/display_vram.cpp
- src/rtsp.cpp
- src/stream.cpp
- src/video.cpp
- src/video.h
- src_assets/common/assets/web/config.html
This PR implements support for encoding AV1 using FFmpeg and standalone NVENC. For the former, we require the changes in https://github.com/LizardByte/build-deps/pull/136, however we can't merge that yet due to the QSV memory leak introduced in FFmpeg 6.0. I tested the `av1_qsv` and `av1_amf` encoders using the WIP FFmpeg 6.0 build to ensure the encoder parameters and output bitstream were valid.
I added the `av1_vaapi` and `av1_videotoolbox` encoder names though they are not upstreamed in FFmpeg yet, so hopefully they will work when they get added.
The net effect of this PR alone is that it will turn on AV1 support for standalone NVENC (Windows). AV1 will be enabled for the other encoders when we update to FFmpeg 6.1.
Tested:
- Standalone NVENC + RFI
- QSV (requires FFmpeg 6.0+ build)
- …
> AV1 encoding support

- src/nvenc/nvenc_base.cpp
- src/nvenc/nvenc_base.h
Narrows down rfi arguments check to ref frames buffer size and removes log error message.
> nvenc: improve rfi logic

- CMakeLists.txt
- src/platform/windows/audio.cpp
This boosts audio capture thread priority beyond normal limits, and should rule out the possibility of buffer overruns.
> Use MMCSS task in audio capture thread

- src/main.cpp
- src/video.cpp
We didn't override the default FFmpeg log callback to use our loggers, so our FFmpeg logs would go to stdout rather than our log file. As a result, you wouldn't see the debug output unless you ran Sunshine from a terminal. This makes it difficult to debug issues like #1559.
Additionally, the HEVC and AV1 AMF encoders were never configured to log, while the H.264 encoder was always configured to log (though the output would be filtered by our configured log level). I changed the logging configuration to be conditional based on the configured log level for Sunshine, which is how we control our FFmpeg logging globally too. …
> Fix FFmpeg codec debug logging

- docker/archlinux.dockerfile
> ci(docker): fix arch linux cache issue

- docs/source/about/advanced_usage.rst
- src/platform/common.h
- src/platform/windows/display.h
- src/platform/windows/display_vram.cpp
- src/video.cpp
- src_assets/common/assets/web/config.html
This PR contains 2 changes to address some usability issues and inefficencies with our codec selection.
The first commit introduces a new `is_codec_supported()` function to `display_t` which can be used to allow displays to reject specific codecs. Rejecting specific AMF versions in the `display_t::init()` like I was doing before has negative side-effects because the caller assumes the error was caused by a capture failure and retries after 500ms. I moved the AMF check into the new `is_codec_supported()` function instead (in addition to adding basic GPU vendor checks for QSV and NVENC encoders).
The second commit changes the behavior around the codec mode options to address a user misconfiguration that led to all hardware encoding being disabled. We already treated HEVC/AV1 codec mode 3 …
> Codec support checks and improvements

- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
- src/stream.cpp
This PR implements proper source address preservation for video and audio traffic. Previously, outgoing traffic would be subject to regular OS routing logic, so it could be sent with a source address different than the address where incoming traffic from the host was received.
This work is also necessary to unblock IPv6 support in #571 due to IPv6 temporary addresses being preferred as source addresses for outbound traffic.
Tested:
- Windows (`send_batch()` and fallback `send()` path)
- Linux (`send_batch()` with `UDP_SEGMENT`, `send_batch()` without `UDP_SEGMENT`, and fallback `send()` path)
- macOS (`send()` only because `send_batch()` is unimplemented)
Fixes #1568 
must …
> Specify the source address for outbound audio and video traffic

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_vram.cpp
- src/stat_trackers.h
- src_assets/common/assets/web/config.html
This adds common synchronization point for consecutive frames, previously we calculated sleep duration on frame-to-frame basis, and this quickly accumulated errors because sleep function always overshoots (up to 1.5ms normally, 0.5ms in average).
Also removes the delay in releasing duplication surface, this dropped frames when the surface was not available during flip. And removes DwmFlush, because this hack is no longer necessary.
Related https://github.com/LizardByte/Sunshine/pull/1203, https://github.com/LizardByte/Sunshine/pull/1168
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating- …
> Improve capture sleep scheduling on Windows

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/confighttp.cpp
- src/network.cpp
- src/network.h
- src/nvhttp.cpp
- src/rtsp.cpp
- src/stream.cpp
- src/upnp.cpp
- src_assets/common/assets/web/config.html
This PR introduces a new "Address Family" option in the "Advanced" settings page which can be used to select between IPv4-only and IPv4+IPv6 modes for streaming. IPv4-only is the default to match the current behavior.
I've also implemented IPv6 Firewall Control via UPnP (based on the GSv6Fwd code) which is supported by some routers. This will automatically open the IPv6 firewall to allow communication when UPnP is enabled, similar to how we create port mappings via UPnP for IPv4. Some routers that don't support UPnP IPv6 firewall control support PCP for pinholes instead, but I will implement that in a future PR. For now, users can open the IPv6 firewall manually in those cases.
The dual address family mode depends on OS support for the `IPV6_V6ONLY` socket option which allows us to have a …
> Add IPv6 streaming support

- .readthedocs.yaml
Remove depreciated option from RTD config file.
> docs: remove depreciated system_packages option from rtd config

- src/platform/windows/input.cpp
Our pen tilt calculation wasn't correct, so applications could get incorrect tilt information. I adjusted it to use the same calculation logic that [Chromium uses](https://github.com/chromium/chromium/blob/6339259149a4291c7131ecafe340d8d5e87172c4/ui/events/android/motion_event_android.cc#L193-L203) and confirmed the results now match between client and host.
Tested with https://patrickhlauke.github.io/touch/pen-tracker/ and the Moonlight Android client.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-creat …
> Fix pen tilt angle calculation

- src/nvenc/nvenc_base.cpp
- src/platform/windows/display_vram.cpp
- src_assets/windows/assets/shaders/directx/ScenePS_NW.hlsl
It was offset because of missing shader constant buffer.
> Fix chroma subsample position

- src/video.cpp
The values used for initialization of a static `encoder_t` should not depend on runtime state. This only ever worked because the config was read before the `amdvce` `encoder_t` was constructed, but that is not guaranteed to be the case.
cc: @psyke83 
> Evaluate log_to_dbg value at encoder init

- packaging/linux/Arch/PKGBUILD
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
Fix broken url in flatpak manifest.
Additionally fixes issue where branches that contain `()` would fail on the ArchLinux docker build.
> ci(flatpak): fix boost url

- src/process.cpp
A recent pull request merged into nightly was not using the correct error codes to determine when to whitelist an error from prep commands. This corrects it to use the proper error code, allowing users to sign into their computer from a cold start if impacted.
> Fix Command Failure on cold starts with Desktop

- docs/source/building/macos.rst
Ran into a missing `PkgConfig` error while following the building for macOS instructions. Installing `pkg-config` with Homebrew fixed this issue:
`Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`
This PR updates the macOS Homebrew build requirements to include `pkg-config`.
> Updated Homebrew build requirements to include `pkg-config`

- cmake/compile_definitions/macos.cmake
Homebrew installs packages in a new location on Apple silicon Macs. The `macos.cmake` does not link this directory causing packages such as `opus` installed via homebrew to not be found.
The solution is to link this directory when performing the macOS build.
> Link the `/opt/homebrew/lib` directory on macOS

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/main.cpp
- src_assets/common/assets/web/config.html
Add a port configuration table to the UI.
Also validates the config port is is in the range of 1029 to 65514, and that all ports are in the range of 1024 to 65535.
Modifies alerts to include a font awesome icon.
Default value:
Custom value:
Invalid values:
- Resolves #1682 
> feat(ui): add port mapping table

- src/platform/linux/misc.cpp
Trivial fix for bug I discovered while testing #1692 on Ubuntu 22.04. I have no idea how this escaped detection until now. We must have just been getting lucky before and the stack happened to be zeroed or something.
> Fix crash during UDP segmentation due to stack garbage

- src/platform/linux/kmsgrab.cpp
Since libva 2.20, `vaInitialize()` will fail if we pass a `VADisplay` backed by a primary node and lack permission to authenticate. Since we don't actually need to have a primary node fd to encode, let's use a render node instead.
Fixes #1690
> Fix KMS grab VRAM capture with libva 2.20

- .gitmodules
- cmake/packaging/windows.cmake
- docs/source/about/usage.rst
- docs/source/troubleshooting/windows.rst
- src_assets/windows/misc/gamepad/install-gamepad.bat
- src_assets/windows/misc/gamepad/uninstall-gamepad.bat
This PR prepares Sunshine for the rebranding of vigembus.
> fix(installer): update vigembus

- src/system_tray.cpp
When sunshine is closed using the "Quit" button on the tray menu, the shutdown does deadlock, causing the 10s timeout to intervene. This change plans to fix this. Tested on Windows in foreground and service mode
> Fix shutdown when called from tray callback

- cmake/compile_definitions/linux.cmake
- cmake/packaging/linux.cmake
This PR fixes the Sunshine assets directory for AppImage build.
> fix(cmake): fix appimage assets directory

- src/main.cpp
I was seeing some intermittent deadlocks of the `sunshine.exe restore-nvprefs-undo` process during uninstallation. In that case, it looks like the process was exiting so fast that `CreateWindowEx()` was still trying to delay load MSCTF (and holding the loader lock) as the main thread was attempting to unload Winsock NSPs. The session monitor thread is holding the loader lock, which prevents the main thread from returning from `FreeLibrary()` and allowing the process to exit.
Moving the session window initialization to only happen we're actually initializing for streaming solves the deadlock. I tried reinstalling 7 times with this fix and didn't ever see the deadlock, so I'm pretty confident this fixes it.
The deadlocked threads:
```
00 0000007e`425ff6b8 00007ffe`37c99ffe …
```
> Don't start the session monitor window when launched in command mode

- src/platform/linux/input.cpp
- src/platform/windows/input.cpp
The Guide button is often reserved for OS functionality on the client OS like Game Bar, Home button, etc. which can leave users without a way to activate that functionality in game. Since a Misc button (Xbox One Share button, PS4 Mute button, etc) isn't physically present on Xbox 360 controllers, we might as well assign it to Guide to make it useful. Right now it's mapped to nothing.
I added the same thing in https://github.com/moonlight-stream/moonlight-common-c/commit/d055599608a9c50b9b5426790dad40fa3ab70687 on the client-side for GFE hosts.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collabo …
> Allow the Misc button to work as Guide on emulated Xbox 360 controllers

- src/rtsp.cpp
Our SDP response was a bit mangled due to a missing newline. Moonlight is still parsing it correctly, but we should fix it nonetheless.
> Fix missing newline in SDP response

- cmake/packaging/linux.cmake
The deb from the Docker image does not have all of its dependencies listed when packaged with `SUNSHINE_TRAY=1`:
```sh
$ ldd $(which sunshine) | grep "not found"
libayatana-appindicator3.so.1 => not found
libnotify.so.4 => not found
```
> Add missing dependencies for tray icon support

- .github/workflows/codeql.yml
CodeQL builds are running out of space randomly. This PR should fix that.
Changes will need to be added to `.github` repo as well.
> ci(codeql): fix build space issue

- src/confighttp.cpp
When the app.json is saved by the UI, a FATAL log level is sent to the logs which is wrongly intercept by the Web UI. This PR changes the log level of that message
> Remove false positive FATAL log

- src/platform/windows/input.cpp
Fixes Windows key regression reported on Discord using solution proposed by @psyke83. All other keys on the US English layout were tested and are working.
> Fix Super key regression after 8a7111a

- src/main.cpp
Follow-up to https://github.com/LizardByte/Sunshine/pull/1704
Should prevent similar freezes in the future.
> Properly join session monitor window thread

- scripts/update_clang_format.py
Removes `wayland-protocols` directory from clang format script, this was missed in #1731.
> build(scripts): remove wayland-protocols from clang-format script

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/httpcommon.cpp
- src/httpcommon.h
- src/nvhttp.cpp
- src_assets/common/assets/web/config.html
Removes the old method used in pairing that was present before the WebUI was implemented
> Removed legacy pairing method

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/platform/windows/input.cpp
- src_assets/common/assets/web/config.html
When forcing manual DS4 emulation, there isn't a natural way to trigger Touchpad click for standard XInput. Current impl supports passing MISC_BUTTON (Xbox Series X Share button), but Steam Input doesn't expose this mapping, and most other XInput controllers on client don't have this button available.
Allow additional accessibility for clients wishing to emulate DS4 by having Back/Select also trigger Touchpad click. In most games supporting native DS4 input, Back/Share does not do anything anyway and typically should translate to a Touchpad click.
My specific usecase here is using Sunshine via Steam Deck Moonlight client. A DualShock 4 or DualSense controller configured via Steam Input cannot map the Touchpad click to Xbox 'Share' and the only way to pass through Touchpad clicks through …
> Manual DS4 mode: Allow Back/Select to trigger Touchpad click

- src/platform/windows/audio.cpp
We should set WAVEFORMATEXTENSIBLE::Format::cbSize to `sizeof(WAVEFORMATEXTENSIBLE) - sizeof(WAVEFORMATEX)` instead of `sizeof(WAVEFORMATEXTENSIBLE)`. Incorrect cbSize can lead to audio capture failures on newer versions of Windows.
Fixes #1783
> fix(audio:windows): set cbSize correctly

- src_assets/windows/assets/shaders/directx/include/base_vs.hlsl
The regression was introduced in https://github.com/LizardByte/Sunshine/pull/1621 due to wrong copy-paste.
> Fix incorrect portrait mode rotation center on Windows

- docs/source/about/advanced_usage.rst
- src/config.h
- src/crypto.cpp
- src/crypto.h
- src/nvhttp.cpp
- src_assets/common/assets/web/config.html
This PR fixes the hardcoded assumption that signatures will always be 256 bytes long (corresponding to RSA-2048). With this change, we can support larger 3072 or 4096 bit RSA keys or other algorithms like ECDSA. Moonlight clients also need to be running updated code that corrects this assumption on their side too.
Interestingly, GFE has the same bug and won't tolerate anything but RSA-2048 keys.
> Don't hardcode the signature length to RSA-2048

- src/platform/windows/publish.cpp
The configuration we specify in `DNS_SERVICE_INSTANCE` causes Windows to respond with TXT records that violate RFC 1035. This API behavior isn't documented anywhere, but you have to specify one empty entry for Windows to produce compliant TXT records.
This fixes automatic discovery of Sunshine hosts by Moonlight clients on Apple devices that use the native mDNS implementation (iOS/tvOS).
> Fix discovery of Windows hosts by iOS/tvOS devices

- src/rtsp.cpp
Use the ping timeout for the launch event's timeout value, to allow users of slower clients more time to connect.
> Extend session timeout

- src/config.cpp
The framerates list is not cleared before adding values from the file configuration.
If the list is not cleared, then the set parameters do not affect the behavior of sunshine server.
> fix: ensure user supplied framerates are used

- src/main.cpp
- src/platform/windows/input.cpp
- src_assets/common/assets/web/index.html
This PR has a few changes to improve the UX for "fatal" errors in the web UI.
- It demotes FFmpeg's `AV_LOG_FATAL` log level down to our `error` level to avoid things like #1849
- It adds an error for ViGEmBus initialization failure since it's common for portable users to fail to install it and wonder why their gamepad doesn't work
- Tweaked wording to be less strong regarding configuration errors, since some may be expected in esoteric configurations
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created …
> Fatal warning improvements

- src/nvhttp.cpp
- src/rtsp.cpp
- src/rtsp.h
- src/stream.cpp
- src/stream.h
This PR introduces support for the `X-SS-Connect-Data` and `X-SS-Ping-Payload` extension that allows Moonlight to provide identifiers with its ENet connect message and A/V ping packets respectively.  This allows Sunshine to correctly correlate those connections with an active session even if they are coming from different IP addresses (which can often happen due to Carrier-Grade NAT).
These extensions require new Moonlight clients that contain the latest moonlight-common-c code, otherwise it will fall back to the older codepaths.
Associated Moonlight commits:
https://github.com/moonlight-stream/moonlight-common-c/commit/dc186082a72219e3ec5c7e8b74445d130dbcbd54
https://github.com/moonlight-stream/moonlight-common-c/commit/6e9ed871bc3e013386c775b2ee7d31deb1151068
Fixes #1804
Fixes #1862 …
> Implement new protocol extension to match client connections together

- src/audio.cpp
- src/rtsp.cpp
Historically, Moonlight has performed bitrate adjustments on its side to account for HEVC, HDR, and FEC overhead in various scenarios. These were very brittle and could lead to very unintuitive behavior in some situations (see the commit message of https://github.com/moonlight-stream/moonlight-common-c/commit/3ed3ba62534ce06c1b97fec46722969e7710fee6 for more details).
With this protocol update, a new SDP attribute `x-ml-video.configuredBitrateKbps` is sent from the client with the user's actual configured bitrate. This allows Sunshine to compute the encoding bitrate on its side, including things unknown to the client like the FEC percentage. It also allows the effective bitrate to exceed the 100 Mbps cap that GeForce Experience enforced.
LizardByte requires that branches be up-to-date …
> Compute the encoding bitrate on the host side for supported clients

- src_assets/windows/misc/gamepad/install-gamepad.bat
This implements the feature mentioned in https://github.com/LizardByte/Sunshine/pull/1948#discussion_r1438467072. We will no longer install or upgrade ViGEmBus if version 1.17 or later is already present. That version was released in December 2020, so this should mitigate the unexpected reboot issues during setup for the vast majority of cases. We use the extended DualShock 4 features, so we don't want to allow drivers older than 1.17.
> Don't install/update ViGEmBus if 1.17 or later is already installed

- src/platform/linux/vaapi.cpp
libva is supposed to be optional. Building currently fails with an unresolved symbol if it is missing.
> Use dl handle for libva's vaTerminate rather than actual function

- src/system_tray.cpp
- Use common variable for tray tooltip assignment, using `PROJECT_NAME` definition.
- Two warnings are generated during build due to converting a string constant to `char*` fixed in https://github.com/LizardByte/tray/pull/8.
```txt
#18 57.17 /build/sunshine/src/system_tray.cpp: In function 'void system_tray::update_tray_stopped(std::string)':
#18 57.17 /build/sunshine/src/system_tray.cpp:343:20: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
#18 57.17   343 |     tray.tooltip = "Sunshine";
#18 57.17       |                    ^~~~~~~~~~
#18 57.17 /build/sunshine/src/system_tray.cpp: In function 'void system_tray::update_tray_require_pin()':
#18 57.17 /build/sunshine/src/system_tray.cpp:362:20: warning: ISO C++ forbids converting a string constant to …
```
> fix(tray): use PROJECT_NAME definition for tooltip

- cmake/packaging/linux.cmake
- cmake/packaging/unix.cmake
- packaging/linux/flatpak/sunshine.desktop
- packaging/linux/sunshine.desktop
GNUInstallDirs (https://cmake.org/cmake/help/v3.18/module/GNUInstallDirs.html) is a CMake module which provides similar params as autotools allowing to adjust where files are installed.
On multiarch and/or cross layouts the prefix might be something like /usr/${arch} but arch independent files should still go into /usr/share.
> build(cmake): Use GNUInstallDirs to install data and lib directories

- cmake/compile_definitions/linux.cmake
- cmake/macros/linux.cmake
- cmake/prep/options.cmake
Gentoo Linux users on Wayland will almost certainly have these protocol files installed already. This makes the package a little simpler. Unfortunately, wlr-protocols does not appear to be packaged anywhere. This is the last of my unbundling requests, apart from allowing a custom build of ffmpeg.
> Optionally allow the system installation of wayland-protocols to be used

- .github/workflows/CI.yml
Install boost from source on macos runner.
> ci(macos): install boost from source

- src/process.cpp
This PR fixes an issue when the tray is disabled and a build warning was produced because of unused variable `has_bool`.
```
/Users/runner/work/Sunshine/Sunshine/src/process.cpp:261:10: warning: unused variable 'has_run' [-Wunused-variable]
bool has_run = _app_id > 0;
^
```
> refactor(process): re-order variables to avoid unused variable when tray is disabled

- src_assets/common/assets/web/template_header.html
This fixes a missing favicon in the web ui. I think this bug was introduced in #1673, and something was missed after rebasing the PR #1736, where the glob pattern changed.
An alternative fix is to adjust the glob pattern back to `server.resource["^/images/favicon.ico$"]["GET"] = getFaviconImage;`
> fix(ui): fix missing favicon

- src/process.cpp
- src/process.h
This issue took embarassingly long to diagnose for how simple it was. Our process grouping logic was not correctly terminating child processes when the parent died and in auto-detach mode. The cause turned out to be an errant check that required the launched app's process to still be running before we'd try to terminate _any_ processes launched in that group.
> Fix termination of child processes when the parent terminates

- src/platform/linux/graphics.cpp
- src/platform/linux/graphics.h
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/vaapi.cpp
- src/platform/linux/wayland.cpp
- src/platform/linux/wayland.h
- src/platform/linux/wlgrab.cpp
This PR fixes several bugs in the wlgrab capture code used for wlroots-derived compositors.
- wlgrab was using the logical size instead of the physical size for capture buffers, which caused problems for environments with a scaling factor != 1.0 (#238)
- wlgrab's `dummy_img()` was not safe to call on a separate thread (as required by `PARALLEL_ENCODING`), because it called `wl_display_dispatch()` which can block indefinitely when racing with another thread. When these races didn't lead to hangs, they would randomly lead to corrupt frames being captured that contained an amalgamation of metadata and buffers from partial frames that resulted in the `Couldn't import RGB Image: 0000300C` errors. This is fixed by updating VAAPI code to understand dummy images and sampling from a blank RGB …
> Wlgrab fixes

- cmake/FindLibva.cmake
- cmake/compile_definitions/linux.cmake
- cmake/prep/options.cmake
- docs/source/building/linux.rst
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/misc.cpp
- src/platform/linux/vaapi.cpp
- src/platform/linux/vaapi.h
- src/platform/linux/wlgrab.cpp
- src/platform/linux/x11grab.cpp
Supersedes #1961 by removing the use of `dlopen` for libva.
> build(linux) make vaapi optional without dlopen

- src/platform/linux/graphics.cpp
- src/platform/linux/graphics.h
- src/platform/linux/vaapi.cpp
This is a follow up to beb51cc9255c9b0d9d316c4f461f16d415caf620, which fixed issues with EGL import for tiled formats but didn't fix aux planes. Aux planes are used for color compression in some modern Intel hardware.
It refactors the `EGLAttrib` array creation into a single function that is shared between RGB and YUV import functions and fully populates that `surface_descriptor_t` with _all_ provided planes in the YUV import codepath to resolve the aux plane issue.
Fixes #1041
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a- …
> Fix EGL import of YUV buffers with aux planes

- src/platform/linux/graphics.cpp
- src/platform/linux/graphics.h
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/misc.cpp
- src/platform/linux/x11grab.cpp
- src/platform/linux/x11grab.h
This PR implements cursor plane capture for the kmsgrab codepath to allow cursor capture when hardware cursor support is in use. This new code replaces the old code that used XFixes to capture the cursor and removes the "off by default" cursor display behavior now that we're not relying on XFixes for cursor capture.
The code has the following restrictions/limitations:
- It assumes at most 1 cursor plane per CRTC
- Only linear ARGB8888 cursor buffers are supported 
- It can perform scaling (`CRTC_W/CRTC_H != SRC_W/SRC_H`) in the VAAPI encoding path but not the software encoding path
- It assumes the underlying cursor buffer will not be modified in place
- Modifications to the underlying dmabuf without a change to the `FB_ID` will not be captured, though using it as a texture atlas and …
> Implement support for KMS cursor plane capture

- src_assets/common/assets/web/ResourceCard.vue
- src_assets/common/assets/web/apps.html
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/index.html
- src_assets/common/assets/web/pin.html
- src_assets/common/assets/web/troubleshooting.html
- src_assets/common/assets/web/welcome.html
- reorder some config options
- add missing config options (inadvertently removed in #1673 
- use shortened line breaks
- removed va-api tab, and put `adapter_name` option on A/V tab
- used common spacing in html comments
- gamepad options only appear if gamepad/controller input is enabled
- keyboard options only appear if keyboard input is enabled
- mouse options only appear if mouse input is enabled
Todo:
> fix(ui): reorder and add missing config options

- docs/source/about/setup.rst
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
- src/process.cpp
- src/process.h
- src_assets/common/assets/web/apps.html
This PR introduces OS-specific graceful termination logic to allow apps to terminate normally rather than be abruptly killed when the client requests them to be stopped. On Windows, we send `WM_CLOSE` to all windows that are owned by processes in the app's process group. On Mac and Linux, we send `SIGTERM` to the process group.
This PR also introduces group-based app lifetime tracking which uses the process group to determine if the "app" is still running rather than just looking at the status of the first process we launched. This group-based tracking takes precedence over auto-detach if both are enabled and the initial process terminates after launching a child, since group-based tracking still allows full functionality of the running/not-running state and the Quit App button in …
> Implement graceful termination and group-based app lifetime tracking

- src/video.cpp
This allows use of low_power=1 for VAAPI to allow more performant encoding on capable Intel hardware (like we do for QSV). It also provides a low_power=0 fallback for QSV to allow use on old/low-end Intel GPUs that don't support low power encoding. Finally, this also implements a fallback to deal with the AMD driver regression on pre-RDNA cards that causes H.264 encoding to fail with AMF_VIDEO_ENCODER_USAGE_ULTRA_LOW_LATENCY.
The changes are pretty basic, but I'm leaving it in draft until I can fully test it.
Testing TODO:
Fixes #1559
Fixes #1412 …
> Add a fallback to retry codec init with more lenient config options

- docs/source/about/advanced_usage.rst
- src_assets/common/assets/web/config.html
This PR adds a hash handler to allow navigating to ids which are not normally available unless the correct tab is selected. Originally I was going to dynamically determine the closest "tab" to the element in the hash, but the element is not available unless the tab is already loaded, so I had to add a mapping of each tab to the options that they contain.
In adding this new mapping, I decided that the `defaultConfig` mapping could be moved to this new mapping. A small bug was also discovered and fixed when moving the `defaultConfig`, which was that the values that were not string encoded previously would not be evaluate properly when comparing the default value to the value in the UI.
The hash watcher can be tested by visiting `https://localhost:47990/config/#encoder`. This should work …
> feat(ui): add hash handler for configuration ids

- docs/source/about/advanced_usage.rst
- src/input.h
- src/platform/linux/input.cpp
- src_assets/common/assets/web/config.html
The first commit resolves a longstanding issue with how Linux input was treating absolute mouse input. Rather than emulating an absolute pointing device, Sunshine was actually emulating a single-touch touchscreen. This lead to all sorts of strange things depending on how the desktop environment treats touch input. Most commonly, it caused the cursor to disappear when not moving or mouse clicks to go to the wrong window. Now we behave like the Linux [vmmouse](https://elixir.bootlin.com/linux/v6.7/source/drivers/input/mouse/vmmouse.c) driver with separate absolute and relative mouse devices.
The second commit implements native support for pen and touch on Linux. I've tested with a few apps under a GNOME Wayland session plus `evtest` and the events look sane to me.
Testing checklist:
Fixes …
> Implement pen and touch support for Linux

- cmake/packaging/linux.cmake
When moving to installed `miniupnpc` instead of submodule in #1971, the dependencies were not specified for the DEB and RPM packages.
- Fixes #2021 
> build(linux deps): fix miniupnp dependency

- src/platform/linux/kmsgrab.cpp
- src/platform/windows/display_base.cpp
- src/video.cpp
- tools/ddprobe.cpp
This PR fixes a bug in Linux KMS capture where changing the display resolution while streaming would cause the stream image to become garbled. The issue turned out to be a mismatch between the Wayland viewports (enumerated in `kms_display_names()` once before the stream starts) and the actual framebuffer size (which can change when the display is reinitialized). The mismatch causes various GL errors and corrupt output.
This change also addresses the Windows issue of GPU driver updates while streaming causing Sunshine to hang due to all the old displays going away.
I've also included additional fixes for bugs discovered while testing, including:
- Fixed delayed switch to UAC secure desktop
- Fixed stream disconnecting with KMS grab when changing the desktop resolution in X11
Testing …
> Reenumerate displays when the display is reinitialized or switched

- src/platform/linux/misc.cpp
Makes Sunshine follow the XDG Base Directory specification when setting the configuration directory under Linux:
>  $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Additionally, following this change `$CONFIGURATION_DIRECTORY` will also be checked and used, if set. This is used by systemd services that explicitly specify a `ConfigurationDirectory=` option:
https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory=
This should have minimal to no impact on existing Sunshine instances, since users with `$XDG_CONFIG_HOME` …
> fix(linux)!: use XDG spec for fetching Linux configuration directory

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/crypto.cpp
- src/crypto.h
- src/network.cpp
- src/network.h
- src/nvhttp.cpp
- src/rtsp.cpp
- src/stream.cpp
- src/stream.h
- src_assets/common/assets/web/config.html
This PR does some refactoring of encryption-related code and implements video encryption and newer control stream encryption scheme. The main functional changes are https://github.com/LizardByte/Sunshine/pull/2025/commits/466492ba17ef36fcf7c4449610f0990b859b0608 and https://github.com/LizardByte/Sunshine/pull/2025/commits/2ac9ab2108f2866f3cf84343ed1bb29624f66942.
From the user perspective, this PR gives the user 3 options for both WAN and LAN connections:
- `ENCRYPTION_MODE_NEVER` - Never use video encryption even if the client supports (default for LAN)
- `ENCRYPTION_MODE_OPPORTUNISTIC` - Use video encryption if the client supports it but allow unencrypted connections from older/slower clients (default for WAN)
- `ENCRYPTION_MODE_MANDATORY` - Require video encryption for all connections. …
> Video encryption

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/nvenc/nvenc_base.cpp
- src/nvenc/nvenc_config.h
- src/platform/windows/nvprefs/driver_settings.cpp
- src/platform/windows/nvprefs/nvprefs_common.cpp
- src/platform/windows/nvprefs/nvprefs_common.h
- src/system_tray.cpp
- src/video.cpp
- src_assets/common/assets/web/config.html
This PR contains the changes from #1798 rebased on the nightly branch with the feedback items addressed.
The only major change is the removal of the reference frame configuration option per the feedback I gave on the original PR. We can discuss reintroducing that option when @ns6089 has time.
Fixes #1908
Fixes #1771
Closes #1798
> Expose more nvenc and nvprefs options (rebased)

- cmake/FindSystemd.cmake
- cmake/FindUdev.cmake
- cmake/packaging/linux.cmake
- docker/debian-bookworm.dockerfile
- docker/debian-bullseye.dockerfile
- docker/ubuntu-20.04.dockerfile
- docker/ubuntu-22.04.dockerfile
- Added FindSystemd.cmake
- Added FindUdev.cmake
- Edited linux.cmake to load these two new modules and read the new path variables for these modules
Instead of using `CMAKE_INSTALL_LIBDIR` to get the system lib directory where a library would be installed (can be 'lib' or 'lib64'), now the actual install path of `systemd` and `udev` are queried via `pkg-config`. This should be more reliable for linux builds.
My knowledge of `cmake` is limited so a review would appreciated.
- Fixes #2038 
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-ch …
> Find the correct install paths for systemd units and udev rules

- src/stream.cpp
This PR contains a couple optimizations of our encryption code.
The first commit performs some minor refactoring to avoid constructing `crypto::aes_t` (`std::vector<uint8_t>`) over and over for each incoming and outgoing encrypted packet. Instead, we create one IV per encryption context and reuse that.
The second commit is a tiny backwards-compatible protocol update to repurpose the unused field in the encrypted video header as a frame number. This allows moonlight-common-c to avoid unnecessary decryption of FEC packets for frames that have already been successfully reconstructed. This reduces CPU time in video decryption by 20% when streaming with the default 20% FEC percentage. cc: @ABeltramo 
LizardByte requires that branches be up-to-date before merging. This means that after any PR …
> Encryption optimizations

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/platform/linux/graphics.cpp
- src/platform/linux/graphics.h
- src/platform/linux/vaapi.cpp
- src/video.cpp
- src_assets/common/assets/web/config.html
This change adopts the new frame/sliced-based swscale API that allows multi-threaded scaling and color conversion. Multithreading significantly improves performance significantly with larger resolutions, since scaling and color conversion is largely bound by CPU performance.
During the rewrite, I also fixed a number of bugs including:
- Incorrect computations of offset and stride causing misaligned luma/chroma planes and/or visible green padding when scaling various resolutions
- Violating the swscale API buffer alignment requirements
- Hardcoded assumptions about pixel formats and chroma subsampling
As part of this PR, I also bumped the default minimum CPU thread count from 1 to 2. This lets us take advantage of swscale's multithreading support while also improving software encoding …
> Rewrite software scaling to improve performance and fix scaling issues with certain resolutions

- docs/source/building/linux.rst
`libcurl` was missing from Ubuntu build docs.
> docs(build): add missing libcurl build dep for ubuntu

- CMakeLists.txt
- cmake/compile_definitions/common.cmake
- cmake/compile_definitions/linux.cmake
- cmake/compile_definitions/macos.cmake
- cmake/compile_definitions/windows.cmake
- cmake/dependencies/common.cmake
- cmake/packaging/windows.cmake
- cmake/prep/build_version.cmake
- cmake/prep/constants.cmake
- cmake/targets/common.cmake
- tools/CMakeLists.txt
- Use CMAKE_SOURCE_DIR property in cmake
- Add quotes in case some paths have spaces
- Replace CMAKE_CURRENT_SOURCE_DIR with CMAKE_SOURCE_DIR in some places
This was originally part of #1603, but decided to break it out as it's not necessarily a change that is only needed for unit testing.
> build(cmake): use CMAKE_SOURCE_DIR property

- src/network.cpp
- src/network.h
- src/nvhttp.cpp
- src/process.cpp
- src/process.h
- src/rtsp.cpp
- src/rtsp.h
- src/stream.cpp
- src/thread_safe.h
This PR completes the full end-to-end encryption implementation by encrypting the RTSP traffic that is sent during session negotation. This completes the chain of trust from HTTPS -> RTSP -> Audio/Video/Control to prevent downgrade attacks on the other encryption schemes via manipulation of RTSP messages between Sunshine and Moonlight.
The first 2 commits are refactoring to get the code ready for the addition of encryption then https://github.com/LizardByte/Sunshine/pull/2095/commits/204489cac638a2eef2aff1c0a2a5fd13031d522a adds the actual encryption. cc: @ABeltramo 
Since RTSP is typically the flexible mechanism that we use to negotiate new options, encrypting RTSP is somewhat tricky to avoid breaking compatibility on both ends while still not allowing downgrade attacks against new …
> RTSP encryption support

- docker/clion-toolchain.dockerfile
This PR adds a custom "toolchain" dockerfile that can be used by CLion for cross platform development. See https://reenignearcher.github.io/2024-02-01-multiplatform-cpp-development-in-clion/
> build(docker): add docker toolchain for clion

- src/platform/macos/av_audio.m
- src/platform/macos/av_img_t.h
- src/platform/macos/av_video.m
- src/platform/macos/display.mm
- src/platform/macos/input.cpp
- src/platform/macos/microphone.mm
- src/platform/macos/misc.h
- src/platform/macos/misc.mm
- src/platform/macos/nv12_zero_device.cpp
- src/platform/macos/nv12_zero_device.h
- src/platform/macos/publish.cpp
- Correct some grammatical issues in comments.
- Many fixes suggested by Clang-Tidy.
> style(macos): various code style fixes

- .gitmodules
By alphabetizing gitmodules, it should create less cases where there are conflicts when adding new submodules in multiple PRs.
> style(submodules): alphabetize gitmodules

- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/display.mm
- src/platform/windows/display_base.cpp
- src/video.cpp
Encoder reprobing takes a significant portion of the total time to connect, especially when streaming the desktop. This PR addresses this by avoiding reprobing in cases where we know the GPU hasn't change and improving the performance of reprobing when we do need to do it.
To skip reprobing, we can use `IDXGIFactory1::IsCurrent()` which will tell us if GPUs or outputs changed state since the factory object was created. This check does catch a bit more than is needed, since some output changes will trigger a reenumeration. However, for desktop streaming and for games where the user just wants to adjust some Moonlight settings and get right back in, this is a major improvement. We can probably do better once #2032 is in.
For reprobing optimizations, we now avoid testing an encoder again …
> Encoder probing performance improvements

- src/confighttp.cpp
- src/main.cpp
- src/main.h
- src/network.cpp
- src/network.h
- src/nvhttp.cpp
- src/platform/linux/publish.cpp
- src/platform/macos/publish.cpp
- src/platform/windows/publish.cpp
- src/rtsp.cpp
- src/stream.cpp
- src/upnp.cpp
This PR moves the `map_port` function out of `main`, and into `network`.
Enabler for #1603 
> refactor(main): move map_port to network

- src/platform/windows/misc.cpp
This PR makes a few fixes and simplifications in the argument handling, including the fixing the issue reported in #2121 that broke handling of the `%*` argument replacement when there were more than 2 arguments being matched.
Fixes #2121 
> Fix and simplify handling of some shell argument replacements

- src/nvhttp.cpp
GFE provides the MAC address over both HTTP and HTTPS queries for /serverinfo, but there's no real good reason an unpaired client needs access to that information. Let's restrict the MAC address to the HTTPS endpoint for paired clients only.
The only use case this breaks is quite contrived anyway. It would have to be a client that previously discovered a host but _didn't_ pair with it, then later that same client wants to wake the PC up after it has gone to sleep. TBH, I think that scenario is closer to an unwanted annoyance than an actual feature due to the possibility another client on the network abusing this by waking your PC over and over again.
must be updated before …
> Cloak MAC address from unpaired clients

- .github/workflows/CI.yml
AppImage builds randomly fail, I believe because the VM becomes out of space. This PR increases the size of the VM by an additional 10 GB.
> ci(linux): increase root reserve for AppImage build

- src/nvenc/nvenc_base.cpp
- src/nvenc/nvenc_base.h
- src/nvenc/nvenc_d3d11.cpp
This implements a backwards compatibility solution for NvEncode API similar to what OBS did in https://github.com/obsproject/obs-studio/pull/7430 to reintroduce support for driver versions between 456.71 (minimum for v11.0) and 522.25 (minimum for v12.0). The net result is we now retain compatibility with drivers going back to October 2020.
I verified that AV1 still works as expected on my RTX 4080, while my RTX 2080 on extremely old drivers (456.71) can now stream with NVENC.
Fixes #2141
Fixes #2056
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks …
> Implement backwards compatibility for NVENC APIs back to Video Codec SDK v11.0

- src/main.cpp
This fixes a small bug introduced by #2110, where the version would be printed to stdout, but not to the UI log viewer.
> fix(main): fix version printing

- cmake/prep/options.cmake
- cmake/targets/common.cmake
This PR adds an option to prevent cuda from inheriting the original compile options. This is necessary to prevent CLion (and maybe other IDEs) from complaining about unknown flags after running the cmake command, when the IDE tries to index symbols.
> build(cmake): add option to skip cuda inheriting compile options

- .github/workflows/CI.yml
- cmake/compile_definitions/common.cmake
- cmake/compile_definitions/windows.cmake
- cmake/prep/options.cmake
- docker/debian-bookworm.dockerfile
- docker/debian-bullseye.dockerfile
- docker/fedora-38.dockerfile
- docker/fedora-39.dockerfile
- docker/ubuntu-20.04.dockerfile
- docker/ubuntu-22.04.dockerfile
- packaging/linux/Arch/PKGBUILD
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- packaging/macos/Portfile
This PR will error cmake on warning, causing CI to fail.
Todo:
> build(cmake): error build on warning

- cmake/compile_definitions/linux.cmake
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- src/platform/linux/input.cpp
This was an attempt to fix the flatpak build in #1603, although it unfortunately didn't... this is probably a better way to find evdev.
Borrowed from:
- https://github.com/PixlOne/logiops/blob/94f6dbab5390c1c7375836dd9314c0c2488e48a3/src/logid/CMakeLists.txt#L74
- https://github.com/PixlOne/logiops/blob/94f6dbab5390c1c7375836dd9314c0c2488e48a3/src/logid/InputDevice.h#L26
> build(cmake) properly find evdev

- .github/workflows/CI.yml
- .gitmodules
- cmake/compile_definitions/common.cmake
- cmake/compile_definitions/windows.cmake
- cmake/dependencies/common.cmake
- cmake/dependencies/windows.cmake
- docs/source/building/windows.rst
- packaging/macos/Portfile
> Use nlohmann_json package instead of submodule

- src/entry_handler.cpp
- src/entry_handler.h
- src/main.cpp
- src/platform/windows/misc.cpp
- src/stream.cpp
`std::abort()` destroys important state that is useful for debugging (particularly on Windows), so let's use a different method that disturbs as little process state as possible before breaking into an attached debugger or generating a coredump. 
> Use a common function to abort for debugging purposes

- cmake/packaging/windows.cmake
Since #1948, we display a fatal log message in the UI if ViGEmBus is unavailable. This is good to help users debug their gamepad issues, but it incorrectly triggers on a clean system when Sunshine is first installed. The problem is that we are starting Sunshine before we install ViGEmBus, so the first initialization happens without ViGEmBus and triggers the warning. Switching the order of operations in the installer should avoid the warning.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fo …
> Install ViGEmBus before starting Sunshine

- src_assets/common/assets/web/config.html
The `global_prep_cmd` and `fps` option mistakenly had regex replacement occurring while saving the config from the UI. This PR modifies the behavior to handle `resolutions` separately from other json style config options.
- Fixes #2160 
> fix(config): properly save global_prep_cmd and fps

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/video.cpp
- src_assets/common/assets/web/apps.html
- src_assets/common/assets/web/config.html
This PR contains a grab bag of mostly unrelated UI changes and adds the option for using non-lowpower HEVC encoding on Intel (see #2175)
Changes:
- Add option to use non-lowpower HEVC encoding on Intel
- Move UPnP option to the top of the Network tab, since it's by far the most commonly used option there
- Fixes the automatic gamepad type selection option appearing on Linux and Mac where it is not supported
- Adjusted the wording of the NVENC latency over power option to be more clear
- Renamed and moved the Channels option from the Advanced tab to the General tab and renamed it to something more descriptive
- Added a note to help users remember to enclose command paths in quotes if they contain spaces
- Renamed and moved the Files tab to feature less prominently in the UI since it's …
> Miscellaneous UI updates

- src/platform/windows/display_vram.cpp
This reworks our dummy image handling to avoid triggering a driver bug with 551.61 drivers and RTX HDR enabled. It also provides a small performance improvement for that (uncommon) case of interacting with dummy image textures.
Fixes #2163
> Add workaround for RTX HDR driver bug

- src/platform/linux/kmsgrab.cpp
- src/platform/linux/misc.cpp
- src/platform/linux/wlgrab.cpp
This introduces some new log messages that allow users using KMS and Wlgrab capture methods to know which display index they should specify to capture a given monitor.
Fixes #2079
> List KMS and Wlgrab displays and their indexes

- CHANGELOG.md
- src/platform/linux/cuda.cu
Trivial fix to prevent freeing a bogus texture object (which ironically causes a CUDA context leak due to `cudaDestroyTextureObject()` retaining the default context). The leaked context prevents the next CUDA hwcontext initialization from succeeding due to [incompatible flags](https://github.com/FFmpeg/FFmpeg/blob/f904e60c32a87f4124c3b94598a3b0141cd8b1b9/libavutil/hwcontext_cuda.c#L351)
> Fix CUDA context leak causing encoder init failures using X11 capture with NVENC

- docker/archlinux.dockerfile
The pre-compiled arch package was for sunshine-debug.
> build(linux): ensure pre-compiled arch pkg is not debug build

- .github/workflows/CI.yml
Fixes a small syntax mistake in the CI workflow.
> build(macos): fix publishing of portfile

- src/config.cpp
A bug in #1548 caused the FPS list in `config::nvhttp.fps` to be empty when no values were set manually. This broke Moonlight-Switch by causing no supported resolution to be advertised.
> Fix predefined FPS values not taking effect

- cmake/packaging/unix.cmake
- cmake/prep/special_package_configuration.cmake
- packaging/linux/flatpak/sunshine.desktop
- packaging/linux/sunshine.desktop
https://github.com/LizardByte/Sunshine/pull/1817#discussion_r1512688732
> Fix wrong path in desktop file

- .github/workflows/CI.yml
If a user accidentally downloads the debuginfo package, they will have a pretty confusing experience. They will see Sunshine.exe in there but then get a cryptic error when they try to run it (because a bunch of dependencies are missing). Based on our download stats, this confusion seems to happen quite regularly (probably because it's near the top in the list of artifacts today).
This change should move the debug info package down below the regular Windows binaries rather than being at the top above the "Show all assets" button. It also reduces the chance of confusion by renaming the files inside so they are not executable.
must be updated before it can be merged. You must …
> Make debuginfo artifacts harder to confuse with the Windows portable build

- src/platform/windows/display_vram.cpp
When a monochrome cursor contains a pixel count that is not evenly divisible by 8, we will run out of space in our cursor image buffer in the middle of processing a single byte of the cursor bitmap and start writing outside the bounds of the buffer. This is because we forgot to do a bounds check in the inner loop.
These cursors are apparently quite rare because this bug has existed in the codebase for over 4 years without being noticed or reported until a few days ago. Ryujinx in particular seems to quickly trigger it because it is frequently changing to a 1x1 pixel cursor and back, which corrupts a bit of memory each time until Sunshine eventually crashes.
Fixes #2219
must …
> Fix heap corruption with monochrome cursor pixel counts that aren't divisible by 8

- src/platform/linux/kmsgrab.cpp
This causes assertion failures when using libc++ debug mode, which Arch seems to do. 
Fixes #2215 
> Fix undefined behavior when computing cursor end pointer

- .github/workflows/CI.yml
- CMakeLists.txt
- cmake/prep/options.cmake
- cmake/prep/special_package_configuration.cmake
- cmake/targets/common.cmake
- docs/source/about/setup.rst
- packaging/macos/sunshine.rb
- src_assets/macos/misc/uninstall_pkg.sh
- vite.config.js
This PR will add a homebrew forumla for Sunshine.
Todo:
- Won't hold the action, as brew requires the forumlas to be in the main branch
- Done, see https://github.com/LizardByte/homebrew (action will take care of creating repo structure)
References:
- https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
- https://github.com/realqhc/homebrew
- Fixes #186 
- Resolves #342 
- Resolves #391 
> build(macos)!: add homebrew formula and drop dmg

- src/system_tray.cpp
This changelist declares the icons to be used by the system tray so that the tray logic can pre-fetch the resources during init. This prevents the icons from being fetched on demand, which can lead to DRM issues from invoking the shell API.
There are no visible changes to the user
- Fixes: #2092
> Use icon caching for system tray.

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- src/platform/linux/misc.cpp
This PR fixes an issue on Linux where the config directory may be changed without the user knowing, after #2034 was merged... and was most prevalent on flatpak installs.
@istori1 FYI
> fix(linux): automatically migrate config directory

- src/platform/linux/kmsgrab.cpp
- src/platform/linux/misc.cpp
This avoids trying to use broken cross-adapter encoding for NVENC when a non-Nvidia GPU is driving the display, like the issue described in #2140 and a support thread on Discord. Since NVENC appears earlier than VAAPI in the encoder list, this broken scenario will happen right out of the box with an Intel/AMD + Nvidia GPU setup.
The logic for detecting an Nvidia GPU is from [nvidia-vaapi-driver](https://github.com/elFarto/nvidia-vaapi-driver/blob/746d5510eabe949def3c79acc856393596d75cf5/src/backend-common.c#L21-L38).
Testing results with monitor connected to AMD GPU and Nvidia GPU present:
- With v0.21, we will fall back to X11 capture + NVENC in this scenario which works but the perf is horrible due to the CPU copyback.
- With v0.22, we try to use KMS capture with NVENC, but we fail …
> Avoid broken fallback to cross-adapter NVENC encoding with KMS

- .github/workflows/ci-docker.yml
- docker/fedora-38.dockerfile
- docker/fedora-39.dockerfile
- docs/source/about/setup.rst
* Let Fedora 38/39 build with Cuda 12.4 which allows gcc13
> fix(Linux/Fedora): re-enable CUDA and bump to 12.4.0

- CHANGELOG.md
- CMakeLists.txt
Version bump and changelog update.
> chore: bump version to v0.22.1

- .gitattributes
- docker/fedora-39.dockerfile
Fix for Fedora 39 arm64 build with CUDA.
Also, add a `.gitattributes` file to ensure dockerfiles are checked out with correct line endings.
> Fix(linux/fedora39) patch system headers so build succeeds with cuda

- CHANGELOG.md
- src/system_tray.cpp
Fixes the issue I saw with Sunshine hanging during termination with the main thread trying to reload a tray icon after `tray_exit()` was called:
```
14  ARM64EC 0000004f`35dfefa0 00007ffa`5b02349c     shell32!#SHPrivateExtractIcons+0x220
15  ARM64EC 0000004f`35dff240 00007ffa`5b023360     shell32!#ExtractIconExW+0x11c
16  ARM64EC 0000004f`35dff2b0 00007ffa`5b622a60     shell32!#ExtractIconExA+0x50
17  ARM64EC 0000004f`35dff4f0 00007ff7`81e595e0     shell32!$ientry_thunk$cdecl$i8$i8i8i8i8i8+0x28
18    AMD64 0000004f`35dff5a0 00007ff7`81e5984a     sunshine!_create_icon_info+0x30 [D:\a\Sunshine\Sunshine\third-party\tray\tray_windows.c @ 115] 
19    AMD64 0000004f`35dff620 00007ff7`81e59943     sunshine!_fetch_icon+0x5a [D:\a\Sunshine\Sunshine\third-party\tray\tray_windows.c @ 168] 
1a …
```
> Don't update tray icon after tray_exit() was called

- CHANGELOG.md
- CMakeLists.txt
- src/platform/linux/misc.cpp
This should be the fix for the crash during config migration that was reported on Discord and https://github.com/LizardByte/Sunshine/commit/a2785baf0aa7202bceecd975b1aa2d8798d2378a#commitcomment-139806889
@KuleRucket can you give this a try and see if it resolves the issue for you?
> Fix crashes in config migration

- src/video.cpp
- src/video.h
This PR aims to simplify creation of encoder fixtures for unit testing (#1603).
> refactor(video): move encoder declarations to header

- .github/workflows/CI.yml
Attempt to improve AppImage build, and hopefully resolve runner out of space and/or memory issues.
- Moves CUDA install to the very beginning (after installing wget)
- Changes install directory of CUDA
- Deletes CUDA after AppImage is packaged
- Reduces `-j` arg of `make` command from 4 to 3
- Removes legacy Ubuntu 18.04 logic
I attempted to bump GCC from 10 to 11, but this introduced new warnings, and errors in the AppImage lint step. This might provide a hint for the existing warnings?
w/ GCC-11
```txt
appimagelint.cli[12510] [INFO] Checking AppImage ./artifacts/sunshine.AppImage
appimagelint.cli[12510] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[12510] [INFO] detected required version for runtime: 2.14
appimagelint.glibc_abi_check[12510] [INFO] detected …
```
> ci(linux): refactor linux build

- .github/workflows/CI.yml
Silent installer for DevCon, per https://github.com/Drawbackz/DevCon-Installer/issues/10
> ci(windows): update devcon

- src/platform/linux/kmsgrab.cpp
- src/platform/linux/x11grab.cpp
This PR populates the frame_timestamp at the point that the KMS and X11 capture is done. This allows Moonlight to show the host latency in the statistics like it does for Windows.
n/a
> Populate host latency for kms/x11 grab

- .github/workflows/CI.yml
- packaging/macos/sunshine.rb
PRs with a default branch other than `nightly` would fail the audit of the homebrew formula. This PR modifies the behavior so the default branch is determined automatically.
> ci(macos): automatically determine default branch for homebrew formula

- src_assets/common/assets/web/pin.html
After localization updates, the pin page was rendered without the js that was responsible for sending the pin the backend.
> fix(ui): could not submit pin due to localization updates

- cmake/packaging/common.cmake
- cmake/packaging/linux.cmake
- cmake/packaging/macos.cmake
- cmake/packaging/windows.cmake
This PR makes a change to the build process, where asset files are copied to the build directory, so that the generated binary can be run without an install. This is mostly to improve the development process, although some users have wanted to run Sunshine without an install in the past as well.
This uses the `file(COPY ...)` method which actually copies the files when running cmake, before the build.
> build(cmake): copy asset files to build dir

- cmake/targets/common.cmake
- cmake/targets/unix.cmake
- cmake/targets/windows.cmake
In some cases, the command using bash to build the web-ui would fail, such as:
- Using the web-ui configuration in CLion
- User doesn't have bash installed, for whatever reason
> build(cmake): build web-ui target with cmd instead of bash on windows

- src/config.cpp
- src/entry_handler.cpp
- src/logging.cpp
- src/logging.h
- src/main.cpp
- src/stream.cpp
- tests/conftest.cpp
- tests/unit/test_logging.cpp
- tests/unit/test_video.cpp
Boost logs are captured in unit tests, and it was discovered that some encoder logging messages were not captured. This PR moves more (and hopefully all) logging setup to a `logging::init` method.
Example test output prior to this PR:
```txt
[ RUN      ] EncoderVariants/EncoderTest.ValidateEncoder/2
[libx264 @ 0x55d3f87659c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55d3f87659c0] profile High, level 4.2, 4:2:0, 8-bit
[libx264 @ 0x55d3f87659c0] frame I:1     Avg QP:31.00  size:  1203
[libx264 @ 0x55d3f87659c0] mb I  I16..4: 99.9%  0.0%  0.0%
[libx264 @ 0x55d3f87659c0] 8x8 transform intra:0.0%
[libx264 @ 0x55d3f87659c0] coded y,uvDC,uvAC intra: 0.0% 0.0% 0.0%
[libx264 @ 0x55d3f87659c0] i16 v,h,dc,p: 97%  0%  3%  0%
[libx264 @ 0x55d3f87659c0] i8 …
```
> fix(logging): add logging namespace and create logging::init method

- .github/workflows/CI.yml
Tests should not run if build fails.
> ci(macos): do not always run tests for macports build

- docker/fedora-38.dockerfile
- docker/fedora-39.dockerfile
- docker/ubuntu-24.04.dockerfile
- Drop arm64 from Ubuntu 24.04 image (temporarily)
- Don't run Python/docs tests on Fedora images as they fail on arm64
> fix(docker): fix arm64 builds

- .dockerignore
- docker/ubuntu-24.04.dockerfile
Remove `libavdevice-dev` as a build dep. What is this even used for?
Also, update docker ignore file.
> build: fix ubuntu 24.04 deps

- .github/workflows/ci-docker.yml
Fedora builds take > 6 hours since merging unit tests (#1603)...
> build(docker): increase job timeout

- .github/workflows/ci-docker.yml
- docker/fedora-38.dockerfile
- docker/fedora-39.dockerfile
Temporarily disable arm64 builds for Fedora. The builds exceed the 6 hour time limit on GitHub hosted runners.
The plan is to move the Fedora builds over to Copr eventually.
> build(linux)!: disable arm64 builds for Fedora

- src/crypto.cpp
- src/crypto.h
- src/nvhttp.cpp
> fix(security): ensure unpairing takes effect without restart

- src/platform/linux/graphics.cpp
Compiler warning
```
/run/build/sunshine/src/platform/linux/graphics.cpp:40:9: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
40 |     if (!size() == 0) {
|         ^       ~~
/run/build/sunshine/src/platform/linux/graphics.cpp:40:9: note: add parentheses after the '!' to evaluate the comparison first
40 |     if (!size() == 0) {
|         ^           
|          (          )
/run/build/sunshine/src/platform/linux/graphics.cpp:40:9: note: add parentheses around left hand side expression to silence this warning
40 |     if (!size() == 0) {
|         ^
|         (      )
1 warning generated.
```
must be updated before …
> fix(linux/capture): fix logical comparison of texture size

- tools/sunshinesvc.cpp
The path to sunshinesvc.exe needs to be quoted because it probably contains spaces, otherwise `CreateProcess()` will run `C:\Program.exe` if it's present. Fortunately, `C:\` prohibits ordinary user writes, so this type of bug isn't exploitable unless the user has manually loosened ACLs on the system drive.
For good measure, let's just pass the path directly to `CreateProcess()` to avoid all the executable searching nonsense.
> Quote the path to sunshinesvc.exe when launching the termination helper

- docker/clion-toolchain.dockerfile
- docker/debian-bookworm.dockerfile
- docker/debian-bullseye.dockerfile
- docker/ubuntu-22.04.dockerfile
- docs/source/building/linux.rst
Remove `libavdevice-dev` which was a left over from when we used packaged ffmpeg, it is not needed when using pre-compiled ffmpeg.
> build(deps): remove libavdevice

- cmake/targets/common.cmake
Building tests could not be disabled due to cmake failures.
- Fixes #2383 
> build(tests): ensure tests can be disabled during build

- src/platform/linux/kmsgrab.cpp
Fix setcap command in kms logging.
- Fixes #2399
> fix(linux): use correct setap command in logs

- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/wlgrab.cpp
- src/platform/linux/x11grab.cpp
- src/platform/windows/display_base.cpp
This commit computes the time of the next screen capture based on the current frame's theoretical time point instead of the actual capture time. This should be slightly more precise and lead to better frame timing.
I made the same change in three parts of the codebase:
- twice in `kmsgrab.cpp` (`display_ram_t` and `display_vram_t`). IIUC these correspond to capture to system RAM for software encoding and capture to VRAM for hardware encoding respectively. Please correct me if I'm wrong; I did not try to understand the whole pipeline.
- once in `x11grab.cpp` which presented the same issue.
At this point I did only preliminary testing of the kmsgrab & VA-API case on an AMD 6650. The results were very encouraging with a precise 60.0 Hz instead of the previous average of 59.94 Hz. (See #2286 …
> Improve frametiming for linux capture

- src/input.cpp
- src/input.h
- src/platform/linux/input.cpp
Fixes the issue described in #1905 by ignoring absolute input events until we've received a valid touchport from the display capture code. This prevents us from scaling client dimensions by 0 and invoking `std::clamp()` with invalid parameters (min > max).
I also included a fix for a bug caught by GCC 14 where `std::clamp()`'s result was discarded.
Closes #1905 
> Fix crash when an absolute position event is received too early during connection setup

- .github/workflows/CI.yml
- codecov.yml
Some fixes for excluding coverage directories as discovered in https://github.com/LizardByte/tray/pull/13
> ci: fix coverage ignore directories

- .codeql-prebuild-cpp-Linux.sh
- .codeql-prebuild-cpp-Windows.sh
- .codeql-prebuild-cpp-macOS.sh
- .github/workflows/codeql.yml
Updates codeql to run in a matrix for cpp analysis. This is required in order to analyze any code that is os specific.
See: https://github.com/LizardByte/.github/pull/322
> ci: update codeql to handle multiple OSes

- .codeql-prebuild-cpp-Linux.sh
- .codeql-prebuild-cpp-Windows.sh
- .codeql-prebuild-cpp-macOS.sh
- Use the correct make command for CodeQL
- Make sure prebuild fails, as needed
> ci: fix codeql prebuild steps for unix OSes

- .github/workflows/CI.yml
Skip coverage upload if not in LizardByte org, allowing contributors to run CI in their own fork more easily.
> ci: skip coverage upload if not in LizardByte org

- .github/workflows/CI.yml
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- packaging/macos/Portfile
- packaging/macos/sunshine.rb
- src_assets/common/assets/web/index.html
- Use BUILD_VERSION for flatpak, Portfile, and homebrew builds
- Use version with `v` prefix for all builds
- More robust version comparison in web ui
- Fixes #2406 
> fix: make version update check more robust

- src_assets/common/assets/web/pin.html
This makes it faster to input the PIN after clicking on the PIN notification on the desktop, since you no longer need to click the PIN input or focus on it by pressing Tab many times.
N/A
> Autofocus PIN input on Web UI pin page

- .github/workflows/CI.yml
- cmake/targets/common.cmake
- src/config.cpp
- src/httpcommon.cpp
- src/network.cpp
- src/network.h
- src/nvhttp.cpp
- src/platform/linux/cuda.cpp
- src/platform/linux/input.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/windows/input.cpp
- src/platform/windows/misc.cpp
- src/rtsp.cpp
- src/stream.h
- tests/CMakeLists.txt
- tools/CMakeLists.txt
#2149 was reverted in #2320 and needs to be split into three changes:
- C++20 (this one!)
- UCRT64
- WGC
> Use C++20.

- cmake/targets/common.cmake
- cmake/targets/unix.cmake
- cmake/targets/windows.cmake
Firstly, this unifies the asset building by leveraging CMake's env command. `add_custom_target` can also accept multiple commands to be run in sequence. It isn't clear how quoting applies here, but I've tested it, and it seems to be behave as expected when spaces are present.
Secondly, this uses `find_program` to find NPM so it can be overridden. This is useful for Gentoo, which needs to be able to do entirely offline builds, because it can override this with `/bin/true` while shipping pre-compiled assets. Gentoo has tried to ship cached NPM modules instead, but it turns out these are very sensitive to the NPM version. I also tried swapping in Yarn, which handles caching better, but ran into other issues.
LizardByte requires that branches be up-to-date before merging. This means that …
> Unify asset building and use find_program to find NPM

- src/file_handler.cpp
- tests/unit/test_file_handler.cpp
When developing unit tests in #1603, it was discovered that the `read_file` function would add an extra newline character.
Todo:
> fix(file_handler): avoid writing extra newline character

- src/audio.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/vaapi.cpp
- src/platform/linux/x11grab.cpp
- src/video.cpp
This PR collects a few minor improvements to the Linux logging code. It allows for easier troubleshooting. Here are the commit messages (with minor edits):
1.
```
Logging (Linux): emit basic GPU info at loglevel info
On multi-GPU systems it's useful to have essential
GPU info in Sunshine's log at the default 'info'
loglevel.
In particular, if x11grab was used in combination with
VA-API encoding, there was no indication at all about
the currently used GPU.
```
2.
```
Logging(Linux): log IDR frames at loglevel debug
IDR frames seem to be related to the occasional DATA_SHARDS_MAX
warnings observed by some AMD users.
```
3.
```
Linux/x11grab: add frame processing latency
This commit populates the img->frame_timestamp field, so that
Moonlight is now capable of showing the "Host processing …
```
> fix(linux): add frame processing latency and logging improvements

- .github/workflows/CI.yml
Currently VA-API encoding may/will fail when the AppImage is used. This seems to be because of a mismatch between the bundled `libva.so` and the system's `/usr/lib/*/dri/*_drv_video.so` driver libraries. ~~Since this is a rather important functionality the necessary libraries are now bundled in the AppImage itself in a relatively recent version.~~ This PR changes the AppImage build process in order to include a recent `libva` version. This should fix VA-API issues for Intel and AMD based systems. ~~I left out `nouveau_drv_video.so` since I'm somewhat skeptical of its encoding capabilities. (Please tell me if I'm wrong...)~~
I tested this PR on an older Intel-based laptop (Ubuntu 22.04, i965 driver) / on my main AMDGPU-based desktop. It's working fine for me.
See #2409 (but does not fix it …
> AppImage: add needed VA-API libraries (Intel & AMD)

- cmake/compile_definitions/macos.cmake
Modify cmake to only `link_directories` that exist on macOS. This will remove "warnings" from the cmake logs.
> build(macos): skip link of nonexistent directories

- src/platform/macos/av_img_t.h
- src/platform/macos/display.mm
- src/platform/macos/nv12_zero_device.cpp
- src/platform/macos/nv12_zero_device.h
- src/video.cpp
I have a MacOS 14.4 running with a AMD RX 570, and noticed the mentioned issues, so after discovering version 0.19.1 was working (thanks to @VasylBaran), I decided to try narrowing down the issue.
~~Partially reverts `e535706a09f1849d2799fd72e889e4d7182f7fe5`, this commit changes `av_img_t` and how it retains/release the frame buffers, which breaks something with how the frame is available to the encoder when needed and creates the mentioned issues.~~
~~If someone could help me out fixing `av_img_t` without reverting the structure, I would gladly improve this solution. Or if you have even another solution, I can pull and run here on my hardware.~~
Fixes `av_img_t` usage and related structs, while retaining it until the next `av_img_t` is correctly configured. This slightly changes how it …
> fix(macos): fix broken streaming on MacOS

- .codeql-prebuild-cpp-Linux.sh
- .github/workflows/CI.yml
- .github/workflows/codeql.yml
- Pin macOS code-ql runner to macOS-13 (x86_64) until https://github.com/github/codeql-action/issues/2266 is fixed
- Fix ubuntu code-ql build (again) by freeing up more space in root reservve for cuda...
This change requires an update to our .github repo, per https://github.com/LizardByte/.github/pull/330
> ci(codeql): fix codeql builds

- docs/source/troubleshooting/general.rst
Adds troubleshooting tips.
N/A
N/A
> docs: packet loss and linux controller

- src/stream.cpp
Currently the log message for Periodic Ping displays wrong packet type. This change fix the log message to show correct packet type.
Fix bug: [2537](https://github.com/LizardByte/Sunshine/issues/2537)
> Fix log message for Periodic Ping

- .github/workflows/CI.yml
- src_assets/common/assets/web/index.html
- src_assets/common/assets/web/public/assets/locale/en.json
- src_assets/common/assets/web/sunshine_version.js
- Compare each part of release versions
- Fix undefined variable
- Add info message when using a pre-release instead of stable
- CI fixes for if branch names contain parenthesis 
Using second oldest pre-release:
Using current pre-release:
Current latest version w/ pre-release notifications disabled:
Current latest version w/ pre-release notifications enabled:
Old version w/ pre-release notifications disabled:
Old version w/ pre-release notifications enabled:
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch- …
> fix(ui): ensure pre-releases are properly checked

- src_assets/common/assets/web/Navbar.vue
- src_assets/common/assets/web/ThemeToggle.vue
- src_assets/common/assets/web/apps.html
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/AudioVideo.vue
- src_assets/common/assets/web/configs/tabs/audiovideo/DisplayModesSettings.vue
- src_assets/common/assets/web/index.html
- src_assets/common/assets/web/init.js
- src_assets/common/assets/web/password.html
- src_assets/common/assets/web/pin.html
- src_assets/common/assets/web/public/assets/css/sunshine.css
- src_assets/common/assets/web/public/assets/locale/en.json
- src_assets/common/assets/web/template_header.html
- src_assets/common/assets/web/theme.js
- src_assets/common/assets/web/troubleshooting.html
- src_assets/common/assets/web/welcome.html
Includes dark mode, auto selects and allows for manually overriding with user preference
- Merging #2491
> feat(ui): Dark Mode

- .gitmodules
- wayland-protocols -> 1.36
- add `.git` extension to gitmodules to prevent redirect warnings for gitlab modules
> build(deps): bump third-party/wayland-protocols to 1.36

- .github/workflows/CI.yml
- docs/source/building/windows.rst
- src/config.cpp
- src/main.cpp
- src_assets/windows/misc/migration/migrate-config.bat
https://github.com/LizardByte/Sunshine/pull/2149 was reverted in https://github.com/LizardByte/Sunshine/pull/2320 and needs to be split into three changes:
-  C++20 
- UCRT64 (this one!)
-  WGC
If https://github.com/msys2/MINGW-packages/pull/20477 is integrated, WGC can proceed without this change.
> build(win): use UCRT64 environment instead of MinGW64.

- cmake/dependencies/common.cmake
ffmpeg build names have changed in https://github.com/LizardByte/build-deps/pull/326
> build(deps): use new ffmpeg build names

- src/confighttp.cpp
- src/nvhttp.cpp
- src/nvhttp.h
- src_assets/common/assets/web/pin.html
- src_assets/common/assets/web/public/assets/locale/en.json
- src_assets/common/assets/web/troubleshooting.html
Introduces the option to name clients during PIN pairing, along with a UI to remove individual client certificates. The format of `sunshine_state.json` was updated to include a `named_certs` array instead of the previous `certs` array. The old array is used for migration to the new format on startup.
Here's an example of the new format:
```json
{
...
"root": {
"uniqueid": "2258BFE6-698A-422C-5F0F-55B49A69C69E",
"devices": [
{
"uniqueid": "0123456789ABCDEF",
"named_certs": [
{
"name": "NVIDIA Shield",
"cert": "-----BEGIN CERTIFICATE-----\nCERT\n-----END CERTIFICATE-----\n",
"uniqueid": "41310952-60C8-1B01-A615-033CC8275E5F"
},
{
"name": "Steam Deck",
"cert": "-----BEGIN CERTIFICATE-----\nCERT\n-----END CERTIFICATE-----\n",
"uniqueid": "AE113204-32D9-6607-6285-7F3C200440EB"
}
]
}
]
}
}
``` …
> Name and unpair individual clients

- src/audio.cpp
- src/audio.h
- src/nvhttp.cpp
- src/process.cpp
- src/rtsp.cpp
- src/rtsp.h
- tests/conftest.cpp
- tests/unit/test_audio.cpp
This PR is made for improving webOS client support. On webOS 5.0 and above, if surround channel configuration is done properly, it can re-encode OPUS stream on-the-fly & send it to surround sound system through eARC/Optical.
Currently, webOS only handles 6-channels, 4 streams & 2 coupled streams configuration, and the channel must be ordered as `[0, 1, 4, 5, 2, 3]` which Sunshine doesn't have. It won't accept stream header either, which makes this PR necessary.
With this PR, if `surroundParams` is specified (formatted like `surround-params=` in RTSP handshake, e.g. `642014523`) in HTTP launch request, it will be applied, and during RTSP handshake, our custom surround-params `a=fmtp:97 surround-params=642014523` will be advertised twice first, followed by the original ones.
Not applicable …
> feat(audio): custom surround-params

- .clang-format
I propose those changes, so for example:
```cpp
constexpr auto MAX_GAMEPADS = std::min(static_cast<std::size_t>(platf::MAX_GAMEPADS), sizeof(std::int16_t) * 8);
```
breaks instead like this:
```cpp
constexpr auto MAX_GAMEPADS = std::min(
static_cast<std::size_t>(platf::MAX_GAMEPADS), 
sizeof(std::int16_t) * 8
);
```
Also, ensures most places don't do:
```cpp
BOOST_LOG(debug)  << "--begin controller touch packet--"sv << std::endl
<< "controllerNumber ["sv;
```
And do
```cpp
BOOST_LOG(debug) 
<< "--begin controller touch packet--"sv << std::endl
<< "controllerNumber ["sv;
``` …
> style: break lines more often, allow multiline params

- src/platform/linux/cuda.cpp
This PR is based on https://github.com/hgaiser/nvfbc-rs/pull/5 , which in turn is based on https://github.com/keylase/nvidia-patch/blob/master/win/nvfbcwrp/nvfbcwrp_main.cpp#L23-L25 .
With this change you don't need a patched NVIDIA library to use NvFBC. My best guess is that this is what GeForce Experience uses to allow it to work on GTX / RTX cards.
N/A
N/A
> Remove the need for a patched nvidia library for NvFBC.

- .github/workflows/update-docs.yml
We need to change the "default_branch" property in readthedocs in order to make the "latest" version point to our latest stable release.
This workflow will probably become a global workflow and replicated from .github. See: https://github.com/LizardByte/.github/pull/341
> docs: update readthedocs on release events

- docs/source/about/advanced_usage.rst
- docs/source/about/setup.rst
- docs/source/troubleshooting/general.rst
- docs/source/troubleshooting/linux.rst
- add more specific note about setcap / appimage / flatpak
- add note about AMD lowlatency issues on linux
- add note about buffer overruns if there's a speed mismatch between host/client
> docs: add more troubleshooting notes

- .github/workflows/CI.yml
- packaging/sunshine.rb
Publish a homebrew formula with the release tag instead of the branch name. The tag doesn't exist when the formula is validated, so the validation will be skipped for this job.
> fix(homebrew): use tag instead of branch in formula

- .github/workflows/CI.yml
- packaging/sunshine.rb
`version` in brew formula cannot have a `v` prefix.
> fix(brew): remove v prefix from version number

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- src/config.cpp
- src/confighttp.cpp
- src/file_handler.cpp
- src/file_handler.h
- src/httpcommon.cpp
- tests/unit/test_file_handler.cpp
- tests/unit/test_httpcommon.cpp
> tests: add httpcommon tests and add new file_handler methods

- src/platform/linux/input/inputtino_gamepad.cpp
A quick fix after this report https://github.com/LizardByte/Sunshine/pull/2606#issuecomment-2171961026
What is happening there is that the Moonlight Switch client doesn't support battery, in absence of a value the virtual pad state defaults to `0` which causes the pad to be seen with 0% battery.  
I've done two things:
- set the default in inputtino to be `CHARGED`/`100%` so that we avoid annoying notifications for clients that don't report that value
- adjusted the battery raw values, Moonlight sends them in the range `[0, 255]` whilst inputtino expects a percentage value `[0, 100]` …
> fix(linux/input): battery values conversion

- docker/fedora-39.dockerfile
- docs/Doxyfile
- src/platform/linux/graphics.cpp
- src/platform/linux/wayland.h
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
More fixes for Doxygen. See #2731
> docs: more doxygen fixes

- cmake/compile_definitions/common.cmake
- cmake/prep/options.cmake
- packaging/macos/Portfile
- packaging/sunshine.rb
macOS has some issues with Boost linking, this PR fixes the runtime error when statically linking boost, fixes the dynamic macOS build missing -licudata (icu4c) and improves brew installation options.
> fix(macos): fix boost on macos

- docs/CMakeLists.txt
Locate the venv interpreter instead of assuming it's location based on the OS.
> build(docs): use patterns to locate python venv interpreter

- docs/Doxyfile
Extracting all causes many things to have missing documentation sections in the generated docs.
> docs(doxygen): do not extract all

- docs/Doxyfile
This is required for Doxygen >= 1.10.0, although it doesn't affect us because we have a custom `header.html` where the copy clipboard functionality was removed altogether, in favor of doxygen-awesome-css' clipboard feature.
See: https://github.com/LizardByte/Sunshine/pull/2765
> docs(doxygen): disable html copy clipboard

- src/upnp.cpp
- src/upnp.h
Fixes incompatibilities with newer version of miniupnpc library.
- Closes #2746 
- Fixes #2775 
> fix(upnp): support newer miniupnpc library

- .github/workflows/CI.yml
AppImage build unit tests seem to randomly fail. I believe it can be solved by adding a small delay before test execution starts.
> ci(appimage): add sleep delay before test execution

- docs/source/building/macos.rst
- packaging/macos/Portfile
- packaging/sunshine.rb
- src/platform/linux/publish.cpp
- src/platform/macos/publish.cpp
The current implementation of service publication on macOS uses
`avahi-client`, but the majority of macOS machines do not have Avahi
installed because macOS provides a native alternative (`mDNSresponder`),
meaning that there is no reason to install Avahi.
The current implementation also attempts to load the Avahi client
libraries using `dlopen(3)`, which has a variety of restrictions on
macOS, such as only being willing to load from certain directories.
Depending on where the Avahi binaries are installed, they might not
be loadable through the current invocation of `dlopen(3)`.
Instead of using an Avahi client on macOS, it makes more sense to use
the native macOS API for publishing services via `mDNSresponder`. This
commit supplies such an implementation that uses the macOS native API.
It …
> macOS: New implementation of service publication

- src_assets/linux/misc/postinst
When building locally, cmake defaults to a prefix of `/usr/local`. In particular sunshine ends up being `/usr/local/bin/sunshine`. However the `postinst` script uses a hardcoded path `/usr/bin/sunshine`. This leads to a failing setup when the locally built sunshine is packaged as a `.deb` using `cpack`. This commit fixes this minor issue by making the `postinst` script search for the binary using `which`.
Or should we also generate `postinst` via cmake's `configure_file` in order to properly hardcode the correct path? I'm not really familiar with cmake but I could give it a try. (I am also wondering if it's really an "asset" or if it rather belongs in "packaging")
must be …
> build(linux): make postinst use which to find sunshine

- src/platform/common.h
- src/platform/linux/vaapi.cpp
- src/video.cpp
Intel needs RC buffer size unset for their H.264 encoder to avoid horrible encoding quality, however this causes issues for AMD cards overshooting the expected maximum frame size and causing packet loss. Resolve this by adding a new hook in `avcodec_encode_device_t` to allow the platform encoding code to set additional options on the codec context and using the vendor string to distinguish Intel cards.
Fixes #2788
> Fix rate control for AMD cards using VAAPI

- docker/archlinux.dockerfile
- docs/source/about/setup.rst
- docs/source/about/third_party_packages.rst
Dropping support for ArchLinux AUR as I am not willing to constantly battle people like `@xiota`, `@dr460nf1r3`. No bug reports will be accepted from users using any AUR package.
> build(linux): drop support for AUR

- docker/archlinux.dockerfile
- docs/source/about/setup.rst
Generate a .SRCINFO file when building Arch package.
> build(archlinux): generate srcinfo file during build

- src/platform/windows/display_wgc.cpp
Using the new WGC capture method on Windows 10 currently causes a segmentation fault.
This should resolve it.
> Check API before trying to disable border on WGC capture

- cmake/compile_definitions/windows.cmake
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/misc.cpp
- src/stream.cpp
- src/utility.h
Combat RX/TX buffer overflows and improve multi-FEC on large frames.
Adopted from https://github.com/LizardByte/Sunshine/pull/1466
Should supersede https://github.com/LizardByte/Sunshine/pull/2787
> Implement basic network flow control

- cmake/compile_definitions/common.cmake
- cmake/targets/common.cmake
- src/main.cpp
- src/rswrapper.c
- src/rswrapper.h
- src/stream.cpp
- tests/unit/test_rswrapper.cpp
I spun this out of #2803 when it became evident that the simple solution of just adding `-mssse3` wouldn't work.
This implementation uses GCC support for function targets to compile the Reed-Solomon code multiple times for SSSE3, AVX2, AVX512, and the default ISA flags. It provides a faster implementation than just hardcoding `-mssse3` while also not breaking non-x86 architectures or older x86 CPUs without SSSE3. It's definitely more complex than a compiler flag, but I think the performance gain is worth it and the complexity is pretty compartmentalized to `rswrapper.h/c`.
On my Ryzen 5950X, AVX2 is about 2x faster than SSSE3 which is about 4x faster than the C variant.
```
Samples: 3K of event 'cycles:P', 4000 Hz, Event count (approx.): 1243747209 lost: 0/0 drop: 0/0
Overhead  Shared …
```
> Provide SSSE3, AVX2, and AVX512 optimized Reed-Solomon functions

- src/platform/linux/input/inputtino_pen.cpp
Currently, pen input is unusable on linux, because of the following issues, as per #2756 
- No pressure sensitivity while using the pen
- Pen doesn't release when hovering after the first touch
This is caused by the fact that EVENT_MOVE events are considered to not touch the screen, which is not the case.
- Fixes #2756 
>  fix(linux/input): handle pen EVENT_MOVE events 

- src/logging.h
- src/nvenc/nvenc_base.cpp
- src/nvenc/nvenc_base.h
- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/wlgrab.cpp
- src/platform/linux/x11grab.cpp
- src/platform/windows/display_base.cpp
- src/stat_trackers.cpp
- src/stat_trackers.h
- src/stream.cpp
Refactor recurring code into dedicated classes and address small edge-case I missed in #2803
> Refactor periodic loggers and limit batch size for small packets

- src/stream.cpp
- tests/unit/test_stream.cpp
The streaming code is copying the entire frame into a new `std::vector` (using the slow `std::back_inserter()` too) just to prepend the frame header, right before it copies it a _second_ time to insert the packet headers. We can easily consolidate these operations into one to prevent a useless allocation and copy of every frame we encode.
This isn't the only redundant copy left (`fec::encode()` does one), but it's the only one that's easy to get rid of. Removing more copies requires scatter/gather I/O support in `platf::send()`/`platf::send_batch()` to allow us to submit separate buffers for the header and payload data of each packet. It's not _that_ hard to support S/G, but it's tricky to actually use due to the myriad frame/packet headers (some of which participate in FEC, while others …
> Eliminate a redundant alloc+copy of each frame

- src/platform/linux/input/inputtino_gamepad.cpp
The `battery.percentage` value is a real percentage (`0..100`), but it has a special value of `LI_BATTERY_PERCENTAGE_UNKNOWN` (0xFF) to indicate the percentage is unknown. We shouldn't pass this value or the `LI_BATTERY_STATE_UNKNOWN` status into `inputino`.
cc: @ABeltramo 
Fixes #2715
> fix(linux/input): don't pass unknown battery values

- src_assets/common/assets/web/configs/tabs/audiovideo/LegacyDisplayOutputSelector.vue
Backslashes were not escaped which caused default value hint for captured display to be incorrect.
> Escape backslashes in javascript string

- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
- src/stream.cpp
This PR implements scatter/gather I/O support in the platform socket code for non-batched sends. Because we can specify separate header and payload buffers, this allows us to eliminate all redundant copies of audio shards. The performance impact of this change alone is quite small, but it will reduce the complexity of the following PR that implements S/G for batched sends.
I also included a drive-by fix for another missing `std::vector::reserve()` call that was causing horrible performance when using `std::copy()` with `std::back_iterator()`.
Testing checklist: …
> Implement S/G IO for non-batched sends and eliminate more data copies

- src/crypto.cpp
- src/crypto.h
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/windows/misc.cpp
- src/stream.cpp
This is the final part of #2867 which implements scatter/gather IO for `platf::send_batch()` and eliminates the frame copy in `fec::encode()` by FEC encoding and sending directly out of the payload buffer. This is done by introducing support for payload buffer lists containing multiple contiguous payloads buffers (necessary because data and parity shards are in different buffers). It also introduces the ability to begin sending messages from a specified offset which avoids having to adjust the buffer lists when we send a FEC block in multiple parts for frame pacing.
Testing checklist: …
> Implement S/G IO for batched sends and eliminate another frame copy

- src/platform/windows/misc.cpp
Trivial fix for an invalid parameter we have been passing to `WSASendMsg()`. I must have had `sendmmsg()` on the mind when I was writing this because the third parameter is `dwFlags` not the count of `WSAMSG`. 1 is `MSG_OOB` which is invalid for a UDP socket, but apparently we get lucky and `WSASendMsg()` just ignores it.
> Fix invalid parameter passed to WSASendMsg()

- src/audio.cpp
- src/logging.cpp
- src/logging.h
- src/platform/common.h
- src/platform/linux/audio.cpp
- src/platform/macos/av_audio.h
- src/platform/macos/av_audio.m
- src/platform/macos/microphone.mm
- src/platform/windows/audio.cpp
Float is the native format of opus codec and most if not all capture backends.
Implementation progress:
> Migrate audio pipeline to float from 16-bit integer

- src/logging.cpp
- src/logging.h
For some reason, sometimes it could cause compiler issues:
https://github.com/LizardByte/Sunshine/actions/runs/10107693224/job/27952073497
> fix: remove logging::bracket "*_view" overloads

- docs/source/about/guides/app_examples.rst
- docs/source/troubleshooting/general.rst
- docs/source/troubleshooting/linux.rst
- packaging/linux/sunshine.service.in
- src_assets/common/assets/web/public/assets/locale/en.json
I've added or updated the documentation in a few places:
* add note about improved networking/streaming code
* add Gnome Wayland resolution change notes (was undocumented)
* delay startup via systemd if necessary
* update note about AMD low-latency mode. (This is only a preliminary update)
There is also one change to the WebUI:
* WebUI: refer to log for detected displays (the text was misleading)
(screenshot done with `LC_ALL=en sunshine`)
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork …
> fix(linux): add delay to service and improve troubleshooting docs

- cmake/prep/build_version.cmake
Cpack binaries are getting version 0.0.0, although the `--version` is correct as well as what's in the web UI. This should fix that.
> build(cmake): set CMAKE_PROJECT_VERSION from PROJECT_VERSION

- src/main.cpp
This allows us to terminate gracefully when console window is closed. Mostly relevant for portable builds.
> Handle CTRL_CLOSE_EVENT on Windows

- .codeql-prebuild-cpp-Linux.sh
- .dockerignore
- .github/workflows/CI.yml
- cmake/packaging/linux.cmake
- docker/debian-bookworm.dockerfile
- docker/fedora-39.dockerfile
- docker/fedora-40.dockerfile
- docker/ubuntu-22.04.dockerfile
- docker/ubuntu-24.04.dockerfile
- scripts/linux_build.sh
This is an attempt to have a single build script for all the distros we provide packages for, excluding those with a build spec like PKGBUILD or flatpak.
Skipping documentation update, as that will be handled in #2932 
TODO:
> build(linux): add common build script

- cmake/compile_definitions/common.cmake
This is an actual "fix" for https://github.com/LizardByte/Sunshine/pull/2919 and other places where the warning cannot be resolved easily (https://github.com/FrogTheFrog/Sunshine/actions/runs/10126414768/job/28003050801).
There is a bug for GCC 12 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105651) which unfortunately is used by flatpak.
Since we are treating all warnings as errors, such a bogus warning will prevent Sunshine from compiling. In some cases it is impossible to avoid this warning as it happens somewhere outside of Sunshine's code, like GTest:
```
test_sunshine.dir/unit/test_display_device.cpp.o -c /run/build/sunshine/tests/unit/test_display_device.cpp
In file included from /usr/include/c++/12.2.0/string:40,
from /usr/include/c++/12.2.0/bitset:47,
from …
```
> build(linux): disable GCC 12 Wrestrict warning

- src/platform/windows/display_base.cpp
Previously we tested all of them (D3D11CreateDevice() and everything) and selected the last one.
Should marginally reduce time spent on encoder probing and remove confusing lines from the log where unrelated outputs were mentioned.
> fix(windows): properly break on the first matching DXGI output

- .github/ISSUE_TEMPLATE/bug-report.yml
Apple users with Apple Silicon had only third-party GPU vendor options, added Apple Silicon to avoid confusion.
> chore(issue-template): add Apple Silicon to GPUs

- src/logging.cpp
- src_assets/common/assets/web/index.html
Include milliseconds in logging timestamps and improve formatting while at it.
Should now give better idea how long individual steps take (shader compilation, encoder probing, etc).
Before
```
[2024:08:04:22:33:15]: Info: Sunshine version: 0.0.0.f8b0be1e
```
After
```
[2024-08-04 22:33:15.623] Info: Sunshine version: 0.0.0.f8b0be1e
```
> feat(logging): include milliseconds in timestamps

- tests/CMakeLists.txt
Resolves a couple of errors specific to msys.
> tests(windows): prefer static libraries

- src/video.cpp
We didn't indicate what encoder we were probing so the log looked *very* confusing.
```
[2024-08-05 13:34:51.829] Info: Creating encoder [hevc_nvenc]
[2024-08-05 13:34:51.829] Info: Color coding: SDR (Rec. 709)
[2024-08-05 13:34:51.829] Info: Color depth: 10-bit
[2024-08-05 13:34:51.830] Info: Color range: JPEG
```
> fix: print encoder name to info log during creation

- src/platform/linux/audio.cpp
Don't set pulseaudio buffer size.
We only care for fragment size anyway and don't pace consumption.
Should hopefully fix audio cracking in pipewire-pulseaudio.
- Fixes #2988
> fix(linux/audio): don't set pulseaudio buffer size

- src/platform/linux/cuda.cpp
Please excuse the code. Basically I had a suspicion that the 'ctx_t' helper in the NvFBC code path was releasing the context early and that the exhaustion of session handles was causing the "can only reconnect 2-4 times" before it fails to reconnect bug. #2974 
So I tried a dirty workaround of binding the context before destroying the session handle. And guess what, it works. 
I also added some error logs around when it binds and unbinds the context to confirm my suspicions. 
Really the whole code needs to be reworked to ensure the ctx_t class remains in scope correctly. But that's a little above my skill level. 
Fixes #2974
> fix(linux): ensure NvFBC capture works after multiple sessions

- .github/workflows/CI.yml
Fix brew link issue in macOS-13 runners.
> build(macos): fix error in macos-13 build

- src/platform/windows/display_vram.cpp
- src/video.cpp
- src/video.h
Skip particular QSV 4:4:4 codecs bypassing ffmpeg.
> fix(win/qsv): skip unsupported 4:4:4 codecs

- packaging/linux/AppImage/AppRun
- packaging/linux/Arch/sunshine.install
- src_assets/linux/misc/postinst
#2606 missed several places where we need to reload uhid rules, so DS5 emulation is broken after installation on most distros.
> fix(packaging): apply udev rules for uhid

- cmake/packaging/linux.cmake
`setcap` doesn't work with atomic desktops.
See:
- #2977
- #2972
> fix(packaging/rpm): setcap with filelist

- cmake/packaging/linux.cmake
- cmake/packaging/windows.cmake
Use directory junction instead of copy in the build directory during cmake configure on Windows.
This prevents work-in-progress shaders getting overwritten without any confirmation.
> feat(cmake): use symlink/junction for shaders in build dir

- docker/archlinux.dockerfile
- docker/clion-toolchain.dockerfile
- docker/debian-bookworm.dockerfile
- docker/fedora-39.dockerfile
- docker/fedora-40.dockerfile
- docker/ubuntu-22.04.dockerfile
- docker/ubuntu-24.04.dockerfile
> build(docker): update dockerfiles

- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
- tests/unit/platform/test_common.cpp
Enable low latency mode for AMD by setting the appropriate environment variable. https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30039
This adds back in some helper functions to set env variables that were removed in https://github.com/LizardByte/Sunshine/pull/3059 ... although it was in the tests code before.
> fix(linux): enable lowlatency mode for AMD

- src/nvhttp.cpp
The upstream `SimpleWeb::Server<SimpleWeb::HTTPS>` implementation doesn't ensure the TLS session is torn down gracefully which leads to unexpected TCP RST packets from Sunshine to the client when using TLS v1.3 and setting `close_connection_after_response` (which NvHTTP does). Depending on the client, this spurious TCP RST can lead to the HTTPS request failing even though all the required data did end up on the wire. The `QSslSocket` implementation in Qt seems to be particularly susceptible to the issue, causing computers to constantly bounce between online and offline.
Ideally this would be fixed upstream, but the way that the classes are structured with `SimpleWeb::ServerBase` doesn't provide a straightforward place to insert this code (`ServerBase` has no clue about any TLS stuff). …
> fix(nvhttp): wrap TLS socket to ensure graceful closure

- src/network.cpp
- src/network.h
- src/platform/linux/publish.cpp
- src/platform/macos/publish.cpp
- src/platform/windows/publish.cpp
- tests/unit/test_network.cpp
All platform mDNS implemenations currently hardcode the instance name to `Sunshine`. This causes reliable name collisions during mDNS registration when more than one Sunshine host is running on the same network. The collision is eventually resolved by appending a number to the name, but this is unnecessary work and delay for nothing. We should just register using our hostname as the instance name most other mDNS services do.
> fix(mdns): don't hardcode mDNS instance name

- src/platform/common.h
macOS build seems to be broken because of boost headers, linux seems to be working as is, but since the forward headers issue is windows only, I think we should handle it as a Windows only flag.
- Fixes #3052
- Fixes #3098
> fix(macos/linux): import boost headers normally

- src/platform/common.h
- src/platform/windows/input.cpp
Invoking `platf::supported_gamepads()` during static initalization of `config_t` was leading to misleading warnings in the logs indicating lack of ViGEmBus. We should handle the `!input` case specially like we do for the `inputino` implementation.
> fix(win/input): fix false warnings about missing ViGEmBus

- src/platform/linux/misc.cpp
Fix typo reported here: https://github.com/LizardByte/Sunshine/commit/bf92fda969367d9dbf427db6669ec012e86b7376#r146064860
> fix(linux): use correct value for AMD_DEBUG environment variable

- src/platform/windows/display_vram.cpp
- src_assets/windows/assets/shaders/directx/convert_yuv420_packed_uv_type0_vs.hlsl
- src_assets/windows/assets/shaders/directx/convert_yuv420_packed_uv_type0s_ps.hlsl
- src_assets/windows/assets/shaders/directx/convert_yuv420_packed_uv_type0s_ps_linear.hlsl
- src_assets/windows/assets/shaders/directx/convert_yuv420_packed_uv_type0s_ps_perceptual_quantizer.hlsl
- src_assets/windows/assets/shaders/directx/convert_yuv420_packed_uv_type0s_vs.hlsl
- src_assets/windows/assets/shaders/directx/convert_yuv420_planar_y_vs.hlsl
- src_assets/windows/assets/shaders/directx/convert_yuv444_packed_vs.hlsl
- src_assets/windows/assets/shaders/directx/convert_yuv444_planar_vs.hlsl
- src_assets/windows/assets/shaders/directx/cursor_vs.hlsl
- src_assets/windows/assets/shaders/directx/include/base_vs.hlsl
- src_assets/windows/assets/shaders/directx/include/base_vs_types.hlsl
- src_assets/windows/assets/shaders/directx/include/convert_yuv420_packed_uv_ps_base.hlsl
Don't offload math to texture sampler when subsampling chroma together with downscaling.
Fixes broken chroma when downscaling.
This makes chroma consistent with luma when downscaling, but luma itself is broken if the factor is >2x and half-broken with lesser factors (inconsistent filter radius, linear texture sampler alone can't be used for proper downscaling).
I'm hesitant to touch upscaling because of the potential performance hit.
Before
After
> fix(win/video): don't offload chroma subsampling math to texture sampler when downscaling

- src/platform/windows/input.cpp
When the client couldn't normalize their keyboard event to a US English layout, we don't know for sure which scan code to use in the keyboard event. Instead of assuming the non-normalized event is from a US English layout, make a better guess by using the host's current keyboard layout. As before, users can still disable the "Always Send Scancodes" option to send the VK code, which will always be correct but has reduced game compatibility.
Fixes #2463
> fix(win/input): use active keyboard layout for non-normalized key events

- package.json
- src_assets/common/assets/web/Navbar.vue
This PR does the following:
- Use `shared-web` package for `discord.js` instead of using the online version.
- Moves vite packages to dev dependencies.
- Removes `bootstrap` and `fontawesome` as they are dependencies of `shared-web` (reduces dependabot PRs)
- Removes `@popperjs/core` as it is unused?
Todo:
> feat(web): use shared-web

- docs/Doxyfile
- docs/configuration.js
- docs/configuration.md
- docs/doc-styles.css
- Remove URLS from markdown headings, as they don't work with the side TOC. See screenshot.
- Fix heading name for `keybindings`
- Add input field for host address and port, allowing dynamic urls.
Todo:
Preview: https://lizardbyte--3163.org.readthedocs.build/projects/sunshine/en/3163/md_docs_2configuration.html
> docs(configure): auto generate open urls

- packaging/macos/Portfile
Previously this resolved to: `/opt/local/bin/{Sunshine}`
I have not actually figured out how to get correct permissions for Screen Recording with sunshine in launchd, but at least this now runs the program.
> fix(macos/packaging): MacPorts startupitem.executable path

- cmake/compile_definitions/common.cmake
Sunshine will still compile with the vendored headers, even if the system has its own ffmpeg headers installed.
Fixes #3169.
> build(cmake): Prioritize vendored includes over system-wide

- .codeql-prebuild-cpp-Windows.sh
- .github/workflows/CI.yml
Use boost from source.
- Resolves #3230
> ci(windows): use boost from source

- .github/workflows/CI.yml
Discovered in #3231, the coverage generation may fail when building boost from source.
- Fixes #3222 (probably)
> test(coverage): ignore _deps directory

- scripts/linux_build.sh
`dnf group install` command was missing `sudo`.
> build(script): fix missing sudo for dnf group install

- src/platform/macos/input.cpp
Pull request #2550 fixed the macOS mouse input mode but broke the touchscreen mode in the process : tapping anywhere on the screen doesn't work anymore. Looking at the changes it seems the [CGWarpMouseCursorPosition(location)](https://github.com/LizardByte/Sunshine/pull/2550/files#diff-730f675bbeb37990b8260140134248992b0606fd99f28ba3c9efea74868eb9e9L345-L347) was removed in `post_mouse()`, restoring it fixes the touchscreen issue. From my testing mouse input mode is unaffected by this change, but I do not have access to Minecraft Java Edition or Tomb Raider as described in https://github.com/LizardByte/Sunshine/pull/2550.
> fix(macos): Touch input broken

- src/platform/windows/display_base.cpp
- tools/ddprobe.cpp
Enhances the ddprobe utility to test to see if frames can be captured and that they are also not empty frames. If one of the 10 frames captured is not empty, it will return back successful. Previously it was only testing to see if it can be duplicated, but would fail on capturing frames which would cause Sunshine to pick the wrong GPU.
N/A
- Fixes #2203 
- Fixes #2076
- Fixes #2875
- Fixes #2078
- Fixes #1632
> fix: automatic selection for hybrid GPU and IDDSampleDriver users

- .github/workflows/CI.yml
- README.md
macOS-12 doesn't support some newer c++ syntax, probably time to drop it. From my research many are dropping support for it in November (~1 month from now).
> chore(macos)!: drop monterey support

- src/confighttp.cpp
Sort apps alphabetically.
Original plan was to sort them via the webUI; however the it attempted to delete/edit the incorrect apps due to the change in index order. So opted to alphabetize the `apps.json` before saving the file.
- Resolves https://github.com/orgs/LizardByte/discussions/489
> feat(apps): order apps alphabetically

- .codeql-prebuild-cpp-Windows.sh
- .github/workflows/CI.yml
- docs/building.md
- src/httpcommon.cpp
See: https://github.com/msys2/MINGW-packages/issues/21028
- Fixes #2722
> build(deps): migrate from curl to curl-winssl on Windows

- .github/workflows/CI.yml
Skip attempting to update brew tap when running workflow in forks.
> ci(homebrew): don't update tap for forks

- src/video.cpp
Integrate the FFmpeg update from https://github.com/LizardByte/build-deps/pull/359 along with the Sunshine changes required to support them.
> build(deps): update to FFmpeg 7.1

- src/platform/windows/display_wgc.cpp
Workaround for build break due to https://github.com/msys2/MINGW-packages/issues/22160
> build(mingw): work around broken windows.foundation.h

- docs/Doxyfile
- packaging/linux/Arch/PKGBUILD
- packaging/sunshine.rb
- src/config.cpp
Manually update build-deps (ffmpeg), and:
- Workaround build error for AMF
- Revert #3286
- Disable docs for some builds (ArchLinux and brew)
- Closes #3275
- Fixes #3273
> build(deps): bump third party/build-deps from `1977d9c` to `8c7caa1`

- packaging/sunshine.rb
Fixes brew Ubuntu build, by changing default behavior of boost linking (static linking seems to be broken at the moment). Also install boost from brew, instead of relying on fetch content.
> build(homebrew): fix boost linking

- src/platform/windows/display_base.cpp
This fixes a display capture initialization performance regression from #3002 that was reported in https://github.com/moonlight-stream/moonlight-common-c/issues/93#issuecomment-2400987935. The lines to set `set_gpu_preference` were accidentally refactored away. This caused ddprobe.exe to run every time that display capture initialized rather than just once.
> fix(display): fix logic to remember ddprobe already ran

- src/platform/windows/audio.cpp
When the Moonlight "Mute host PC speakers" option is selected, Sunshine will change the audio device to Steam Speakers. The changed block of code cycles through some settings in order and stops on the first one found, which happens to be the 32-bit signed int format. What we really want to happen is to have 24-bit as the highest supported format because this mode won't unset an existing spatial audio mode (Atmos for Headphones only supports 16 and 24-bit at <= 48k. 
This patch simply removes the F32 and S32 checks for stereo. F32 isn't supported by Steam Speakers, but S32 is and that's the one we want to avoid.
> fix(audio/windows): don't set virtual speakers higher than 24-bit mode

- src/video.cpp
Hyper-V GPU Paravirtualization (with https://github.com/jamesstringerparsec/Easy-GPU-PV) causes some strange behavior in DXGI DDA where `AcquireNextFrame()` will succeed (giving us a black frame) then `ReleaseFrame()` will fail with `DXGI_ERROR_ACCESS_LOST` immediately afterwards (which is turned into `capture_e::reinit`). DDA is left in a strange state after this happens, where further calls to _both_ `AcquireNextFrame()` and `ReleaseFrame()` fail with `DXGI_ERROR_INVALID_CALL` (indicating both that there is and is not a pending frame to release).
Capture does seem to eventually recover and stabilize (when DWM renders a fresh frame?), but this pattern of pushing a frame then immediately failing with `capture_e::reinit` causes the encode thread to break into the reinit loop without …
> fix(video): encode at least one frame before capture reinit

- cmake/dependencies/common.cmake
- cmake/packaging/linux.cmake
- docker/clion-toolchain.dockerfile
- packaging/linux/Arch/PKGBUILD
- packaging/linux/fedora/Sunshine.spec
- packaging/sunshine.rb
- scripts/linux_build.sh
VDPAU is a decode-only API, so we have no foreseeable need for that in Sunshine.
> build(deps): remove unused dependency on libvdpau

- docs/app_examples.md
- docs/guides.md
Add a new guide for how to enable autostart for Sunshine without enabling autologin. This is the significantly revised document from my previous PR #3200 
This guide works by first starting a system service that creates an SSH tunnel to the localhost to start sunshine, similar to Eric Dong's guide on Remote SSH headless setup, but we're SSHing from the local machine instead of a remote machine so you don't need to leave the moonlight client to get streaming setup. After you login to SDDM, there is a second user service that kills the first system service, and runs sunshine with the permissions of the graphical desktop; this is to fix the issues I encountered in #3200 where pipewire was not working, and the system tray icon did not appear.
This guide also gives some non-sunshine related …
> docs(guides): add autostart guide

- docs/getting_started.md
- packaging/linux/flatpak/dev.lizardbyte.app.Sunshine.metainfo.xml
Corrected documentation of startup calls for Linux+Flatpak: I have removed `$(pactl info | awk '/Server String/{print$3}')` and replaced it with `$(id -u $whoami)`. This should allow Sunshine to find the Pulse audio server also on Linux installations that are not English.
- Fixes #3261
- Fixes #2840
- Fixes #2839
> docs: improve flatpak start commands

- src_assets/common/assets/web/Navbar.vue
- src_assets/common/assets/web/apps.html
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/index.html
- src_assets/common/assets/web/locale.js
- src_assets/common/assets/web/password.html
- src_assets/common/assets/web/pin.html
- src_assets/common/assets/web/template_header.html
- src_assets/common/assets/web/troubleshooting.html
- src_assets/common/assets/web/welcome.html
- vite.config.js
These changes allow to use sunshine webui after reverse proxy with subpath.
- Resolves #3008
> fix: Reverse Proxy support

- .gitmodules
- cmake/compile_definitions/linux.cmake
- tests/CMakeLists.txt
- Bump googletest to v1.15.2 and change tracking branch to main as googeltest doesn't seem to update release branches
- Fixes for .gitmodules file
- Remove an extra line break in cmake
- Improve error message for cuda not found.
> chore(various): tedious updates

- docs/configuration.md
- src/config.cpp
- src/config.h
- src/network.cpp
- src/network.h
- src/nvhttp.cpp
- src/rtsp.cpp
- src/rtsp.h
- src/stream.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/General.vue
This PR reworks session handling to be more flexible in the following cases:
- A user has existing streaming sessions and would like to connect a new client. This would fail with the default value of `channels` prior to this PR and the user would need to go manually disconnect that session.
- A user left a stream idle on another device and would like to quit the game they are streaming. That would fail until all active sessions have disconnected (and apprently in some other situation where session management broke: https://github.com/moonlight-stream/moonlight-qt/issues/1279)
This removes the `channels` configuration options and allows users to connect as many session as they want (up to the arbitrary limit of 128). They can also now quit the running app (which also disconnects all …
> feat(stream)!: remove limit on concurrent sessions and allow quitting apps with active sessions

- src/video.cpp
Disable padding OBU insertion in AV1 bitstreams from FFmpeg NVENC to match the standalone NVENC implementation and avoid wasted bandwidth and compatibility issues with Snapdragon 8 Gen 3 decoders.
Fixes #3331
> fix(nvenc): disable filler data in AV1 bitstream

- src/crypto.cpp
- src/nvhttp.cpp
Remove dependency on functions that were deprecated in OpenSSL 3.0. No behavior changes at runtime (`SSL_get_peer_certificate` is defined to be an alias of `SSL_get1_peer_certificate()`).
The missing `openssl/rsa.h` include is used for `EVP_PKEY_CTX_set_rsa_keygen_bits()`. `openssl/rsa.h` was pulled in indirectly via `openssl/pem.h` when deprecated APIs are enabled.
> fix(openssl): fix build with OPENSSL_NO_DEPRECATED

- cmake/dependencies/common.cmake
- docs/Doxyfile
- src/cbs.cpp
Use updated submodule, which had a few breaking changes.
> build(deps): update dependency and paths for build-deps submodule

- docs/Doxyfile
- docs/api.md
- docs/performance_tuning.md
- docs/troubleshooting.md
- src/confighttp.cpp
- src_assets/common/assets/web/apps.html
Adds clearer API documentation. This closes out an item in the roadmap.
> docs(api): improve api documentation

- packaging/sunshine.rb
Moving binary after build and adding codesign for macOS as per issue #3340 
Issue #3340
> fix(homebrew): codesign binary only on Intel macOS

- docs/configuration.md
- src/config.cpp
- src/config.h
- src/platform/common.h
- src/platform/linux/vaapi.cpp
- src/video.cpp
- src/video.h
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/ContainerEncoders.vue
- src_assets/common/assets/web/configs/tabs/encoders/VAAPIEncoder.vue
- src_assets/common/assets/web/public/assets/locale/en.json
This PR introduces a configuration option for AMD GPUs using the VAAPI encoder to strictly enforce frame bitrate limits (rc_buffer_size) to balance the concerns of video quality (#2864) and frame bitrate excursions (#2788). Intel GPUs appear fine with VBR mode, so this option can be ignored for them.
This PR sets the default to the v0.23.1 (and pre-#2821) behavior which is to _not_ enforce a strict RC buffer size. Even though this isn't ideal for packet loss reasons, the immediate symptom of large frames exceeding the FEC maximum in #2788 was resolved separately by #2803 anyway.
Fixes #2864
> feat(vaapi): add option to enable strict enforcement of frame size

- vite.config.js
This commit addresses a situation where the user clones the Sunshine
directory in a location such that an ancestor of the repository is a
symlink. For example, imagine that the `~/git` directory is a symlink
to the `~/Documents/git` directory. Further imagine that the user clones
Sunshine into `~/git/Sunshine`. In this setup, attempting to build
the web-ui will fail with a series of incredibly cryptic error messages,
which look like this:
RollupError: The "fileName" or "name" properties of emitted chunks
and assets must be strings that are neither absolute nor relative
paths, received "../../../../../../Documents/git/Sunshine/src_assets/common/assets/web/password.html".
This seems to occur because vite isn't aware that `Documents/git` and
`git` are actually the same directory as each …
> build(vite): fix assets directories with symlinks present

- src/platform/macos/display.mm
- src/platform/macos/misc.h
- src/platform/macos/misc.mm
Currently, if Sunshine has not yet been granted the screen capture
permission, the program simply hangs indefinitely on startup when it
attempts to probe for usable encoders. This is not desirable because
it prevents testing and using all of the parts of Sunshine that do not
require the screen capture permission.
With this patch, the encoder probing will simply fail instead of
hanging indefinitely if Sunshine does not yet have the screen capture
permission.
Note that Sunshine already prints out an error message telling the user
that the screen capture permission is needed. The bug is that Sunshine
currently indefinitely hangs shortly after printing that message.
N/A
N/A
> fix(macos): prevent indefinite hanging if screen capture is not granted

- docs/Doxyfile
Building the Sunshine docs is currently agonizingly slow because it
generates many hundreds of dot graphs in serial, without any
parallelization.
This commits sets `DOT_NUM_THREADS` to 0, which causes `doxygen` to
determine on its own a reasonable level of parallelization, based on
the number of processors available on the system.
The speed difference with this change is incredibly dramatic. I haven't
performed particularly rigorous testing, but on my fairly weak laptop
building the docs after applying this patch takes about 35 seconds.
Without applying this patch, building the docs instead takes a
ridiculous 135 seconds. This is on an M1 machine with only 4 performance
cores and 4 efficiency cores. On a more powerful machine, the difference
will be even more marked.
Unless there's some …
> build(docs): parallelize generation of dot graphs

- docs/troubleshooting.md
This reverts commit 8810c5ccdd3327521eb41a1a17999d87095423b8.
Appears this was fixed with the latest nvidia drivers or KDE 6.2, not sure which, but it's probably good to clean this page up.
> docs(troubleshooting): Remove workaround for "blur" plugin in KDE

- docs/Doxyfile
Reverts LizardByte/Sunshine#3361
> build(docs): revert parallelize generation of dot graphs

- src/process.cpp
- src/rtsp.cpp
Remove permanent side-effect in `rtsp_server_t::clear(true)` that prevents RTSP server from accepting new connections. I have no idea why this was there, since the destructor of `rtsp_server_t` should handle teardown of the `io_context`.
Also a drive-by fix for an unhandled exception I saw when testing this scenario on Linux due to us calling `terminate()` after we had already successfully terminated the process group.
Fixes #3371
> fix(rtsp): fix RTSP timeout after quitting an app

- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/process.cpp
We were leaking detached child processes on Mac and Linux because we are expected to still wait on those with `waitpid()` in order to reap their entry in the process table. We will now do that when `proc_t::running()` is called (which happens regularly while streaming and periodically when clients poll for server info). This isn't a perfect solution but it's much better than the current situation today where all detached processes become zombies.
We were also leaking file descriptors into detached processes which could cause our log files and sockets to persist longer than expected.
Fixes #3378
> fix(process): avoid leaking zombies and fds in detached processes

- packaging/sunshine.rb
libcurl is no longer linking properly on macOS under homebrew.
- Fixes comment https://github.com/LizardByte/Sunshine/issues/3180#issuecomment-2463975526
> build(macos): fix libcurl linking

- cmake/targets/common.cmake
Fixed the issue that generating cmake configuration on Windows platform failed after BUILD_TESTS was set to OFF.
Error message:
```shell
CMake Error at cmake/targets/common.cmake:116 (set_source_files_properties):
set_source_files_properties given non-existent DIRECTORY
```
None
None
> fix(cmake): configuration generation fails when BUILD_TESTS is OFF

- .github/ISSUE_TEMPLATE/bug-report.yml
- README.md
- docs/troubleshooting.md
- gh-pages-template/index.html
- Resolves #3338
- Resolves #2530
- Resolves #3351
- Closes #3395
> docs: various updates

- src/nvhttp.cpp
- src/rtsp.cpp
- src/stream.cpp
Boost 1.87 removes `asio::io_service`. See: https://github.com/boostorg/asio/issues/110
These changes seem compatible with 1.86 and 1.87 so technically we don't need to update to 1.87.
> build(deps): fix boost 1.87 compatibility

- .github/workflows/ci-docker.yml
Something changed with how artifacts are extracted from the docker builds. This fixes that.
These changes need to also be added to the `.github` repo.
> build(docker): fix docker artifacts

- packaging/linux/fedora/Sunshine.spec
Fedora copr builds are failing after an update to https://copr.fedorainfracloud.org/coprs/slaanesh/cuda-gcc
Additionally, cuda has been updated.
> build(copr): fix build

- docs/Doxyfile
- src/config.cpp
Using the INCLUDE_PATH causes errors when building in some cases.
> docs(doxygen): remove INCLUDE_PATH from config

- src/nvenc/nvenc_base.cpp
- src/rtsp.cpp
- src/video.h
Context in https://github.com/TheElixZammuto/moonlight-xbox/issues/117
This type of degradation can be fixed on nvidia cards by implementing intra-refresh.
I do not have an nvidia card so I wasn't be able to test, but this change has been validated by the commenters in the issue above using a custom Sunshine build made by me and by other forks of Sunshine made by other people, and it seems to fix the issue.
This change is completely opt-in by the client, so this change should only apply to the Xbox/UWP Client
Related to:
**moonlight-xbox:** https://github.com/TheElixZammuto/moonlight-xbox/pull/155
**moonlight-common-c:** https://github.com/moonlight-stream/moonlight-common-c/pull/97
https://github.com/TheElixZammuto/moonlight-xbox/issues/117
> fix(nvenc): Enable opt-in client refresh by client

- cmake/packaging/windows.cmake
Typo in GUI of removing closing bracket in Virtual Gamepad removal window.
> chore(installer/windows): remove parentheses in Virtual Gamepad removal prompt

- src_assets/windows/assets/shaders/directx/include/base_vs.hlsl
Replace modulo operation with bitwise operation to optimize performance and remove warning messages on some GPUs
> fix(shaders/directx): replace modulus with bitwise operator

- src/platform/macos/av_video.m
Fixes the following compiler warnings on macOS:
```
src/platform/macos/av_video.m:35:13: warning: incompatible pointer types initializing 'NSScreen *' with an expression of type 'NSArray<NSScreen *> * _Nonnull' [-Wincompatible-pointer-types]
35 |   NSScreen *screens = [NSScreen screens];
|             ^         ~~~~~~~~~~~~~~~~~~
src/platform/macos/av_video.m:36:3: warning: collection expression type 'NSScreen *' may not respond to 'countByEnumeratingWithState:objects:count:'
36 |   for (NSScreen *screen in screens) {
|   ^  
```
> fix(capture/macos): fix implicit conversion of NSArray

- docs/configuration.md
- src/config.cpp
- src/config.h
- src/platform/windows/display_base.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/AudioVideo.vue
- src_assets/common/assets/web/configs/tabs/audiovideo/DisplayDeviceOptions.vue
- src_assets/common/assets/web/public/assets/locale/en.json
At the moment `ddprobe` does not always work (see https://github.com/LizardByte/Sunshine/pull/3414). This PR allows to manually specify the GPU preference instead of relying on the `ddprobe`.
> feat(ddprobe): allow to manually specify gpu preference

- docs/Doxyfile
- docs/api.js
- docs/api.md
- src/confighttp.cpp
- Return 400 status code on config API errors
- Add `default_resource` for requests that are not `GET`
- Remove trailing commas in API examples
- Clarify how `index` works when saving an app
- Change xml responses to json
- Add grouped tab code examples to API docs
TODO:
```
>curl -u user:pass -X DELETE -k https://localhost:47990/api/apps/5000
{
"status": "true"
}
```
Note: existing check was useless since it could never actually be fired ( < 0 is not possible due to the regex of the endpoint), instead changed it to a clamp and checked the upper bounds.
- Fixes #3384
> fix(confighttp): do not return 200 on errors

- .github/workflows/CI.yml
- cmake/prep/options.cmake
- src/platform/windows/display.h
- src/platform/windows/display_vram.cpp
- tests/CMakeLists.txt
- tests/unit/test_video.cpp
For the longest time, I thought DDA just didn't work on the Microsoft Basic Display Adapter. It turns out that it works fine, but we're passing a D3D11 device flag that it doesn't support so we fail to create the D3D11 device with `DXGI_ERROR_UNSUPPORTED`. I reviewed several DDA samples online (including [the official Microsoft one](https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/DXGIDesktopDuplication/README.md)) and none of them set this `D3D11_CREATE_DEVICE_VIDEO_SUPPORT` flag.
It's not completely clear what `D3D11_CREATE_DEVICE_VIDEO_SUPPORT` even does exactly, but assuming it's required for the device where we do video encoding/processing, let's just set it on the device that FFmpeg uses for encoding.
> fix(capture/windows): fix capture when using the basic render driver

- README.md
- cmake/packaging/windows.cmake
- docs/contributing.md
- packaging/linux/flatpak/README.md
- packaging/sunshine.rb
- src/platform/linux/kmsgrab.cpp
- src_assets/common/assets/web/apps.html
This PR updates hrefs to docs, mainly so they will continue to work with the doxygen version of the docs.
This PR should not be merged until right before the next stable release.
Additionally, directly before this is merged, we need to update a setting on readthedocs, to not put docs under an `en` subdirectory (also for the `.github` repo).
> docs(hrefs): update readthedocs hrefs

- cmake/compile_definitions/windows.cmake
- cmake/dependencies/common.cmake
- cmake/dependencies/windows.cmake
This PR will check for MinHook during cmake configure step instead of failing during the build step.
PLATFORM_LIBRARIES is also listed alphabetically.
> build(cmake): check for MinHook during configure

- cmake/dependencies/windows.cmake
> fix(cmake/windows): static link MinHook

- src_assets/common/assets/web/Checkbox.vue
- src_assets/common/assets/web/apps.html
Inverse global prep values for apps.
> fix(checkbox): inverse global prep values for apps

- src/system_tray.cpp
- src/system_tray.h
Add button to reset display device settings on Windows. Also, remove the callbacks from the header file (where they should not be located in my opinion) and into cpp file.
Also check https://stackoverflow.com/questions/4422507/how-are-unnamed-namespaces-superior-to-the-static-keyword regarding the anonymous namespace.
> feat(tray): add button to reset display device settings on Windows

- src/httpcommon.cpp
- src/httpcommon.h
- tests/unit/test_httpcommon.cpp
Fixes most of the sonarqube warnings on httpcommon.  Was able to fix one of the security issues regarding curl_easy_init, but the other one does not want to go away.  Since it's a false alarm, I added the no sonar comment to prevent it from affecting the security score.
> fix(httpcommon): sonarqube warning cleanup

- .github/workflows/update-flathub-repo.yml
- packaging/linux/flatpak/dev.lizardbyte.app.Sunshine.metainfo.xml
Per https://github.com/flathub-infra/website/issues/4527#issuecomment-2612393675 the indentation in the flatpak metainfo file is incorrect. This happens when doing a replace during the final release stage.
> ci(packaging): fix flatpak metainfo

- src/display_device.cpp
- src/display_device.h
- src/nvhttp.cpp
- src/video.cpp
Since Windows 11 24H2 update it seems that Windows can get into a broken state where probing encoders (or likely also just using DXGI API) will break Sunshine in such a way that it cannot start any stream nor the libdisplaydevice is able to access the windows API to do any changes.
While this is not a perfect solution to the problem, the user can at least do something (plug or unplug displays) or libdisplaydevice could try restoring previous config once the API is available.
- Resolves https://github.com/LizardByte/Sunshine/issues/3580 (due to libdd bump)
> fix(video): prevent encoder probing with no active displays

- src/display_device.cpp
- src/display_device.h
- src/video.cpp
It is possible that if there are no devices reported, that the API is not functioning properly. Make sure not to prevent encoding in such cases if we can't tell.
> fix(video): allow encoder probing when there are no devices at all

- docs/configuration.md
- src/config.cpp
- src/config.h
- src/stream.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/audiovideo/DisplayDeviceOptions.vue
- src_assets/common/assets/web/public/assets/locale/en.json
This adds the option to revert the display configuration changes on disconnect of the client instead of waiting for the termination of the session or app. It's set off by default as I expect some applications don't always play well with a resolution change while active and many users may just not want this behavior by default.
This was a feature I found a use for and figured some others may as well. Happy to make any changes as desired!
None
> feat(display): Add revert display config on disconnect option

- src_assets/common/assets/web/apps.html
- src_assets/common/assets/web/password.html
- src_assets/common/assets/web/pin.html
- src_assets/common/assets/web/troubleshooting.html
- src_assets/common/assets/web/welcome.html
I forgot to check the UI for string boolean values in https://github.com/LizardByte/Sunshine/pull/3544. This PR address that, and also changes from loose comparison to strict comparison in several places.
- Fixes #3624
> fix(ui): properly handle boolean json responses

- .github/workflows/ci-docker.yml
- scripts/linux_build.sh
ARM builds fail when using ubuntu-24.04 images, probably due to running out of space issues. It was discovered their was a segmentation fault occurring at random times. For now the runner is being rolled back to ubuntu-22.04.
> ci(docker): fix debian arm builds

- crowdin.yml
- docs/configuration.md
- scripts/_locale.py
- src/config.cpp
- src_assets/common/assets/web/configs/tabs/General.vue
Add language settings for Traditional Chinese. Also need to enable this language in crowdin.
> chore(l10n): Add language settings for Traditional Chinese

- .github/workflows/CI.yml
Adjust flatpak matrix to build aarch64 on new ubuntu arm runner.
> ci(flatpak): build aarch64 on arm architecture

- gh-pages-template/.readthedocs.yaml
This PR adds the ability to preview website builds by using Read the Docs.
> ci(gh-pages): preview website for PR builds in RTD

- packaging/linux/flatpak/modules/xvfb/xvfb.json
This moves a few xvfb-run dependencies to LizardByte hosted mirrors.
> fix(packaging/flatpak): move xvfb modules to LizardByte mirrors

- packaging/linux/flatpak/modules/xvfb/xvfb.json
This PR moves more xvfb-run dependencies (on Flatpak) to git sources and mirrors on LizardByte-infrastructure org.
> fix(packaging/flatpak): move more xvfb modules to LizardByte mirrors

- src_assets/common/assets/web/config.html
I have added a 1rem margin between the Save and Apply buttons with Bootstrap's `mr-3` class.
No specific issue closed. I can make one if necessary for PR acceptance.
> style(Web UI): Add 1rem margin between Save and Apply buttons for better UI/UX

- src/config.cpp
- src/main.cpp
The config was parsed before logging was initialized. The ideal case is that it's parsed after logging is initialized so it can be included when users submit logs in bug reports or when asking for support.
TODO:
```
[2025-03-29 18:32:04.747]: Info: Sunshine version: 0.0.0.868eb8054cb658fd5412cc3a1d6d4be19d3c83cc
[2025-03-29 18:32:04.748]: Info: Package Publisher: LizardByte
[2025-03-29 18:32:04.748]: Info: Publisher Website: https://app.lizardbyte.dev
[notify_pre_releases] -- [enabled]
[min_fps_factor] -- [30]
[2025-03-29 18:32:04.748]: Info: Get support: https://app.lizardbyte.dev/support
```
> fix(config): parse config after logging initialized

- src/config.cpp
> fix(config): fix parse error when list ends on last line of config file

- cmake/dependencies/Boost_Sunshine.cmake
- cmake/dependencies/nlohmann_json.cmake
- tools/CMakeLists.txt
> build(cmake): update policies

- docs/getting_started.md
- packaging/linux/fedora/Sunshine.spec
- packaging/linux/fedora/patches/f42/aarch64/01-math_functions.patch
- packaging/linux/fedora/patches/f42/x86_64/01-math_functions.patch
Enable Fedora 42. The cuda compatibility package was also removed from F40-41 builds as it isn't actually necessary.
- Fixes https://github.com/orgs/LizardByte/discussions/677
> build(linux): enable fedora 42

- .codeql-prebuild-cpp-Windows.sh
- .codeql-prebuild-cpp-macOS.sh
- .github/workflows/CI.yml
- cmake/dependencies/Boost_Sunshine.cmake
- packaging/linux/flatpak/modules/boost.json
- packaging/sunshine.rb
Boost 1.88 fails builds due to missing `boost::process::v1`. For now, pin to 1.87.
> build(deps): pin boost to 1.87

- cmake/compile_definitions/windows.cmake
- src/platform/windows/windows.rc.in
I noticed this file was named incorrectly when looking at the languages api, and noticed there is rust detected as a language. I think it was because this file is named `.rs`.
https://api.github.com/repos/LizardByte/Sunshine/languages
> build(windows): fix resource file name

- cmake/compile_definitions/linux.cmake
- packaging/linux/fedora/Sunshine.spec
- packaging/sunshine.rb
- scripts/linux_build.sh
- src/platform/linux/wayland.cpp
- src/platform/linux/wayland.h
- src/platform/linux/wlgrab.cpp
This swaps out the wrl-export-dmabuf-unstable-v1 wayland protocol in favor of wlr-screencopy-unstable-v1. Since export-dmabuf is unsupported in newer versions of hyprland and other compositors it prevents the use of headless monitors.
- Fixes #2955
> fix(linux): headless monitors on wayland

- docs/Doxyfile
- docs/app_examples.md
- docs/awesome_sunshine.md
- docs/guides.md
This PR adds Awesome-Sunshine to Sunshine's docs.
> docs: add external documentation

- src/platform/windows/audio.cpp
fix(audio): set the bits-per-sample of Steam Streaming Speakers to 16-bit when the default audio device is 16-bit. This may help with audio glitches when enabling the virtual device.
Resolves https://github.com/orgs/LizardByte/discussions/682
> fix(audio): set the bits-per-sample of Steam Streaming Speakers to 16-bit when the default audio device is 16-bit

- gh-pages-template/index.html
FontAwesome is pretty limited in brand icons, so move to using simple-icons and bootstrap-icons.
> docs(website): use cdn for branded icons

- .github/workflows/ci-copr.yml
- .github/workflows/release-notifier-moonlight.yml
- .github/workflows/update-flathub-repo.yml
- .github/workflows/update-pacman-repo.yml
- scripts/linux_build.sh
Various workflow updates.
- Automerge PRs into pacman-repo and flathub
- Remove archive from pacman-repo before commit
- Use org vars for discord notifier
- Fix typos
- Update linux build script
> ci(workflows): minor fixes and updates

- docs/app_examples.md
- src_assets/linux/assets/apps.json
- src_assets/macos/assets/apps.json
- src_assets/windows/assets/apps.json
This will make example Steam Big Picture app automatically exit big picture mode on disconnect.
Note: only validated on Linux. Don't think that's really an issue, considering it's just a url change
Adds command from ["Command to quit steam big picture"](https://github.com/orgs/LizardByte/discussions/206) discussion
> fix(apps): exit steam big picture mode on session end

- .github/workflows/CI.yml
- .github/workflows/ci-docker.yml
Follow up from https://github.com/LizardByte/Sunshine/pull/3813
For some reason the GITHUB_TOKEN cannot read repository metadata with `contents: read` even though the job indicates that it can read metadata. I guess that the keys needed are available only to users with elevated permissions.
> ci(release): increase permission for job and bump actions

- .github/workflows/CI.yml
arm64 builds for flatpak and constantly failing, likely due to the maximize build space action.
> ci(flatpak): disable maximize build space for arm64

- docs/configuration.md
wlr now uses wlr-screencopy-unstable-v1 rather than reading from dma buf
Solves my comment for #2955
> docs(configuration): Update doc for wlr capture method

- docs/configuration.md
- src/audio.cpp
- src/config.cpp
- src/config.h
- src_assets/common/assets/web/configs/tabs/AudioVideo.vue
- src_assets/common/assets/web/public/assets/locale/en.json
So I use sunshine to stream my headless monitor to my laptop and use it as a second display, when doing so sunshine automatically changes the default audio sink to one created by sunshine, This is undesirable for my usecase, this pr adds an option disable_audio to the config which allows stopping streaming audio completely
None
> feat(audio): add an option to disable sound streaming

- .github/workflows/CI.yml
- package.json
- vite.config.js
> ci(codecov): add bundle analysis

- docs/app_examples.md
Add usage example of `displayconfig-mutter` to Gnome section on resolution change
N/A
Don't think there is one
> feat(docs): Suggest using displayconfig-mutter for Gnome Wayland resolution change

- scripts/linux_build.sh
This commit locks the gcc version to 14 instead of 15.x.x currently default on arch and also disables docs as they are currently broken on arch. This fixes arch builds
- Fix bug #3840
> build(linux): fix gcc version and disable docs for build on arch

- docs/getting_started.md
- src_assets/linux/misc/60-sunshine.rules
Adds `MODE="0660", GROUP="input"` to udev rules to improve input reliability on linux
- Closes https://github.com/LizardByte/roadmap/issues/12
> fix(linux/input): improve input rules

- src/stream.cpp
Instead of using now() when the RTP packet is created, use the earlier packet->frame_timestamp that we're already collecting for host latency stats. This timestamp is more accurate to when we captured the frame, and the same timestamp value is shared by all RTP packets that make up the same video frame. Duplicate frames without capture timestamps use the ratecontrol timestamp.
> fix(rtp): improve timestamp accuracy for video

- CMakeLists.txt
export compile_commands.json for diagnostics
None
> build(cmake): export compile commands

- src_assets/windows/misc/service/install-service.bat
- src_assets/windows/misc/service/uninstall-service.bat
This PR will make the installer "remember" the previous type of service start type on Windows. If the user selects to "auto start" during installation it will overwrite the previous service start type.
- Fixes https://github.com/LizardByte/Sunshine/issues/3469
- Closes https://github.com/LizardByte/Sunshine/pull/3867
> fix(installer/windows): remember service start type

- src_assets/windows/misc/service/install-service.bat
Changing quoting style in https://github.com/LizardByte/Sunshine/pull/3902 broke later usages of the variable that were not quoted.
- Fixes https://github.com/LizardByte/Sunshine/issues/3903
> fix(installer/windows): ensure service_bin is properly quoted

- cmake/packaging/windows.cmake
- cmake/packaging/windows_nsis.cmake
- cmake/packaging/windows_wix.cmake
Just moving NSIS packaging in preparation for https://github.com/LizardByte/roadmap/issues/76, which is probably needed for https://github.com/LizardByte/Sunshine/pull/3905 (or https://github.com/LizardByte/Sunshine/pull/3369)
> refactor(installer/windows): move nsis code

- .github/workflows/CI.yml
`windows-2019` runner is deprecated and will be removed by June 30, 2025.
> ci(windows): change runner from windows-2019 to windows-2022

- scripts/linux_build.sh
Updated the linux_build.sh file to include Ubuntu 25.04.
Set the cuda and gcc versions.
Tested and working.
Added the config for Ubuntu 25.04
Tested on my machine, so ymmv.
Alienware Area-51 R5
Intel i9-9820X
NVIDIA GeForce RTX 2080
Ubuntu 25.04
Gnome 48
Wayland
Kernel - Linux 6.14.0-15-generic
Note that I had to patch the cuda math headers as per [nvidia forum](https://forums.developer.nvidia.com/t/error-exception-specification-is-incompatible-for-cospi-sinpi-cospif-sinpif-with-glibc-2-41/323591)
- Resolves https://github.com/LizardByte/Sunshine/issues/3892
> build(linux): add Ubuntu 25.04 support to linux_build.sh

- .github/workflows/CI.yml
- cmake/compile_definitions/windows.cmake
- tools/CMakeLists.txt
- tools/audio.cpp
Fix Windows build, same logic used as in `build-deps` repo.
See:
- https://github.com/msys2/MINGW-packages/issues/24209
- https://github.com/microsoft/cppwinrt/issues/1490
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=120495
> build(windows): fix gcc15 compatibility

- src/platform/macos/av_video.m
One liner change from identity comparison to value comparison for display ID. It fixes the issue for me on macOS 26 beta. I only have one computer, so I’m unable to verify whether this change affects compatibility with earlier versions of macOS.
Before change:
```
[2025-06-19 20:25:34.684802] [0x00000001fb026340] [info]    config: 'stream_audio' = true
[2025-06-19 20:25:34.685028] [0x00000001fb026340] [info]    config: 'ping_timeout' = 10000
[2025-06-19 20:25:34.685]: Info: Sunshine version: 0.0.0.dirty
[2025-06-19 20:25:34.685]: Info: Package Publisher: Third Party Publisher
[2025-06-19 20:25:34.685]: Info: Publisher Website:
[2025-06-19 20:25:34.685]: Info: Get support: https://app.lizardbyte.dev/support
[2025-06-19 20:25:34.685]: Info: config: 'ping_timeout' = 10000
[2025-06-19 …
```
> fix(macOS): nil displayName on macOS 26 beta

- docs/configuration.md
- src/config.cpp
- src/config.h
- src/video.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/audiovideo/DisplayModesSettings.vue
- src_assets/common/assets/web/public/assets/locale/en.json
This PR makes the minimum_frame_time calculation based strictly on the client requested framerate.
| Client Framerate | `minimum_frame_time` | static FPS |
| --- | --- | --- |
| 30 | 33ms | 23 |
| 60 | 16ms | 33 |
| 90 | 11ms | 55 |
| 120 | 8ms | 64 |
TODO:
Optionally:
- Closes https://github.com/LizardByte/Sunshine/pull/3715
- Resolves https://github.com/LizardByte/Sunshine/issues/3419
> fix(video): base min frame time strictly on client framerate

- cmake/compile_definitions/windows.cmake
See https://github.com/msys2/MINGW-packages/issues/24209#issuecomment-3019838909
> build(windows): remove no-template-body exception

- .github/workflows/ci.yml
This PR adds VirusTotal scanning results to the end of the release notes in the releases.
See:
- https://github.com/LizardByte/roadmap/issues/86
- https://github.com/LizardByte/actions/pull/13
- https://github.com/LizardByte/Sunshine/issues/3962
> ci(release): add virustotal reports

- src/main.cpp
- src/rtsp.cpp
- src/rtsp.h
This PR slightly refactors the RTSP thread (erroneously called the `rtpThread`) to eliminate the useless wakeup every 500ms that happens all the time while Sunshine is running. This needlessly wastes power by waking up the CPU even while the system is otherwise completely idle.
The thread was previously performing 2 main jobs:
- Expiring sessions that had been launched through the HTTPS server but not yet completed the RTSP handshake
- Removing sessions that had been stopped
The first job is now handled by a `steady_timer` which runs in the ASIO `io_context` to time out any session that hasn't been fully established within the ping timeout. The second job is still performed by the RTSP thread, but it now only polls while there are actually sessions to monitor.
> fix(power): don't wake up every 500ms to poll while not streaming

- src/video.cpp
- src/video.h
AMF Encodes HEVC in L6.2 by default. Some clients can't properly handle level higher than 5.2 (e.g. webOS: https://github.com/mariotaku/moonlight-tv/issues/355)
This PR tries to use a lower level when possible, determined by resolution/frame rate automatically according to [specs](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding_tiers_and_levels#Levels), which improves compatibility.
Not applicable.
Resolve https://github.com/mariotaku/moonlight-tv/issues/355
> fix(amf): attempt to use level 5.1/5.2 for hevc

- src_assets/common/assets/web/configs/tabs/audiovideo/DisplayDeviceOptions.vue
As discussed in #3613, the import for the Checkbox element was removed as a part of #3579 which stopped the 'Config revert on disconnect', option in the display options, from rendering.
This simply adds the import back which restores the functionality.
Before (v2025.628.4510):
After:
None
> fix(display): Restore Checkbox import for display device opts

- scripts/linux_build.sh
This adds two missing build dependencies for Arch to linux_build.sh: doxygen and graphviz.
> build(deps): add doxygen and graphviz to arch deps

- .gitattributes
- .github/matchers/copr-ci.json
- .github/matchers/docker.json
- .github/matchers/gcc-strip3.json
- .github/matchers/gcc.json
- .github/workflows/ci-copr.yml
- .github/workflows/ci-flatpak.yml
- .github/workflows/ci-homebrew.yml
- .github/workflows/ci-linux.yml
- .github/workflows/ci-windows.yml
- .github/workflows/localize.yml
- cmake/prep/build_version.cmake
- docker/archlinux.dockerfile
- docker/clion-toolchain.dockerfile
- docker/debian-bookworm.dockerfile
- docker/ubuntu-22.04.dockerfile
- docker/ubuntu-24.04.dockerfile
- packaging/linux/fedora/Sunshine.spec
- packaging/linux/flatpak/scripts/additional-install.sh
- packaging/linux/flatpak/scripts/remove-additional-install.sh
- scripts/icons/convert_and_pack.sh
- scripts/linux_build.sh
- src_assets/macos/misc/uninstall_pkg.sh
`actionlint` and problem matchers are being added in https://github.com/LizardByte/.github/pull/488
This PR tests several of the problem matchers, and will update the workflows to pass the `actionlint` step.
Confirmed the following problems matchers are working:
TODO:
> ci: use actionlint and problem matchers

- docs/configuration.md
- src/config.cpp
- src/config.h
- src/video.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/audiovideo/DisplayModesSettings.vue
- src_assets/common/assets/web/public/assets/locale/en.json
This PR merges the current minimum FPS behavior with the old min_fps_factor, under a new name minimum_fps_target. It defaults to 0 (current "about half the stream FPS") and can be set to any value from 1-1000. (Note: input validation appears to be broken, but is out of scope for this fix.)
- Fixes #4055
> fix(video): restore the ability to set a minimum fps target

- docs/troubleshooting.md
Just a small documentation improvement with example code how traffic shaping could be done on a OS Level.
I troubleshooted that issue for many hours, found out about this helpful page but didn't found any examples. I think that will be helpful for many other users too.
> docs: Docs buffer overrun improvement

- src/config.cpp
- src/entry_handler.cpp
- src/main.cpp
- src/nvenc/nvenc_d3d11.cpp
- src/nvenc/nvenc_d3d11.h
- src/nvenc/nvenc_d3d11_on_cuda.cpp
- src/nvenc/nvenc_d3d11_on_cuda.h
- src/nvhttp.cpp
- src/platform/windows/audio.cpp
- src/platform/windows/display_base.cpp
- src/platform/windows/display_vram.cpp
- src/platform/windows/input.cpp
- src/platform/windows/misc.cpp
- src/platform/windows/nvprefs/driver_settings.cpp
- src/platform/windows/nvprefs/driver_settings.h
- src/platform/windows/nvprefs/nvapi_opensource_wrapper.cpp
- src/platform/windows/nvprefs/nvprefs_common.h
- src/platform/windows/nvprefs/undo_file.cpp
- src/system_tray.cpp
- tools/sunshinesvc.cpp
Fixes sonar cpp:S4962 issues.
- Fixes https://sonarcloud.io/project/issues?rules=cpp%3AS4962&issueStatuses=OPEN%2CCONFIRMED&id=LizardByte_Sunshine
> style(sonar): fix cpp:S4962

- docs/configuration.md
- src/config.cpp
- src/config.h
- src/main.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/General.vue
- src_assets/common/assets/web/public/assets/locale/en.json
Add a runtime config option to enable/disable system tray (and desktop notifications associated with it) so Users can disable the tray icon if they wish to without having to recompile Sunshine. This is especially helpful if there are issues related to the system try (like #4199).
- Resolves https://github.com/orgs/LizardByte/discussions/334
> feat(tray): Add runtime config option to enable/disable system tray

- scripts/linux_build.sh
Debian Trixie requires new dependencies when building in order to find udev and systemd.
- Fixes https://github.com/LizardByte/Sunshine/issues/4243
> fix(linux): service file for Trixie
