LizardByte/Sunshine

- scripts/build-private.sh
- scripts/build-sunshine.sh
build scripts under ./scrips/ are pulling sources from original repository
> fix git url in build scripts

- .github/workflows/CI.yml
- CHANGELOG.md
- CMakeLists.txt
- Use master branch for create_release action
- Bump version to v0.13.0
> Prepare v0.13.0

- .github/workflows/CI.yml
- scripts/Dockerfile-debian
- scripts/Dockerfile-fedora_33
- scripts/Dockerfile-fedora_35
- scripts/Dockerfile-ubuntu_18_04
- scripts/Dockerfile-ubuntu_20_04
- scripts/Dockerfile-ubuntu_21_04
- scripts/Dockerfile-ubuntu_21_10
- Adds Ubuntu 18.04 build and deb package
- General Dockerfile cleanup
- Prepares CI for rpm packaging
> Add ubuntu 18.04 packaging

- .github/workflows/localize.yml
- docs/source/contributing/localization.rst
- scripts/_locale.py
- Do not fail localize workflow if `sunshine.po` does not exist
- Add proper keywords for boost::locale
- Minor documentation updates about localization
> Do not fail workflow if `sunshine.po` doesn't exist

- .github/workflows/CI.yml
- Add missing dependencies to AppImage
- Fixes #146
> Add missing dependencies to AppImage

- .github/workflows/CI.yml
- packaging/linux/flatpak/com.github.sunshinestream.sunshine.yml
Fixes CI for pull requests from outside SunshineStream organization.
- Fixes #231
> Fix flatpak CI for outside pull requests

- .github/workflows/CI.yml
The `hapakaien/archlinux-package-action@v2` action is currently broken. This PR is testing a forked version that aims to update the archlinux-keyring.
> fix aur build

- docs/source/about/third_party_packages.rst
Update Winget badge link to `LizardByte.Sunshine`
> Update Winget badge link

- .github/workflows/CI.yml
- upstream archlinux-package-action has been fixed
> fixed archlinux-package-action

- CMakeLists.txt
- update version in `CMakeLists.txt`
- Fixes #(issue)
> prepare v0.14.1

- .github/workflows/CI.yml
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
Changes flatpak sources to Ubuntu jammy packages, since the original sources are known to be unavailable from time to time (affecting the automated build process on GitHub).
Also, changes flatpak build to `ubuntu-22.04`
> Change Flatpak sources to jammy

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- Bump ffmpeg from 4.4.2 to 5.5.1 (flatpak)
> Update Flatpak sources to Kinetic

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
Reduces build time for Flatpak by disabling building certain, unneeded, features of dependencies.
> Reduce build time and cleanup for Flatpak

- .github/workflows/CI.yml
- uses matrix build for flatpak (aarch64 should only build on release triggering events)
Replaces #386
> use matrix build for flatpak

- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
Enabling FFMPEG to use CPU encoding libraries.
> Adding back CPU encoding

- .github/workflows/CI.yml
Export the debug extension in order to debug the Sunshine Flatpak
> Export Debug Bundle

- .github/workflows/CI.yml
> add flatpak-builder cache

- .github/workflows/CI.yml
Reduce the cache size by removing the temporary build of Cuda.
> [Flatpak] Do not cache cuda module

- .github/workflows/CI.yml
- use github sha for nightly tag
- using `nightly` as tag is problematic
- specifically provide commit to release action
- flatpak build was failing as it expected the commit of the `master` branch after the nightly release was already created which pointed to the master commit instead of the nightly commit
- build aarch64 flatpak on nightly release
> update nightly releases

- .github/workflows/CI.yml
> fix `setup_release` outputs

- .github/workflows/CI.yml
- update nightly release builds
- use `nightly-dev` tag for nightly releases
- add commit hash to nightly release body
- fix strategy matrix for flatpak build
- aarch64 will build on releases only
> update nightly release builds

- CHANGELOG.md
- CMakeLists.txt
- update changelog
- update version in CMakeLists
> prep v0.15.0

- .github/workflows/CI.yml
- fix CI setup-release
prior issue on push to `master` branch
```bash
if [[ $GITHUB_EVENT_NAME == "push" ]]; then
RELEASE=true
else
RELEASE=false
fi
COMMIT=660d8e191c9019aab762a60ffe075bbf56993ad2
if [[ $GITHUB_REF == refs/heads/master ]]; then
TAG="v0.15.0"
RELEASE_NAME="v0.15.0"
RELEASE_BODY="### Added
- (Windows) Add firewall rules scripts
- (Windows) Automatically add and remove firewall rules at install/uninstall
- (Windows) Automatically add and remove service at install/uninstall
- (Docker) Official image added
- (Linux) Add aarch64 flatpak package
- (Windows/Linux/MacOS) - Move default config and apps file to assets directory
- (MacOS) Bump boost to 1.80 for macport builds
- (Linux) Remove backup and restore of config files
- (Linux) - Create sunshine config directory if it …
```
> fix CI setup-release

- .github/workflows/CI.yml
- fixes env variable for setup release job
> fix CI env variables

- .github/workflows/CI.yml
- (actually) fix for setup_release job output
Tested these scenarios for release body:
- changelog (multiline string) used as release body
- overwrote release body with random string (single line string)
- no text for release body
> fix env variables for setup_release job

- .github/workflows/CI.yml
- updates winget release job needs
- Fixes #464
> fix winget release

- src/stream.cpp
Sunshine currently sends a hardcoded frame header with an invalid frame type value (`0x104`) that `moonlight-common-c` knows to ignore (otherwise it asserts on unknown frame types). Most of the frame header is unknown, but send a valid frame type value now that we understand that part of the header (and `moonlight-common-c` uses it for reference frame invalidation handling).
> Send valid frame type value in frame header

- src/stream.cpp
Sunshine is not sending valid timestamps in the RTP header for video traffic. This caused clients that depend on PTS for frame pacing to break (see https://github.com/moonlight-stream/moonlight-ios/issues/538).
I introduced a workaround in moonlight-common-c to unbreak iOS for servers that send broken PTS information (https://github.com/moonlight-stream/moonlight-common-c/commit/bc00d957d34cb6d66b7638fdf63282b7d0210f80), but this is the proper server-side fix. PTS is arguably even more important for Sunshine compared to GFE, because Sunshine doesn't send frames at a constant rate (when there is no activity on screen). …
> Send a valid PTS in the RTP video header

- .gitmodules
> set submodule branches

- src/platform/windows/audio.cpp
Sunshine requires 48 KHz sample rate audio for compatibility with the Opus encoder. If the primary audio device on the host is not set to 48 KHz, audio will be glitchy or unavailable entirely due to a lack of a compatible 48 KHz loopback format.
Fortunately, Windows includes a built-in resampler that can transparently resample any loopback format to 48 KHz for us. All we have to do is ask for the resampler when creating our audio client and it will do the magic for us.
Relevant docs: https://learn.microsoft.com/en-us/windows/win32/coreaudio/audclnt-streamflags-xxx-constants
Fixes #233 …
> windows: Fix audio when host is not using 48 KHz sample rate

- src/platform/windows/misc.cpp
This fixes the reported issue of Sunshine being unable to launch apps in non-service mode. It turned out that it worked fine if non-elevated or admin without UAC, but broke if Sunshine was launched as admin with UAC enabled.
Now we will just launch the app without impersonation when Sunshine is running in the context of a user account (either elevated or non-elevated). The result is that apps will have the same elevation status as Sunshine itself, but that seems fine to me.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull …
> Fix launching apps when Sunshine is running as admin

- .github/workflows/CI.yml
pin libpsl until https://github.com/msys2/MINGW-packages/issues/14882 is resolved
> windows: pin libpsl version

- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_vram.cpp
- src/video.cpp
This PR modifies `hwdevice_t` to use a separate `ID3D11Device` and `ID3D11DeviceContext` to allow encoding to happen in parallel with capture without violating DXGI synchronization requirements. Each `img_t` has a texture created on the capture-side by `display_vram_t::complete_img()` which is then opened via handle on the encoding side by `hwdevice_t::share_img()`. 
The only concurrency bottleneck now is `display_vram_t::snapshot()` and `hwdevice_t::convert()` where they use a `IDXGIKeyedMutex` to synchronize access to the same `img` texture. Since `PARALLEL_ENCODING` creates a pool of images, this is unlikely to a problem in practice.
This PR temporarily includes the changes in #667 since they are necessary for this to work. Once #667 is merged, I'll rebase this to remove that commit. …
> Use separate encoding and capture devices to enable parallel encoding and capture

- README.rst
Docs were failing to build `epub` version due to an unknown `mimetype`. See here https://github.com/badges/shields/issues/8671#issuecomment-1369157186
> fix docs badges for epub

- src/video.cpp
We want to keep the VBV buffer size equal to one frame (`bitrate / framerate`) to avoid large frame size spikes, so let's avoid increasing it unless we're using software encoding with more than one slice.
> Only increase rc_buffer_size when software encoding with more than one slice

- CHANGELOG.md
- CMakeLists.txt
- update changelog
- add release links to end of changelog
- update version number
> prepare v0.17.0

- docs/source/about/usage.rst
Fixes typo `F13` -> `F12` in `Shortcuts` section of documentation.
> Fix typo in `Shortcuts` section

- src/video.cpp
Our variable frame rate encoding scheme has a major issue with static content because the RC buffer limit can be reached and additional frames are required to fill in additional detail (which will never come if the image is static). This PR improves image quality in that situation by encoding the previous frame again if the capture frame rate drops below 10 FPS.
You can easily see this effect if you connect with Moonlight Qt at low bitrate with a complex scene displayed on the host and then resize the Moonlight window (which triggers a key frame).
We probably want to move to fixed rate encoding, but this is a very simple stop-gap until we do that work.
Fixes #717
must be …
> Enforce 10 FPS encoding frame rate floor to improve static image quality

- docs/source/about/advanced_usage.rst
Add a link to the nvenc preset migration guide to assist users in choosing from the new presets.
Ref: https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-preset-migration-guide/
> nvenc: add nvidia preset migration guide to docs

- .github/workflows/CI.yml
Attempt to fix nightly pushes to the AUR.
- Fixes #678 
> fix aur nightly publishing

- .github/workflows/CI.yml
Fix aur publish conditions. If statements in bash were evaluating incorrectly.
- Fixes #678 
> cd: fix aur publish conditions

- CHANGELOG.md
Previous changelog resulted in an error when parsing.
```txt
unexpected EOF while looking for matching `''
```
> changelog: fix v0.18.0 formatting

- CMakeLists.txt
- docker/fedora-36.dockerfile
- docker/fedora-37.dockerfile
- docker/ubuntu-22.04.dockerfile
- docs/source/building/linux.rst
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
CMake: Linux: update dependencies & use dynamic Boost
Fixes: #434 
> CMake: Linux: update dependencies & use dynamic Boost

- CHANGELOG.md
> changelog: v0.18.1

- CMakeLists.txt
Update version in CMakeLists.txt
> cmake: v0.18.1

- src/config.cpp
Invert default config settings for input (keyboard, mouse, controller)
> input: invert default config settings

- docs/source/conf.py
> docs: add favicon

- src_assets/common/assets/web/config.html
Fixes an issue introduced in #1023 where apply button would not call api.
> ui: fix apply settings

- src/system_tray.cpp
Open URLs as unprivileged user, as they would not open properly when running Sunshine as a service on Windows.
> tray-icon: execute as user

- .github/workflows/ci-qodana.yml
- qodana-js.yaml
- qodana-python.yaml
> ci: add qodana

- src/utility.h
This change fixes build with GCC 13 on Fedora 38.
n/a
n/a
> Add missing <string> include

- CHANGELOG.md
- CMakeLists.txt
> v0.19.0 release prep

- CHANGELOG.md
- CMakeLists.txt
> v0.19.1 prep

- docs/source/conf.py
Use `project_copyright` alias instead of built-in `copyright` for Sphinx configuration file.
> docs: use project_copyright alias

- src/video.cpp
The dummy images are not needed after populating the `AVFrame` with `convert()`, so we can free them to avoid having an extra image hanging around in RAM or VRAM the whole time while we're streaming.
> Free dummy images when they are no longer needed

- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/cuda.cu
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/wlgrab.cpp
- src/platform/linux/x11grab.cpp
- src/platform/macos/display.mm
- src/platform/windows/display.h
- src/platform/windows/display_base.cpp
- src/platform/windows/display_ram.cpp
- src/platform/windows/display_vram.cpp
- src/video.cpp
An attempt to minimize vram usage without introducing possible computational bottlenecks.
Still needs a lot of work, but so far the results look promising.
Before (4K60 SDR)
After (4K60 SDR)
> Minimize vram usage

- src/video.cpp
Follow-up to https://github.com/LizardByte/Sunshine/pull/1098, split up because that pull request is big enough already.
Whether we should use one universal timeout for all buffer size thresholds and how big this timeout should be is up for discussion.
> Delay capture buffer downsize

- docker/fedora-36.dockerfile
- docker/fedora-37.dockerfile
> build(deps): update fedora dependencies

- docs/source/about/advanced_usage.rst
> docs(advanced_usage): fix nvlax url

- docs/Doxyfile
This PR enables macro expansion for Doxygen. This will allow code within macros to have docs generated.
> docs(doxygen): enable macro expansion

- src/system_tray.h
Adds header guards to system_tray.h and removes redundant macro ifdef block. The macro was preventing doxygen from parsing `system_tray.h` and the following lines should execute without the macro specified in `system_tray.h`.
* https://github.com/LizardByte/Sunshine/blob/5ad5699456be78ff45865a16d0ae1961498baa8f/src/main.cpp#L335
* https://github.com/LizardByte/Sunshine/blob/5ad5699456be78ff45865a16d0ae1961498baa8f/src/main.cpp#L415
* https://github.com/LizardByte/Sunshine/blob/5ad5699456be78ff45865a16d0ae1961498baa8f/src/system_tray.cpp#L5
n/a
n/a …
> fix: header guards on system tray

- .readthedocs.yaml
- docs/Doxyfile
- docs/source/source/src/audio.rst
- docs/source/source/src/cbs.rst
- docs/source/source/src/config.rst
- docs/source/source/src/confighttp.rst
- docs/source/source/src/crypto.rst
- docs/source/source/src/httpcommon.rst
- docs/source/source/src/input.rst
- docs/source/source/src/main.rst
- docs/source/source/src/move_by_copy.rst
- docs/source/source/src/network.rst
- docs/source/source/src/nvhttp.rst
- docs/source/source/src/platform/linux/cuda.rst
- docs/source/source/src/platform/linux/vaapi.rst
- docs/source/source/src/platform/linux/wayland.rst
- docs/source/source/src/platform/macos/misc.rst
- docs/source/source/src/platform/windows/misc.rst
- docs/source/source/src/process.rst
- docs/source/source/src/round_robin.rst
- docs/source/source/src/rtsp.rst
- docs/source/source/src/stream.rst
- docs/source/source/src/sync.rst
- docs/source/source/src/system_tray.rst
- docs/source/source/src/task_pool.rst
- docs/source/source/src/thread_pool.rst
- docs/source/source/src/thread_safe.rst
- docs/source/source/src/upnp.rst
- docs/source/source/src/uuid.rst
- docs/source/source/src/video.rst
Add dependency diagrams to docs using `graphviz`.
> docs(diagrams): add diagrams using graphviz

- src/video.cpp
This fixup can be removed, since the bug in Moonlight has been fixed since the middle of last year.
> Remove 3-byte NALU prefix fixup

- src/confighttp.cpp
- src/main.cpp
- src/main.h
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
- src/system_tray.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/troubleshooting.html
This PR implements restart support for Linux, Mac, and standalone Windows scenarios and adds a Restart option to the system tray icon as requested in #1187. I also made some minor improvements to the restart success messages by making them auto-hide after 5 seconds.
Since Mac and Linux will not deterministically manage to send the POST response before restarting, I've removed the success/failure logic there. Since we're restarting in an `atexit()` callback after closing all fds, there's no real way to get status back to the UI anyway.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-wi …
> Universal restart support

- docker/debian-bullseye.dockerfile
- docker/fedora-36.dockerfile
- docker/fedora-37.dockerfile
- docker/ubuntu-20.04.dockerfile
- docker/ubuntu-22.04.dockerfile
Unpin (most) docker dependencies.
> build(deps): unpin docker dependencies

- src/platform/linux/cuda.h
> Add missing cstdint include

- src/nvhttp.cpp
- src_assets/common/assets/web/config.html
We weren't sending any status messages to clients with our failure responses. As a result, they'd just see a 400/404/503 error code with no context to explain what the error actually was.
> Add status messages for client errors

- docker/fedora-38.dockerfile
- docs/source/about/installation.rst
Add Fedora 38 docker image and release assets.
Todo:
> ci: add fedora 38

- docs/source/source/src/task_pool.rst
> docs: correct typo for task_pool

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/platform/windows/audio.cpp
- src_assets/common/assets/web/config.html
This PR adds a feature to install the Steam Streaming Speakers driver if it's present on disk (Steam installed) but not already installed (if the user hasn't used Steam Remote Play). Since some users may have their own audio configuration that they don't want us messing with, I added a UI option to opt-out of this behavior.
The Steam Streaming Speakers driver allows us to support 5.1 and 7.1 surround sound on systems without a physical surround sound output. It also allows the "Play audio on host PC" option in Moonlight to correctly mute host audio. …
> Add support for installing the Steam Streaming Speakers driver

- CMakeLists.txt
- src/cbs.cpp
- src/config.cpp
- src/crypto.cpp
- src/input.cpp
- src/platform/linux/cuda.cpp
- src/platform/linux/cuda.cu
- src/platform/linux/graphics.cpp
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/display_vram.cpp
- src/platform/windows/misc.cpp
- src/round_robin.h
- src/stream.cpp
- src/task_pool.h
- src/upnp.cpp
- src/utility.h
- src/video.cpp
Fixes a bunch of compiler warnings, mostly on Clang. Specific details of each fix are in the individual commits.
> Compiler warning cleanup

- src/main.cpp
We've had many instances of users that install Sunshine without turning off GameStream in GeForce Experience. This leads to all sorts of issues trying to stream that are difficult to debug, especially because users don't always mention that they were/are using GameStream.
This PR prints a log message if GameStream is enabled and Sunshine is configured to use the same set of ports as GFE. I printed them at the "Fatal" level in an attempt to draw the most attention to them.
It would be nice to have some prominent way of displaying major configuration warnings in the Web UI like specifying a missing display, having no working encoders, port conflicts, etc. Since we don't have that, a log message is the next best thing.
LizardByte requires that branches be up-to-date before merging. This …
> Print a warning if GameStream is using conflicting ports

- CMakeLists.txt
- src/main.cpp
- src_assets/windows/misc/autostart/autostart-service.bat
- src_assets/windows/misc/service/install-service.bat
- src_assets/windows/misc/service/uninstall-service.bat
- tools/sunshinesvc.cpp
The first commit consolidates required service options and introduces friendly text for each installer option. The text changes ensure the new "Launch on Startup" option doesn't stick out from the others.
The second commit adds a friendly name to be displayed for SunshineSvc in Task Manager and Services.msc. It's totally cosmetic but nice to have.
The third commit introduces a configurable installer option to allow users to select whether they want Sunshine to start on boot (enabled by default as it is today). Some users don't want Sunshine to start automatically, so this allows them to still use the installer version for that use case now that the service is mandatory. If the service isn't running yet, the shortcut launch code elevates itself and starts it.
The fourth commit expands the …
> Installer option cleanup, manual start option, and service rename

- src/audio.cpp
- src/platform/windows/audio.cpp
- The first commit fixes a couple of issues with the Audio Sink option. If selected, Sunshine would not actually switch to it on stream start but instead would switch to it on stream _end_. This also fixes Sunshine incorrectly switching to the Audio Sink instead of the original audio device when ending a stream where the Virtual Sink was used.
- The second commit adds logic to reset the default audio device away from Steam Streaming Speakers on startup (the same way Steam does). This fixes the case where the user must manually switch the default audio device back if Sunshine crashes while streaming. Now the default audio device will automatically switch back to the previous default in a few seconds when SunshineSvc restarts Sunshine.
LizardByte requires that branches be up-to-date before …
> Audio sink fix and default device reset on startup

- CHANGELOG.md
- CMakeLists.txt
- docs/source/gamestream/gamestream.rst
Changelog and release version bump for v0.20.0
> v0.20.0 release prep

- README.rst
- docs/source/about/third_party_packages.rst
- Force badges to use svg image format.
- Move Winget package to official downloads.
- Change url target for nix package.
- Use repology for Chocolatey pacakge.
- Add AOSC package to third party list.
- Add logo for Scoop package.
> docs(badges): force badges to use svg

- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/cuda.cu
- src/platform/linux/graphics.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/publish.cpp
- src/platform/macos/nv12_zero_device.cpp
- src/platform/macos/publish.cpp
- src/platform/windows/display_vram.cpp
- src/platform/windows/misc.cpp
- src/thread_safe.h
- src/video.cpp
- third-party/nvfbc/NvFBC.h
Corrects typos found in comments using the utility, [Codespell](https://github.com/codespell-project/codespell). Has no impact to any logic or user-surfaced output.
`N/A`
`N/A`
> Correct typos in comments

- src/platform/linux/input.cpp
- src/platform/macos/input.cpp
- src/system_tray.cpp
- src_assets/common/assets/web/apps.html
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/troubleshooting.html
Corrects typos that will be surfaced to an end user using the utility, [Codespell](https://github.com/codespell-project/codespell).
`N/A`
`N/A`
> Correct typos in logging & web portal

- src/platform/windows/display_base.cpp
Latest changes to the img queue may have caused occasional stream freezes.
This attempts to investigate and mitigate them.
> Investigate and mitigate possible stream freezes

- src_assets/windows/misc/vigembus/install-vigembus.bat
Retrieve system proxy settings from the registry and pass them into the curl command.
This is a reimplementation of pull request https://github.com/LizardByte/Sunshine/pull/1118 without using PowerShell. 
It retrieves ```HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings```. if ```ProxyEnable``` equals ```0x1```, it will parse ```ProxyServer``` with ```-x ``` in the front to the curl command. if ```ProxyEnable``` equals any other value or dosen't exist, it will not use proxy.
Resolves  https://github.com/LizardByte/Sunshine/issues/1116 …
> fix(installer): use the system proxy to download ViGEmBus if it is enabled

- docker/debian-bookworm.dockerfile
- docs/source/about/installation.rst
- docs/source/building/linux.rst
Add debian bookworm package.
- Resolves #1454 
> build(distro): add debian bookworm package

- src/input.cpp
- src/platform/common.h
- src/platform/linux/input.cpp
- src/platform/macos/input.cpp
- src/platform/windows/input.cpp
This PR implements native pen and touch support for Windows using the Sunshine protocol extensions and `InjectSyntheticPointerInput()` which was introduced in Windows 10 1809. It also implements the core plumbing needed for supporting this feature on Mac and Linux.
Most major pen/touch features are supported including:
- 10-point multitouch
- Contact area
- Pressure
- Rotation and tilt
- Hover (though not distance, due to Windows API limitations)
- Pen buttons (only 1, due to Windows API limitations)
This implementation is currently limited to direct input devices where the pen/touch device is associated with a screen. It does not currently support independent devices like standalone drawing tablets (and likely never will on Windows, due to API limitations).
cc: @ABeltramo 
LizardByte …
> Native pen and touch support for Windows

- src/platform/windows/input.cpp
We still need to call `syncThreadDesktop()` in the pen/touch codepath like we do with `SendInput()` since that's also injecting to the thread's current input desktop. Without this, touch input doesn't work on the login screen or in the UAC secure desktop.
> Fix touch input on UAC secure desktop and login screen

- src_assets/common/assets/web/config.html
Fixes the annoying indentation for  "Output Name" field
Before:
After:
None so far
> Remove "config-page" class from "Output Name" field

- .github/workflows/CI.yml
- packaging/macos/Portfile
This PR simplifies the macports build in the CI.
> ci: simplify macport build

- .readthedocs.yaml
- .rstcheck.cfg
- README.rst
- docs/requirements.txt
- docs/source/about/advanced_usage.rst
- docs/source/about/app_examples.rst
- docs/source/about/installation.rst
- docs/source/about/usage.rst
- docs/source/building/build.rst
- docs/source/building/linux.rst
- docs/source/building/macos.rst
- docs/source/building/windows.rst
- docs/source/contributing/contributing.rst
- docs/source/contributing/localization.rst
- docs/source/contributing/testing.rst
- docs/source/gamestream/gamestream.rst
- docs/source/legal/legal.rst
- docs/source/source/src.rst
- docs/source/troubleshooting/general.rst
- docs/source/troubleshooting/linux.rst
- docs/source/troubleshooting/windows.rst
Lint rst files in readthedocs build.
> docs: lint rst files

- docs/source/about/usage.rst
Update docs/considerations when streaming from a laptop.
- Resolves #872 
> docs: update considerations

- docs/source/contributing/localization.rst
> docs: update localization information

- cmake/dependencies/common.cmake
This PR fixes #1591. Despite the issue talks only about unsupported `sunshine-git` package from AUR, it also affects official Debian, Ubuntu, Fedora, Arch (and probably other) [nightly builds](https://github.com/LizardByte/Sunshine/releases/tag/nightly-dev). They all contain the following unwanted files coming from enet:
* `/usr/include/enet/*.h`
* `/usr/lib/static/libenet.a`
Enet [already got](https://github.com/cgutman/enet/commit/bbfe93c248ce198246328d52bda5b4e6dd4cc95e) a new CMake option `ENET_NO_INSTALL` to disable installation of any enet files. Now on Sunshine side we only need to bump `moonlight-common-c` submodule and activate this option.
- Resolves #1576 
- Resolves #1591
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, …
> Disable installation of enet headers and libraries

- docs/source/about/usage.rst
- src/process.cpp
- src/process.h
- src_assets/common/assets/web/apps.html
This implements the idea I mentioned on Discord a while back to detect cases where the app terminates quickly with an exit code of 0 and treat that as a detached app. It is enabled by default, because this behavior is desirable in the vast majority of cases.
With this change, launching things like Steam, Chrome, and Firefox as normal commands triggers the auto-detach and stream properly without having to be made detached commands.
This should significantly reduce the incidence of issues like #1422 happening when users aren't sure whether to use detached or normal commands. The detached vs normal commands stuff is very confusing for users, and this is the first baby step toward a future where we can do away with that distinction and just do the right thing automatically.
Resolves #1422 …
> Automatically treat launcher-type apps as detached

- README.rst
- docs/source/contributing/localization.rst
Update docs related to localization.
> docs: update localization

- src/platform/common.h
- src/platform/macos/av_img_t.h
- src/platform/macos/av_video.h
- src/platform/macos/av_video.m
- src/platform/macos/display.mm
- src/platform/macos/nv12_zero_device.cpp
- src/platform/macos/nv12_zero_device.h
- src/video.cpp
This PR fixes a _ton_ of issues in the macOS video capture backend and also considerably simplifies the code. It also implements zero-copy encoding like Windows and Linux have.
Bugs fixed include:
- Use after free on startup caused by pointing the AVFrame into the av_img_t's locked CVPixelBuffer without retaining ownership of it
- Encoding fails with an invalid argument error for non-`PARALLEL_ENCODING` encoders
- Incorrect color range and color space with the VideoToolbox encoder
- Invocation of `push_captured_image_cb()` was incorrectly never reporting a new frame
- Modifying a CVPixelBuffer that we had locked with `kCVPixelBufferLock_ReadOnly`
- Captured images with a stride that was not a multiple of 32 would be completely corrupt due to incorrect stride alignment
Fixes #1348 …
> Fix macOS video capture backend

- src/platform/windows/input.cpp
Some applications examine the timestamp field in the DS4 HID input report to determine if the gamepad is active and for computing angular velocity from motion reports. We weren't updating that field, so these applications didn't work properly.
This fixes [reWASD](https://www.rewasd.com/) and the `timestamp_us` field in `SDL_SensorEvent` for games using SDL.
Fixes #1733 
> Send proper DS4 timestamp values in our input reports

- src/video.cpp
This causes QuickSync to generate H.264 bitstreams with multiple PPS NALUs which lead to some issues in current versions of Moonlight on iOS and Android platforms. I have updated the Android and iOS clients to properly handle this situation now, but the change has not rolled out to users yet.
Aside from Moonlight compatibility issues, this option also seems to override our max_dec_frame_buffering option so it may increase latency on some Android devices too.
After Android and iOS updates have been out in the field awhile, we could potentially investigate turning this back on if we can find some benefit to it.
This reverts commit f838069a0ef80a267de4ea4382712c0680215266.
must …
> Revert "Use new 'remotegaming' scenario setting for QSV"

- CHANGELOG.md
- CMakeLists.txt
Update changelog for next release.
> docs: update changelog for v0.21.0

- docs/source/troubleshooting/windows.rst
Updates troubleshooting docs for disk permission issues in Windows.
> docs(windows): add drive permissions troubleshooting

- docs/source/contributing/localization.rst
> docs: fix failing images

- docker/fedora-39.dockerfile
- docs/source/about/installation.rst
- docs/source/building/linux.rst
Add fedora 39 image, and drop fedora 37.
> build(docker): add fedora 39 and drop fedora 37

- cmake/compile_definitions/linux.cmake
This PR moves optional header files to their respective `PLATFORM_TARGET_FILES` setup.
> build(cmake): do not include unneeded headers

- src/platform/linux/x11grab.h
Building with DRM enabled and X11 disabled results in this error:
```
In file included from src/platform/linux/x11grab.h:55:58: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, typename util::Function<void, T*>::type function> using util::safe_ptr = util::uniq_ptr<T, util::Destroy<T*, void, function> >’
55 |   util::safe_ptr<_XDisplay, std::default_delete<_XDisplay>>;
|                                                          ^~
src/platform/linux/x11grab.h:55:58: note:   expected a constant of type ‘typename util::Function<void, T*>::type’, got ‘std::default_delete<_XDisplay>’
src/platform/linux/x11grab.h:68:3: error: ‘xdisplay_t’ does not name a type; did you mean ‘display_t’?
68 |   xdisplay_t
|   ^~~~~~~~~~
|   display_t
````
I suspect this is …
> Fix grabbing code when DRM is enabled and X11 is disabled

- cmake/compile_definitions/common.cmake
- cmake/dependencies/common.cmake
- cmake/prep/options.cmake
As mentioned, I am packaging Sunshine for Gentoo Linux. Don't worry, we are not super strict about unbundling dependencies, and I understand that several are not feasible or worth the effort. This is one I would like to address though.
> Optionally allow the system installation of MiniUPnP to be used

- docs/source/about/advanced_usage.rst
- src/config.cpp
- src/config.h
- src/input.cpp
- src/platform/windows/input.cpp
- src_assets/common/assets/web/config.html
This PR adds a few input configuration options based on user requests.
- Gamepad autoselection logic can now be configured to include/exclude touchpad and motion sensor support when deciding on a controller type
- High resolution scroll events can now be disabled for applications that don't handle them properly (#1873)
- Native pen/touch support can now be disabled for applications without proper pen/touch support
I've also moved a couple input-related options from the General tab to the Input tab where they belong.
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/wo …
> New input configuration options

- src/platform/windows/input.cpp
This is a potential workaround for the BSODs reported in #1370. It seems that keeping a ViGEmBus handle alive across a power transition can cause ViGEmBus to crash, so we will just open it when we need it and close it when all gamepads are gone.
As a nice bonus, this allows Sunshine to pick up a new ViGEmBus installation without needing to restart Sunshine. It might also resolve the issue with the ViGEmBus installer rebooting the system (at least when it's just us holding a ViGEmBus handle).
Fixes #1370
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-fo …
> Only keep the ViGEmBus connection alive while gamepads are attached

- docs/source/troubleshooting/general.rst
> docs: add reset credential examples for unique pacakges

- src/platform/linux/graphics.cpp
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/vaapi.cpp
- src/video.cpp
Rather than actually checking what the format was of the planes returned from `vaExportSurfaceHandle()`, we just assumed they would be `DRM_FORMAT_R8` and `DRM_FORMAT_GR88`. This is correct for NV12, but not P010.
More importantly, we were discarding the DRM modifiers which _will_ break things if the surfaces are tiled or otherwise compressed. I suspect this could be the root cause of #1800 and/or #1041.
It also fixes green padding caused by incorrectly cleared YUV buffers and complete failure of the KMS grab capture method if even a single card fails to initialize.
Fixes #1811
Fixes #1320
Possibly fixes #1800
Possibly fixes #1041
Partially fixes #1631 (kmsgrab part)
must be …
> VAAPI and KMSGrab fixes

- .gitmodules
This switches to our own private submodule of ViGEmClient with the hope of fixing #1841.
See https://github.com/LizardByte/Virtual-Gamepad-Emulation-Client/pull/1
Fixes #1841
> Switch to LizardByte ViGEmClient submodule

- src/platform/linux/input.cpp
We didn't correctly accumulate scroll deltas if they were less than a full tick of the scroll wheel on Linux. This meant that things would work normally for applications that exclusively used the `REL_WHEEL_HI_RES` scroll events, but high-res scrolling wouldn't work at all for older applications that use `REL_WHEEL` or when we used the XTest fallback path.
> Fix low-res scrolling on Linux

- src/platform/macos/input.cpp
AbsoluteToNanoseconds is depreciated since macOS 10.8.
```txt
/Users/runner/work/Sunshine/Sunshine/src/platform/macos/input.cpp:393:19: warning: 'AbsoluteToNanoseconds' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
elapsedNano = AbsoluteToNanoseconds(*(AbsoluteTime *) &elapsed);
^
/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/DriverServices.h:93:1: note: 'AbsoluteToNanoseconds' has been explicitly marked deprecated here
AbsoluteToNanoseconds(AbsoluteTime absoluteTime)              __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
^
1 warning generated.
```
LizardByte requires that …
> fix(macos): replace depreciated AbsoluteToNanoseconds

- src_assets/common/assets/web/index.html
- src_assets/common/assets/web/troubleshooting.html
Add a link to logs when fatal errors prevent Sunshine from starting properly.
> feat(ui): add href to logs in fatal error container

- docs/source/about/setup.rst
- src/platform/linux/graphics.cpp
- src/platform/linux/graphics.h
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/vaapi.cpp
This PR adds experimental support for HDR streaming on Linux using the KMS backend and VAAPI encoding.
It's early days for HDR in the Linux ecosystem, but I've done basic integration testing with Plasma 6.0 Beta 2. It will probably also work with Gamescope, but I haven't tested that. For metadata, we pull the [HDR_OUTPUT_METADATA](https://drmdb.emersion.fr/properties/3233857728/HDR_OUTPUT_METADATA) blob from the CRTC's associated connector and send that data to the client.
HEVC Main 10 encoding quality on my Tiger Lake iGPU is poor (more blocking artifacts than usual) in some areas when in HDR mode, but I'm not sure that's our fault (I recall a similar issue with QSV on Windows). The actual HDR itself seems to work properly. Adjusting the SDR brightness slider in KDE properly raises and …
> Implement HDR support for Linux KMS capture backend

- src/nvhttp.cpp
This PR adds additional pin validation. Checks the length of the pin, and checks for alpha characters.
> fix: add additional pin validation

- docs/source/about/advanced_usage.rst
- src_assets/common/assets/web/config.html
This PR adds hyperlinks in the docs to take the user to the location in the UI where the config categories/settings are located.
Todo:
> docs(advanced-usage): cross reference config UI

- src_assets/common/assets/web/config.html
Hashes that matched the tab id were not handled in #2002.
> fix(ui): allow hash handler to accept tab ids

- src/platform/linux/kmsgrab.cpp
The plane iterator had a bug where it would not reach the final plane in the list of planes, since it always set `plane_p` to the _next_ entry rather than the current entry. This means that `it != std::end(...)` would be false _on_ the last iteration instead of _after_ the final iteration. This bug affected all systems, but it didn't often manifest as a visible issue since the planes we're looking for are rarely the last plane in the list. However, it completely broke VKMS since it only has one plane.
I also updated the mapping of display types to `DRM_MODE_CONNECTOR_` values to silence the (red herring) warning that was also reported in #347.
Fixes #347
must be updated …
> Fix Linux KMS capture on virtual monitors

- DOCKER_README.md
Podman runs rootless and therefore the `lizard` user in the containers does not have access to the `~/.config/sunshine` directory. This PR adds a section about using Podman, as well as a few other fixes.
- Resolves #2033 
> docs(docker): add podman notes

- .gitmodules
- cmake/compile_definitions/common.cmake
- cmake/dependencies/common.cmake
- cmake/dependencies/windows.cmake
- src/platform/windows/nvprefs/driver_settings.cpp
- src/platform/windows/nvprefs/driver_settings.h
- src/platform/windows/nvprefs/nvapi_opensource_wrapper.cpp
- src/platform/windows/nvprefs/nvprefs_common.cpp
- src/platform/windows/nvprefs/nvprefs_common.h
- src/platform/windows/nvprefs/nvprefs_interface.cpp
- src/platform/windows/nvprefs/nvprefs_interface.h
- src/platform/windows/nvprefs/undo_data.cpp
- src/platform/windows/nvprefs/undo_data.h
- src/platform/windows/nvprefs/undo_file.cpp
- src/platform/windows/nvprefs/undo_file.h
Added a https://github.com/nlohmann/json library as a submodule to be used when working with JSON.
All uses of `boost::json` have been removed.
> Add a dedicated library for working with JSON

- docs/source/about/setup.rst
Corrects some wording in the Portfile installation instructions.
> docs(setup): correct instruction for portfile install

- src/platform/linux/cuda.cpp
- src/platform/linux/cuda.h
- src/platform/linux/graphics.cpp
- src/platform/linux/graphics.h
- src/platform/linux/kmsgrab.cpp
- src/platform/linux/wlgrab.cpp
This PR uses the CUDA OpenGL interoperability APIs to support passing NVENC frames captured from KMS or wlgrab without having to make a round-trip through CPU memory. This massively improves capture performance at high resolutions when not using NvFBC (like under Wayland or without NvFBC-patched drivers). It should theoretically also work with the new HDR support in the latest 550 beta drivers released a few days ago, but I haven't tested it myself.
Unlike the VAAPI hardware encoding support which imports the VA surface as EGLImages using `egl::import_target()`, we don't have any similar external buffer to import. Instead, we simply create target Y and UV plane textures using OpenGL via the new `egl::create_target()` function, then register them with CUDA using …
> Implement proper support for KMS and wlgrab capture with NVENC

- src/network.cpp
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/misc.cpp
- src/stream.cpp
This PR fixes several issues with QoS tagging on Windows and Linux and implements QoS tagging for macOS.
- Add a workaround to fix QoS tagging for IPv4 streams when running Sunshine in IPv4+IPv6 dual-stack mode on Windows
- Adds opportunistic QoS tagging for control stream traffic from the host (client-side already did this for a long time)
- Adds missing call to `enet_initialize()` before using libenet
- Allows priority mechanisms like `SO_PRIORITY` and `SO_NET_SERVICE_TYPE` to be used on macOS and Linux, even if the client requests no DSCP tagging
- Fixes QoS tagging being disabled on Linux when a client disconnects, even if other clients are still streaming
- Reduces audio DSCP tag from CS7 to CS6 to better adhere to standard QoS marking behavior (CS7 is reserved for critical network …
> QoS tagging and prioritization fixes and improvements

- src/platform/linux/misc.cpp
Trivial fix for bug found during QoS testing.
> Fix DSCP tagging for dual-stack sockets on Linux

- src/stream.cpp
We inform any connected clients that the stream is gracefully terminating if the app being streamed exits, however we did not do that properly if Sunshine itself is exiting (via Exit/Restart options in the system tray, Restart button in the UI, Ctrl+C on the command-line, etc). This fixes the latter case to avoid giving the user an unnecessary termination dialog without any useful error code (since it wasn't an error in the first place). …
> Inform clients of graceful termination when Sunshine exits

- src/platform/windows/display_base.cpp
#2031 introduced a regression when a multi-monitor system is running Sunshine portable (not using the service) and triggers the UAC secure desktop. If this happens, there will be a random chance that the display switches after the UAC prompt is dismissed. Whether this happens depends on exactly when during the display reenumeration that the active desktop switches back to one we have permission to capture.
This PR addresses the issue by ensuring we only call `syncThreadDesktop()` once per enumeration. Because the thread desktop appears to be how DXGI DDA determines if a display can be captured, this ensures a consistent view of outputs. Enumeration will either see all displays or see none of them (triggering the expected retry logic in the capture code). The partial display list returned …
> Avoid display switching unexpectedly when the UAC secure desktop appears

- CHANGELOG.md
- CMakeLists.txt
This PR bumps the project version to v0.22.0 and updates the changelog.
> chore: bump version to v0.22.0

- src/platform/linux/cuda.cpp
Linux sysfs uses lowercase hex PCI IDs while CUDA gives us uppercase IDs. This causes us to fail to find the matching DRM device on systems where the PCI ID happens to contain a hex value greater than 9.
In any case, we shouldn't crash if we fail to find the device either, so add some exception handling too.
None of my test hardware seems to assign PCI IDs that trigger this bug, but testing by hand showed the expected behavior. 
Fixes #2212
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-for …
> Fix mismatched case and unhandled exception in CUDA device lookup

- docs/source/about/guides/app_examples.rst
- src/platform/windows/misc.cpp
- src/process.cpp
This PR contains some small fixes to process launching code for Windows:
- Change the cmd.exe trampoline to wait on the launched app to exit, so that process termination tracking works as expected
- Strip quotes out of the specified working directory, in case the user accidentally includes them
- Temporarily prepend the specified working directory to our `PATH` when launching apps to ensure they can be found if specified relative to the working directory (like some of our app examples do)
Finally, the PR updates the Windows app examples in the documentation to reflect the current best practices. …
> Windows app launch fixes and documentation improvements

- src_assets/windows/misc/gamepad/install-gamepad.bat
Using WMIC for this is extremely slow because it requires enumerating all installed MSIs. This PS-based version is simpler and much faster (10x or more) on machines with many installed apps.
> Replace WMIC-based check for ViGEmBus with a Powershell check

- cmake/prep/special_package_configuration.cmake
- docker/archlinux.dockerfile
- docs/source/about/setup.rst
- packaging/linux/Arch/PKGBUILD
- packaging/linux/Arch/sunshine.install
This updates our packaging for Arch-based distros to:
- Build kmsgrab by default for proper Wayland capture support on GNOME, KDE, and other non-wlroots-based compositors
- Add the post-install commands to make kmsgrab work out of the box
- Add optional dependencies for AMD and Intel VAAPI drivers for hardware encoding support
However, this requires removing the the standalone PKGBUILD artifact from our releases due to the new dependency on the install script. However, this should be fine. Users that want to build from source should use the AUR, while users that want the binary package directly from us will still be able to get that.
must be updated before it can be merged. …
> Arch packaging updates

- src/platform/linux/kmsgrab.cpp
This PR adds some additional debugging which would be very helpful to debug the recent KMS-related bug reports. It also makes the `SYS_CAP_ADMIN` error much more obvious by upgrading it to fatal severity in cases where we have no available fallback capture mechanism.
The only functional change in this PR is to avoid using KMS capture with a non-atomic driver under X11. In this scenario, we will not be able to capture the mouse cursor because the properties we rely on are atomic-only. Falling back to X11 capture will allow the cursor to be captured properly in that scenario (at a performance cost). …
> Improve KMS debuggability and avoid known broken cases

- src_assets/common/assets/web/config.html
`中国人` means `Chinese people`, correct it to `简体中文` to match the following `(Chinese Simplified)`.
`N/A`
`N/A`
> Correct typo in Chinese Simplified locale option

- codecov.yml
Change default branch to nightly.
> ci(codecov): update codecov default branch

- docs/source/contributing/localization.rst
- src_assets/common/assets/web/pin.html
- src_assets/common/assets/web/public/assets/locale/en.json
- Improve guidance for contributors around localization.
- Translate 2 js strings.
> fix(i18n): update localization docs and js strings

- src_assets/common/assets/web/config.html
Fixes the usage of non-existing locale variable...
> Add mising _win postfix

- docs/source/about/setup.rst
Curl command needs to follow the redirect otherwise you'll get a 0-byte file
> docs: update curl flag for macos portfile installation

- README.rst
GitHub broke rendering of the existing rst tables in the readme, so this updates them to a csv table. The left column will no longer be merged, but instead contain empty text
> docs(readme): use csv tables

- src_assets/common/assets/web/welcome.html
> fix(i18n): use correct key for welcome_success

- CHANGELOG.md
- CMakeLists.txt
> chore: bump version to v0.23.0

- docker/ubuntu-24.04.dockerfile
- docs/requirements.txt
Update python from 3.11 to 3.12.
> build(linux): fix ubuntu 24.04 build

- .github/workflows/CI.yml
Use token for codecov-action, and fail ci if error.
> build(deps): use token for codecov/codecov-action

- src/video.h
Previously:
```
[2024:04:07:13:27:07]: Debug: ------  h264 ------
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: unknown: unsupported
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: -------------------
[2024:04:07:13:27:07]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2024:04:07:13:27:07]: Debug: ------  hevc ------
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: unknown: supported
[2024:04:07:13:27:07]: Debug: -------------------
```
With the fix:
``` …
```
> minor fix in debugging code (codec checks)

- .github/workflows/CI.yml
Disable search for codecov-action, which was generating it's own coverage reports instead of using the provided report.
> ci(codecov): skip search

- .gitignore
- scripts/requirements.txt
- add missing dependency for clang-format
- update gitignore to more closely match github's recommended gitignore file for c++ projects
> chore: repo updates

- .github/workflows/CI.yml
- tests/CMakeLists.txt
I will try to fix code coverage reports in this PR.
References:
- https://github.com/LizardByte/libdisplaydevice/pull/25 (fix exclude paths)
- https://github.com/LizardByte/libdisplaydevice/pull/27 (gcovr exclusions)
- https://github.com/LizardByte/libdisplaydevice/pull/33 (use debug build)
> ci: fix code coverage

- .codeql-prebuild-cpp-Windows.sh
- .github/workflows/CI.yml
Pinning curl until https://github.com/msys2/MINGW-packages/issues/21028 is resolved.
> build(windows): pin curl to working version

- README.rst
Repology no longer has winget listed.
> docs(readme): fix winget badge

- .github/workflows/CI.yml
- cmake/dependencies/common.cmake
- docker/clion-toolchain.dockerfile
- docker/debian-bookworm.dockerfile
- docker/debian-bullseye.dockerfile
- docker/fedora-39.dockerfile
- docker/fedora-40.dockerfile
- docker/ubuntu-22.04.dockerfile
- docker/ubuntu-24.04.dockerfile
- docs/source/building/linux.rst
- packaging/linux/Arch/PKGBUILD
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
Removes unused intel media sdk.
> build(linux): remove unused intel media sdk

- packaging/linux/sunshine.service.in
When using the below sections in the service file, the screen accessibility reader can be activated on some linux distros.
```txt
PartOf=graphical-session.target
Wants=xdg-desktop-autostart.target
After=xdg-desktop-autostart.target
```
- Fixes #1303
> fix(linux): simplify default sunshine.service

- README.rst
Use GitHub API to get latest directory name in winget repo.
> docs(readme): update winget badge query

- .github/workflows/CI.yml
- packaging/sunshine.rb
> fix(brew): update version and fix ci push events

- README.rst
- docs/source/about/third_party_packages.rst
- Add a GHCR badge using https://github.com/ipitio/ghcr-pulls
- Add a Flathub badge
- Change AUR badge to display version number instead of vote count
- Update alternate for badge images
> docs: update badges

- .github/ISSUE_TEMPLATE/bug-report.yml
> ci(issues): update issue template

- docs/Doxyfile
- src/platform/linux/misc.cpp
- src/rtsp.cpp
> docs: fix ffmpeg include directory

- docs/Doxyfile
- src/file_handler.cpp
- src/platform/common.h
- src/platform/linux/cuda.cpp
- src/platform/linux/input/legacy_input.cpp
- src/platform/linux/misc.cpp
- src/platform/linux/wayland.h
- src/platform/macos/input.cpp
- src/platform/macos/misc.mm
- src/platform/windows/input.cpp
- src/platform/windows/misc.cpp
- src/upnp.cpp
> docs(src): fix some doxygen warnings

- gh-pages-template/index.html
Adds a client section to the website.
> docs(website): add clients section

- cmake/prep/special_package_configuration.cmake
- packaging/linux/flatpak/dev.lizardbyte.sunshine.yml
- packaging/linux/flatpak/modules/xvfb/xvfb-run
- packaging/linux/flatpak/modules/xvfb/xvfb.json
xvfb was removed from flatpak's Builder BaseApp in https://github.com/flathub/org.flatpak.Builder.BaseApp/commit/402cd761f2ee29e2c334bbccb5d3534e942cb550
> build(flatpak): add xvfb locally

- .gitmodules
remove org.flatpak.Builder.BaseApp
> build(flatpak): remove org.flatpak.Builder.BaseApp

- .github/workflows/CI.yml
> ci(macos): adjust permissions for test binaries

- .github/workflows/update-homebrew-release.yml
- .github/workflows/update-pacman-repo.yml
- .github/workflows/update-winget-release.yml
- docker/archlinux.dockerfile
- packaging/linux/Arch/PKGBUILD
- Update PKGBUILD in pacman-repo, via a PR, when we create a stable release
- A few updates to the PKGBUILD to make it more inline with the pacman-repo and easier to `sed`
- A few updates to the archlinux dockerfile
> build(linux): sync PKGBUILD with pacman-repo

- docs/source/about/setup.rst
- docs/source/troubleshooting/general.rst
- docs/source/troubleshooting/linux.rst
Add notes about network testing with iPerf3.
(A few other minor documentation fixes)
> docs(troubleshoot): add network testing with iPerf3

- docker/ubuntu-22.04.dockerfile
Use CMake 3.30 for Ubuntu 22.04 docker as at least 3.25 is required for the upcoming PR.
> feat: Use CMake 3.30 for Ubuntu 22.04 docker

- docs/source/source_code/source_code.rst
> docs(source code): fix examples end alias

- packaging/linux/flatpak/flatpak-lint-baseline_repo.json
- packaging/sunshine.rb
Fixes new linting errors caused by:
- https://github.com/Homebrew/brew/commit/7bf7030db893e2dccda49ef61395c02af9613c3b
- https://github.com/flathub-infra/flatpak-builder-lint/pull/454 (probably?)
> build(linux): fix new lint errors

- .github/workflows/CI.yml
- docs/getting_started.md
- packaging/sunshine.rb
This PR adds a beta homebrew formula. It works by doing the following, AFTER the spec is validated.
1. rename the formula
2. Use sed to replace 2 values
3. Upload it to our homebrew repo
- Closes #2973
> feat(macos): add beta homebrew formula

- cmake/compile_definitions/linux.cmake
- docs/getting_started.md
Adds some missing cuda compute capabilities.
> fix(build): update cuda compatibilities

- DOCKER_README.md
Add some information based on https://github.com/LizardByte/Sunshine/discussions/2625#discussioncomment-9633893
References:
- https://github.com/games-on-whales/gow/blob/2e442292d79b9d996f886b8a03d22b6eb6bddf7b/compose/streamers/sunshine.yml#L40C96-L40C146
- https://github.com/jessfraz/dockerfiles/issues/359
> docs(docker): add ipc note

- DOCKER_README.md
- README.md
- docs/app_examples.md
- docs/building.md
- docs/changelog.md
- docs/configuration.md
- docs/contributing.md
- docs/gamestream_migration.md
- docs/getting_started.md
- docs/guides.md
- docs/legal.md
- docs/performance_tuning.md
- docs/third_party_packages.md
- docs/troubleshooting.md
Add interactive TOC per https://github.com/jothepro/doxygen-awesome-css/issues/157
> docs: add interactive table of contents

- docs/troubleshooting.md
Update docs to reflect current state after #3115 (AMD low latency on Linux) is merged.
> docs(troubleshooting): update note on AMD lowlatencyenc (Linux)

- docs/contributing.md
- gh-pages-template/index.html
Move from uno repo to dashboard repo.
> docs(metadata): update urls

- gh-pages-template/index.html
> fix(gh-pages): update uno url

- .github/workflows/CI.yml
> ci(windows): fix typo in publisher name

- packaging/linux/Arch/PKGBUILD
- packaging/linux/flatpak/dev.lizardbyte.app.Sunshine.yml
- packaging/macos/Portfile
- packaging/sunshine.rb
> build(cmake): fix typo in publisher name variable

- src_assets/common/assets/web/ResourceCard.vue
> fix(web-ui): broken url

- src/httpcommon.cpp
Use stronger SSL and TLS version in curl, for `download_file` function. This function is used to download cover images from our games database.
- Fixes https://sonarcloud.io/project/issues?open=AZFC16X9i5a_X_62txoX&id=LizardByte_Sunshine
> fix(curl): use stronger SSL and TLS versions

- .codeql-prebuild-cpp-Windows.sh
- .github/workflows/CI.yml
- cmake/dependencies/Boost_Sunshine.cmake
- src/platform/common.h
- src/platform/linux/misc.cpp
- src/platform/macos/misc.mm
- src/platform/windows/display_base.cpp
- src/platform/windows/misc.cpp
- src/process.cpp
- src/process.h
- src/system_tray.cpp
Migrate the code to be boost 1.86 compatible.
- Resolves https://github.com/LizardByte/Sunshine/issues/3248
> fix(boost)!: migrate boost to 1.86

- .github/workflows/ci-copr.yml
- packaging/linux/fedora/sunshine.spec
- src_assets/linux/misc/postinst
Fix version number for copr build. Follow up for #3239.
> build(fedora): fix version variables and skip post on rpm-ostree

- .github/ISSUE_TEMPLATE/bug-report.yml
Various updates to issue template.
> chore(github): update issue template

- .github/workflows/CI.yml
See https://github.com/gcovr/gcovr/issues/984
> ci(windows): pin gcovr to < 8.0

- packaging/linux/flatpak/dev.lizardbyte.app.Sunshine.yml
`libayatanna-appindicator` was recently added to flatpak `shared-modules`
> build(flatpak): migrate to libayatanna-appindicator

- .github/workflows/CI.yml
PR based on changes in https://github.com/LizardByte/libdisplaydevice/pull/24
> ci(coverage): simplify gcovr exclusions

- docs/troubleshooting.md
Update documentation with troubleshooting info for blur in KDE.
> docs(troubleshooting): Add workaround for "blur" plugin in KDE

- gh-pages-template/index.html
- src/system_tray.cpp
- src/system_tray.h
No longer accepting donations through mee6.
> chore: remove mee6

- docs/getting_started.md
> docs: fix typo in docker url

- src_assets/common/assets/web/index.html
Fixes typo in href.
- Fixes #3491
> fix(ui): remove extra slash in logs href

- docs/building.md
Doing a fresh MSYS2 setup and it seems that this dependency is needed.
> fix(docs): use ucrt64 doxygen for msys2

- docs/guides.md
Blog url was incorrect... thanks co-pilot.
> docs(guides): fix blog url

- docs/configuration.md
- src/config.cpp
- src_assets/common/assets/web/config.html
- src_assets/common/assets/web/configs/tabs/audiovideo/DisplayDeviceOptions.vue
- src_assets/common/assets/web/public/assets/locale/en.json
Disabling this by default as it is causing a lot of pain with many users (as observed in GitHub issues, discord, and reddit comments).
> fix(dd_config)!: disable by default

- package.json
> build(deps): bump vite from 4.5.2 to 4.5.9

- .github/workflows/CI.yml
> ci(homebrew): fix python install

- README.md
Fixes a rendering whitespace issue that occurs only in GitHub.
> docs(readme): fix badge whitespace

- README.md
- docs/contributing.md
Adding sponsors/supporters section as a way to highlight those who support the project.
> docs(readme): add sponsors

- README.md
Add GitHub and CrowdIn contributor images to readme. Thanks to all contributors!
> docs(readme): add contributor images

- gh-pages-template/index.html
Ignore version tags for CrowdIn.
> chore(gh-pages): add crowdin-ignore class

- docs/troubleshooting.md
- packaging/linux/flatpak/scripts/remove-additional-install.sh
- src/platform/linux/input/inputtino_gamepad.cpp
- src_assets/linux/misc/60-sunshine.rules
Update Sunshine rules for inputtino.
See:
- https://games-on-whales.github.io/wolf/stable/user/quickstart.html#_virtual_devices_support
- https://github.com/LizardByte/Sunshine/pull/1127
- https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules
TODO:
- Fixes #3569
> fix(linux): update sunshine rules

- src/platform/common.h
- src/platform/linux/input/inputtino_gamepad.cpp
- src/stream.cpp
This is part of a series of PRs:
- https://github.com/moonlight-stream/moonlight-common-c/pull/102 to extend the Moonlight protocol for this new event
- https://github.com/moonlight-stream/moonlight-qt/pull/1561 requires the changes in `moonlight-common-c` and exposes the adaptive trigger events via SDL
- https://github.com/games-on-whales/inputtino/pull/26 to expose the adaptive triggers events in Linux
- https://github.com/LizardByte/Sunshine/pull/3738  requires the changes in `moonlight-common-c` and `inputtino` and delivers the adaptive trigger events to Moonlight clients
https://github.com/user-attachments/assets/c403a181-bae7-4b79-a5b6-7278f5bba97e
> feat(input/linux): DualSense adaptive trigger support

- README.md
See https://github.com/LizardByte/contributors/pull/13
> docs(readme): update crowdin image url

- packaging/sunshine.rb
> build(homebrew): explicitly set cxx standard

- packaging/sunshine.rb
This PR adds system tray support on Linux for the homebrew package. This is accomplished via adding "resources". The patches are borrowed from the flatpak `libayatana-appindicator` module. The build process is also replicating the flatpak module.
> fix(homebrew): enable system tray for linux

- .codeql-prebuild-cpp-Windows.sh
- .github/workflows/CI.yml
Pin gcc to v14 due to https://github.com/msys2/MINGW-packages/issues/22160#issuecomment-2835667514
> ci(windows): pin gcc to 14

- package.json
> build(deps): bump vite from 4.5.9 to 4.5.14

- docs/contributing.md
CLion is now free for non-commercial usage. See https://blog.jetbrains.com/clion/2025/05/clion-is-now-free-for-non-commercial-use/
> docs(contributing): update CLion description

- gh-pages-template/index.html
Add the [Nintendo 3DS client](https://github.com/zoeyjodon/moonlight-N3DS) to the website.
> docs(website): Add Nintendo 3DS client

- scripts/linux_build.sh
Fixing script bug, discovered by discord user. https://discord.com/channels/804382334370578482/1380742153436921856/1380755840834994228
> build(linux): disable cuda option in cmake when --skip-cuda arg is passed

- docs/getting_started.md
- packaging/linux/Arch/PKGBUILD
gcc13 has been removed from Arch repos.
> build(arch-packaging): update gcc

- .github/workflows/ci-copr.yml
- .github/workflows/ci.yml
This PR slightly refactors CI for copr builds. The main advantage is that the `rpm` files will be included in release assets.
Additionally, the job were renamed to use `-` instead of `_`.
> ci(copr): refactor copr-ci

- src/platform/linux/misc.cpp
Zeroing the VLAs isn't actually necessary since we already initialized most of the fields anyway. The `iovec` and `mmsghdr` structs are part of the Linux userspace ABI, so they can't be changed in ways that would make zeroing the whole struct necessary (like adding a new field).
Closes #3998
> fix(build): remove VLA zeroing to fix Clang build

- .github/workflows/ci.yml
This line should not have been removed in https://github.com/LizardByte/Sunshine/pull/4056
> ci(copr): disable copr for push event

- cmake/compile_definitions/linux.cmake
Make sure libdrm is found for both DRM (KMS) and Wayland capture methods if they are specified individually.
- Closes https://github.com/LizardByte/Sunshine/pull/4063
> build(wayland): ensure libdrm is found

- .github/workflows/ci-copr.yml
- .github/workflows/ci-homebrew.yml
- .github/workflows/ci.yml
This PR bumps `LizardByte/actions` accross the workflows.
- This allows virustotal results for the copr artifacts added when the release is updated.
- The release notes will be correctly modified for the updated release, whereas they are currently re-generated incorrectly.
> ci(copr-ci): fix release notes

- cmake/targets/common.cmake
- packaging/sunshine.rb
- tests/CMakeLists.txt
- tools/CMakeLists.txt
This PR moves Sunshine, tools, and tests to CXX 23. This is being done in order to make sonar cloud warnings more relevant as often the warnings apply only to c++23 or newer, and some contributors may end up creating bugs by fixing those warnings for sonar.
> build(cmake): bump c++ to 23

- .gitignore
- scripts/linux_build.sh
I noticed two places in `linux_build.sh` that missed a `sudo` in order to actually work if used by an unprivileged user:
- when setting up gcc
- when locally compiling (and installing!) doxygen.
Additionally, the script will now `pushd` into the build directory before compiling doxygen, and `popd` out when finished.
> build(linux): linux_build.sh fixes (gcc/doxygen)

- packaging/sunshine.rb
This PR is draft for now, but the goal is to migrate all our "resources" in the homebrew formula to actual brew packages.
TODO:
> build(homebrew): use new brew packages

- cmake/packaging/linux.cmake
Docker image depends on libgbm but it's not included. This is probably not noticed outside of docker because it's automatically installed in other cases.
- Fixes https://github.com/LizardByte/Sunshine/issues/4112
> fix(packaging/linux): depend on libgbm

- src/platform/windows/audio.cpp
- src/platform/windows/display.h
- src/platform/windows/display_vram.cpp
- src/platform/windows/display_wgc.cpp
- src/platform/windows/input.cpp
- src/platform/windows/misc.cpp
- src/platform/windows/misc.h
- src/platform/windows/nvprefs/nvprefs_common.h
- src/platform/windows/publish.cpp
- tools/audio.cpp
- tools/sunshinesvc.cpp
Fixes cpp:S3806 sonarcloud issues.
- Fixes https://sonarcloud.io/project/issues?rules=cpp%3AS3806&issueStatuses=OPEN%2CCONFIRMED&id=LizardByte_Sunshine
> style(sonar): fix cpp:S3806

- src/platform/windows/audio.cpp
- src/platform/windows/input.cpp
- src/process.cpp
Fixes sonarcloud cpp:S1110 issues.
- Fixes https://sonarcloud.io/project/issues?rules=cpp%3AS1110&issueStatuses=OPEN%2CCONFIRMED&id=LizardByte_Sunshine
> style(sonar): fix cpp:S1110

- cmake/dependencies/common.cmake
- src/platform/linux/vaapi.cpp
- src/video.cpp
This is the companion PR to https://github.com/LizardByte/build-deps/pull/482 that adds the changes to Sunshine required to support FFmpeg 8.0.
Testing checklist:
> build(deps): Update to FFmpeg 8.0 branch

- .github/workflows/ci-flatpak.yml
- .github/workflows/ci-linux.yml
- .github/workflows/ci.yml
This PR migrates to the new `more_space` action.
> ci(linux): migrate to LizardByte/actions/actions/more_space action

- docker/clion-toolchain.dockerfile
Install npm using package manager instead of nvm on clion-toolchain dockerfile and add gbm.
> build(toolchain): fix missing dependencies on clion-toolchain

- src/config.cpp
Adds the missing default value for ds5_inputtino_randomize_mac to input_t input in config.cpp
This was missed during development in PR #4158 and needs to be corrected for the default of ```native_pen_touch``` to be defined (as it is the last value for input_t and currently is not explicitly defined).
> fix(input): Add missing default value for ds5_inputtino_randomize_mac

- .github/copilot-instructions.md
- tests/CMakeLists.txt
- tests/integration/test_locale_consistency.cpp
This PR was inspired by https://github.com/LizardByte/Sunshine/pull/4215 and adds tests for when new localization files are added. This should ensure we don't miss anything when languages are added.
Additionally, there is basic validation done to the json files so should catch any major syntax errors in the `en.json`.
> test(locale): test that languages are properly defined

- docker/archlinux.dockerfile
- packaging/linux/Arch/PKGBUILD
- packaging/linux/Arch/sunshine.install
This is mirroring the changes done in https://github.com/LizardByte/pacman-repo/pull/52 to the main repository.
> fix(packaging/Arch): make cuda and unit tests optional

- packaging/linux/Arch/PKGBUILD
Correcting a small forgotten edge-case: if `cuda` was freshly installed, its `/etc/profile.d/cuda.sh` will not have been sourced in the current session; therefore we must set the variables manually if that is the case for the build to proceed.
> fix(packaging/Arch): do not fail if cuda was freshly installed

- README.md
- docs/app_examples.md
- docs/building.md
- docs/contributing.md
- docs/gamestream_migration.md
- docs/getting_started.md
- docs/legal.md
- docs/third_party_packages.md
- docs/troubleshooting.md
This PR moves the large majority of admonitions in docs to GitHub style. This will be possible to merge after dependabot updates doxyconfig, per https://github.com/LizardByte/doxyconfig/pull/36
> docs: use github admonition styles

- src_assets/linux/misc/60-sunshine.rules
Fix warnings from `udevadm verify`:
```
/usr/lib/udev/rules.d/60-sunshine.rules:8 style: a comma between tokens is expected.
/usr/lib/udev/rules.d/60-sunshine.rules:8 style: a comma between tokens is expected.
/usr/lib/udev/rules.d/60-sunshine.rules: udev rules have style issues.
```
None.
None.
None.
> fix(Linux): udev rules style issues

- packaging/linux/Arch/PKGBUILD
Remove cuda as required dependency for AUR. See https://github.com/LizardByte/pacman-repo/pull/54
> build(packaging/Linux): remove cuda as required dependency on aur

- src_assets/windows/misc/service/install-service.bat
Alternate quoting in install-service.bat. Both triple quotes and this style both work on my system. I will wait to see if we get more feedback about the service not working, though I suspect those reports are more from AV blocking stuff.
> fix(windows): Correct binPath syntax in install-service.bat

- .github/workflows/ci-copr.yml
When the copr-ci workflow would update a release it would always set it to pre-released, even if it was already marked as "latest".
> ci(copr): Trigger release job only for non-prereleases

- docker/archlinux.dockerfile
- docker/debian-trixie.dockerfile
- docker/ubuntu-22.04.dockerfile
- docker/ubuntu-24.04.dockerfile
- scripts/linux_build.sh
Dockerfiles for Arch, Debian, and Ubuntu now use a separate 'deps' stage to cache dependency installation, improving build efficiency. The build script 'linux_build.sh' is refactored to support discrete build steps (deps, cmake, validation, build, package, cleanup, all) via a new --step argument, enabling more granular control and better Docker layer caching. Version requirements for cmake and doxygen are now centralized, and the script's logic is modularized into step-specific functions.
> build(Linux): Refactor Dockerfiles and build script for multi-stage, step-based builds
